Point Cloud Library (PCL): pcl::PolynomialCalculationsT< real > Class Template Reference
pcl::PolynomialCalculationsT< real > Class Template Reference
Module common
This provides some functionality for polynomials, like finding roots or approximating bivariate polynomials.
#include <pcl/common/polynomial_calculations.h>
Classes
struct Parameters
Parameters used in this class.
Public Member Functions
PolynomialCalculationsT ()
~PolynomialCalculationsT ()
void solveQuarticEquation (real a, real b, real c, real d, real e, std::vector< real > &roots) const
Solves an equation of the form ax^4 + bx^3 + cx^2 +dx + e = 0 See http://en.wikipedia.org/wiki/Quartic_equation#Summary_of_Ferrari.27s_method.
void solveCubicEquation (real a, real b, real c, real d, std::vector< real > &roots) const
Solves an equation of the form ax^3 + bx^2 + cx + d = 0 See http://en.wikipedia.org/wiki/Cubic_equation.
void solveQuadraticEquation (real a, real b, real c, std::vector< real > &roots) const
Solves an equation of the form ax^2 + bx + c = 0 See http://en.wikipedia.org/wiki/Quadratic_equation.
void solveLinearEquation (real a, real b, std::vector< real > &roots) const
Solves an equation of the form ax + b = 0.
BivariatePolynomialT< real > bivariatePolynomialApproximation (std::vector< Eigen::Matrix< real, 3, 1 >, Eigen::aligned_allocator< Eigen::Matrix< real, 3, 1 > > > &samplePoints, unsigned int polynomial_degree, bool &error) const
Get the bivariate polynomial approximation for Z(X,Y) from the given sample points.
bool bivariatePolynomialApproximation (std::vector< Eigen::Matrix< real, 3, 1 >, Eigen::aligned_allocator< Eigen::Matrix< real, 3, 1 > > > &samplePoints, unsigned int polynomial_degree, BivariatePolynomialT< real > &ret) const
Same as above, using a reference for the return value.
void setZeroValue (real new_zero_value)
Set the minimum value under which values are considered zero.
Protected Member Functions
bool isNearlyZero (real d) const
check if fabs(d)<zeroValue
bool sqrtIsNearlyZero (real d) const
check if sqrt(fabs(d))<zeroValue
Protected Attributes
Parameters parameters_
Detailed Description
template<typename real>
class pcl::PolynomialCalculationsT< real >
This provides some functionality for polynomials, like finding roots or approximating bivariate polynomials.
Author
Bastian Steder
Definition at line 50 of file polynomial_calculations.h.
Constructor & Destructor Documentation
template<typename real > pcl::PolynomialCalculationsT< real >::PolynomialCalculationsT ()
Definition at line 44 of file polynomial_calculations.hpp.
template<typename real > pcl::PolynomialCalculationsT< real >::~PolynomialCalculationsT ()
Definition at line 51 of file polynomial_calculations.hpp.
Member Function Documentation
template<typename real > pcl::BivariatePolynomialT< real > pcl::PolynomialCalculationsT< real >::bivariatePolynomialApproximation (std::vector< Eigen::Matrix< real, 3, 1 >, Eigen::aligned_allocator< Eigen::Matrix< real, 3, 1 > > > & samplePoints, unsigned int polynomial_degree, bool & error) const inline
Get the bivariate polynomial approximation for Z(X,Y) from the given sample points.
The parameters a,b,c,... for the polynom are returned. The order is, e.g., for degree 1: ax+by+c and for degree 2: ax²+bxy+cx+dy²+ey+f. error is set to true if the approximation did not work for any reason (not enough points, matrix not invertible, etc.)
Definition at line 414 of file polynomial_calculations.hpp.
template<typename real > bool pcl::PolynomialCalculationsT< real >::bivariatePolynomialApproximation (std::vector< Eigen::Matrix< real, 3, 1 >, Eigen::aligned_allocator< Eigen::Matrix< real, 3, 1 > > > & samplePoints, unsigned int polynomial_degree, pcl::BivariatePolynomialT< real > & ret) const inline
Same as above, using a reference for the return value.
Definition at line 426 of file polynomial_calculations.hpp.
References pcl::BivariatePolynomialT< real >::getNoOfParametersFromDegree(), pcl::BivariatePolynomialT< real >::parameters, and pcl::BivariatePolynomialT< real >::setDegree().
template<typename real > bool pcl::PolynomialCalculationsT< real >::isNearlyZero (real d) const inline protected
check if fabs(d)<zeroValue
Definition at line 112 of file polynomial_calculations.h.
References pcl::PolynomialCalculationsT< real >::parameters_, and pcl::PolynomialCalculationsT< real >::Parameters::zero_value.
Referenced by pcl::PolynomialCalculationsT< real >::solveCubicEquation(), pcl::PolynomialCalculationsT< real >::solveLinearEquation(), pcl::PolynomialCalculationsT< real >::solveQuadraticEquation(), and pcl::PolynomialCalculationsT< real >::solveQuarticEquation().
template<typename real > void pcl::PolynomialCalculationsT< real >::setZeroValue (real new_zero_value) inline
Set the minimum value under which values are considered zero.
Definition at line 106 of file polynomial_calculations.h.
References pcl::PolynomialCalculationsT< real >::parameters_, and pcl::PolynomialCalculationsT< real >::Parameters::setZeroValue().
template<typename real > void pcl::PolynomialCalculationsT< real >::solveCubicEquation (real a, real b, real c, real d, std::vector< real > & roots) const inline
Solves an equation of the form ax^3 + bx^2 + cx + d = 0 See http://en.wikipedia.org/wiki/Cubic_equation.
Definition at line 158 of file polynomial_calculations.hpp.
References pcl::PolynomialCalculationsT< real >::isNearlyZero(), and pcl::PolynomialCalculationsT< real >::solveQuadraticEquation().
Referenced by pcl::PolynomialCalculationsT< real >::solveQuarticEquation().
template<typename real > void pcl::PolynomialCalculationsT< real >::solveLinearEquation (real a, real b, std::vector< real > & roots) const inline
Solves an equation of the form ax + b = 0.
Definition at line 69 of file polynomial_calculations.hpp.
References pcl::PolynomialCalculationsT< real >::isNearlyZero().
Referenced by pcl::PolynomialCalculationsT< real >::solveQuadraticEquation().
template<typename real > void pcl::PolynomialCalculationsT< real >::solveQuadraticEquation (real a, real b, real c, std::vector< real > & roots) const inline
Solves an equation of the form ax^2 + bx + c = 0 See http://en.wikipedia.org/wiki/Quadratic_equation.
Definition at line 102 of file polynomial_calculations.hpp.
References pcl::PolynomialCalculationsT< real >::isNearlyZero(), pcl::PolynomialCalculationsT< real >::solveLinearEquation(), and pcl::PolynomialCalculationsT< real >::sqrtIsNearlyZero().
Referenced by pcl::PolynomialCalculationsT< real >::solveCubicEquation(), and pcl::PolynomialCalculationsT< real >::solveQuarticEquation().
template<typename real > void pcl::PolynomialCalculationsT< real >::solveQuarticEquation (real a, real b, real c, real d, real e, std::vector< real > & roots) const inline
Solves an equation of the form ax^4 + bx^3 + cx^2 +dx + e = 0 See http://en.wikipedia.org/wiki/Quartic_equation#Summary_of_Ferrari.27s_method.
Definition at line 260 of file polynomial_calculations.hpp.
References pcl::PolynomialCalculationsT< real >::isNearlyZero(), pcl::PolynomialCalculationsT< real >::solveCubicEquation(), pcl::PolynomialCalculationsT< real >::solveQuadraticEquation(), and pcl::PolynomialCalculationsT< real >::sqrtIsNearlyZero().
template<typename real > bool pcl::PolynomialCalculationsT< real >::sqrtIsNearlyZero (real d) const inline protected
check if sqrt(fabs(d))<zeroValue
Definition at line 119 of file polynomial_calculations.h.
References pcl::PolynomialCalculationsT< real >::parameters_, and pcl::PolynomialCalculationsT< real >::Parameters::sqr_zero_value.
Referenced by pcl::PolynomialCalculationsT< real >::solveQuadraticEquation(), and pcl::PolynomialCalculationsT< real >::solveQuarticEquation().
Member Data Documentation
template<typename real > Parameters pcl::PolynomialCalculationsT< real >::parameters_ protected
Definition at line 125 of file polynomial_calculations.h.
Referenced by pcl::PolynomialCalculationsT< real >::isNearlyZero(), pcl::PolynomialCalculationsT< real >::setZeroValue(), and pcl::PolynomialCalculationsT< real >::sqrtIsNearlyZero().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/common/polynomial_calculations.h
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/common/impl/polynomial_calculations.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:54