Point Cloud Library (PCL): pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType > Class Template Reference
pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType > Class Template Reference
Utility class for evaluating a fern.
#include <pcl/ml/ferns/fern_evaluator.h>
Public Member Functions
FernEvaluator ()
Constructor.
virtual ~FernEvaluator ()
Destructor.
void evaluate (pcl::Fern< FeatureType, NodeType > &fern, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< LabelType > &label_data)
Evaluates the specified examples using the supplied tree.
void evaluateAndAdd (pcl::Fern< FeatureType, NodeType > &fern, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< LabelType > &label_data)
Evaluates the specified examples using the supplied tree and adds the results to the supplied results array.
void getNodes (pcl::Fern< FeatureType, NodeType > &fern, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< NodeType * > &nodes)
Evaluates the specified examples using the supplied tree.
Detailed Description
template<class FeatureType, class DataSet, class LabelType, class ExampleIndex, class NodeType>
class pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >
Utility class for evaluating a fern.
Definition at line 59 of file fern_evaluator.h.
Constructor & Destructor Documentation
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::FernEvaluator ()
Constructor.
Definition at line 52 of file fern_evaluator.hpp.
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::~FernEvaluator () virtual
Destructor.
Definition at line 58 of file fern_evaluator.hpp.
Member Function Documentation
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluate (pcl::Fern< FeatureType, NodeType > & fern, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< LabelType > & label_data)
Evaluates the specified examples using the supplied tree.
Parameters
[in] fern The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] examples The examples that have to be evaluated.
[out] label_data The destination for the resulting label data.
Definition at line 65 of file fern_evaluator.hpp.
References pcl::Fern< FeatureType, NodeType >::accessFeature(), pcl::Fern< FeatureType, NodeType >::accessThreshold(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndices(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getLabelOfNode(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getNumOfBranches(), and pcl::Fern< FeatureType, NodeType >::getNumOfFeatures().
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluateAndAdd (pcl::Fern< FeatureType, NodeType > & fern, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< LabelType > & label_data)
Evaluates the specified examples using the supplied tree and adds the results to the supplied results array.
Parameters
[in] fern The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] examples The examples that have to be evaluated.
[out] label_data The destination where the resulting label data is added to.
Definition at line 109 of file fern_evaluator.hpp.
References pcl::Fern< FeatureType, NodeType >::accessFeature(), pcl::Fern< FeatureType, NodeType >::accessThreshold(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndices(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getLabelOfNode(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getNumOfBranches(), and pcl::Fern< FeatureType, NodeType >::getNumOfFeatures().
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::FernEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::getNodes (pcl::Fern< FeatureType, NodeType > & fern, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< NodeType * > & nodes)
Evaluates the specified examples using the supplied tree.
Parameters
[in] fern The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] examples The examples that have to be evaluated.
[out] nodes The leaf-nodes reached while evaluation.
Definition at line 151 of file fern_evaluator.hpp.
References pcl::Fern< FeatureType, NodeType >::accessFeature(), pcl::Fern< FeatureType, NodeType >::accessThreshold(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndices(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getNumOfBranches(), and pcl::Fern< FeatureType, NodeType >::getNumOfFeatures().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/ml/include/pcl/ml/ferns/fern_evaluator.h
/home/travis/build/PointCloudLibrary/pcl/ml/include/pcl/ml/impl/ferns/fern_evaluator.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:33