Point Cloud Library (PCL): pcl::VoxelGridOcclusionEstimation< PointT > Class Template Reference
pcl::VoxelGridOcclusionEstimation< PointT > Class Template Reference
Module filters
VoxelGrid to estimate occluded space in the scene.
#include <pcl/filters/voxel_grid_occlusion_estimation.h>
Public Member Functions
VoxelGridOcclusionEstimation ()
Empty constructor.
virtual ~VoxelGridOcclusionEstimation ()
Destructor.
void initializeVoxelGrid ()
Initialize the voxel grid, needs to be called first Builts the voxel grid and computes additional values for the ray traversal algorithm.
int occlusionEstimation (int &out_state, const Eigen::Vector3i &in_target_voxel)
Computes the state (free = 0, occluded = 1) of the voxel after utilizing a ray traversal algorithm to a target voxel in (i, j, k) coordinates.
int occlusionEstimation (int &out_state, std::vector< Eigen::Vector3i, Eigen::aligned_allocator< Eigen::Vector3i > > &out_ray, const Eigen::Vector3i &in_target_voxel)
Computes the state (free = 0, occluded = 1) of the voxel after utilizing a ray traversal algorithm to a target voxel in (i, j, k) coordinates.
int occlusionEstimationAll (std::vector< Eigen::Vector3i, Eigen::aligned_allocator< Eigen::Vector3i > > &occluded_voxels)
Computes the voxel coordinates (i, j, k) of all occluded voxels in the voxel grid.
PointCloud getFilteredPointCloud ()
Returns the voxel grid filtered point cloud.
Eigen::Vector3f getMinBoundCoordinates ()
Returns the minimum bounding of coordinates of the voxel grid (x,y,z).
Eigen::Vector3f getMaxBoundCoordinates ()
Returns the maximum bounding of coordinates of the voxel grid (x,y,z).
Eigen::Vector4f getCentroidCoordinate (const Eigen::Vector3i &ijk)
Returns the corresponding centroid (x,y,z) coordinates in the grid of voxel (i,j,k).
Public Member Functions inherited from pcl::VoxelGrid< PointT >
VoxelGrid ()
Empty constructor.
virtual ~VoxelGrid ()
Destructor.
void setLeafSize (const Eigen::Vector4f &leaf_size)
Set the voxel grid leaf size.
void setLeafSize (float lx, float ly, float lz)
Set the voxel grid leaf size.
Eigen::Vector3f getLeafSize () const
Get the voxel grid leaf size.
void setDownsampleAllData (bool downsample)
Set to true if all fields need to be downsampled, or false if just XYZ.
bool getDownsampleAllData () const
Get the state of the internal downsampling parameter (true if all fields need to be downsampled, false if just XYZ).
void setMinimumPointsNumberPerVoxel (unsigned int min_points_per_voxel)
Set the minimum number of points required for a voxel to be used.
unsigned int getMinimumPointsNumberPerVoxel () const
Return the minimum number of points required for a voxel to be used.
void setSaveLeafLayout (bool save_leaf_layout)
Set to true if leaf layout information needs to be saved for later access.
bool getSaveLeafLayout () const
Returns true if leaf layout information will to be saved for later access.
Eigen::Vector3i getMinBoxCoordinates () const
Get the minimum coordinates of the bounding box (after filtering is performed).
Eigen::Vector3i getMaxBoxCoordinates () const
Get the minimum coordinates of the bounding box (after filtering is performed).
Eigen::Vector3i getNrDivisions () const
Get the number of divisions along all 3 axes (after filtering is performed).
Eigen::Vector3i getDivisionMultiplier () const
Get the multipliers to be applied to the grid coordinates in order to find the centroid index (after filtering is performed).
int getCentroidIndex (const PointT &p) const
Returns the index in the resulting downsampled cloud of the specified point.
std::vector< int > getNeighborCentroidIndices (const PointT &reference_point, const Eigen::MatrixXi &relative_coordinates) const
Returns the indices in the resulting downsampled cloud of the points at the specified grid coordinates, relative to the grid coordinates of the specified point (or -1 if the cell was empty/out of bounds).
std::vector< int > getLeafLayout () const
Returns the layout of the leafs for fast access to cells relative to current position.
Eigen::Vector3i getGridCoordinates (float x, float y, float z) const
Returns the corresponding (i,j,k) coordinates in the grid of point (x,y,z).
int getCentroidIndexAt (const Eigen::Vector3i &ijk) const
Returns the index in the downsampled cloud corresponding to a given set of coordinates.
void setFilterFieldName (const std::string &field_name)
Provide the name of the field to be used for filtering data.
std::string const getFilterFieldName () const
Get the name of the field used for filtering.
void setFilterLimits (const double &limit_min, const double &limit_max)
Set the field filter limits.
void getFilterLimits (double &limit_min, double &limit_max) const
Get the field filter limits (min/max) set by the user.
void setFilterLimitsNegative (const bool limit_negative)
Set to true if we want to return the data outside the interval specified by setFilterLimits (min, max).
void getFilterLimitsNegative (bool &limit_negative) const
Get whether the data outside the interval (min/max) is to be returned (true) or inside (false).
bool getFilterLimitsNegative () const
Get whether the data outside the interval (min/max) is to be returned (true) or inside (false).
Public Member Functions inherited from pcl::Filter< PointT >
Filter (bool extract_removed_indices=false)
Empty constructor.
virtual ~Filter ()
Empty destructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PointCloud &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (size_t row_start, size_t col_start, size_t nb_rows, size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Types
typedef Filter< PointT >
::PointCloud PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
Protected Types inherited from pcl::VoxelGrid< PointT >
typedef Filter< PointT >
::PointCloud PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef pcl::traits::fieldList
< PointT >::type FieldList
Protected Member Functions
float rayBoxIntersection (const Eigen::Vector4f &origin, const Eigen::Vector4f &direction)
Returns the scaling value (tmin) were the ray intersects with the voxel grid bounding box.
int rayTraversal (const Eigen::Vector3i &target_voxel, const Eigen::Vector4f &origin, const Eigen::Vector4f &direction, const float t_min)
Returns the state of the target voxel (0 = visible, 1 = occupied) unsing a ray traversal algorithm.
int rayTraversal (std::vector< Eigen::Vector3i, Eigen::aligned_allocator< Eigen::Vector3i > > &out_ray, const Eigen::Vector3i &target_voxel, const Eigen::Vector4f &origin, const Eigen::Vector4f &direction, const float t_min)
Returns the state of the target voxel (0 = visible, 1 = occupied) and the voxels penetrated by the ray unsing a ray traversal algorithm.
float round (float d)
Returns a rounded value.
Eigen::Vector3i getGridCoordinatesRound (float x, float y, float z)
Returns the corresponding (i,j,k) coordinates in the grid of point (x,y,z).
Protected Member Functions inherited from pcl::VoxelGrid< PointT >
void applyFilter (PointCloud &output)
Downsample a Point Cloud using a voxelized grid approach.
Protected Member Functions inherited from pcl::Filter< PointT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
bool initialized_
Eigen::Vector4f sensor_origin_
Eigen::Quaternionf sensor_orientation_
Eigen::Vector4f b_min_
Eigen::Vector4f b_max_
PointCloud filtered_cloud_
Protected Attributes inherited from pcl::VoxelGrid< PointT >
Eigen::Vector4f leaf_size_
The size of a leaf.
Eigen::Array4f inverse_leaf_size_
Internal leaf sizes stored as 1/leaf_size_ for efficiency reasons.
bool downsample_all_data_
Set to true if all fields need to be downsampled, or false if just XYZ.
bool save_leaf_layout_
Set to true if leaf layout information needs to be saved in leaf_layout_.
std::vector< int > leaf_layout_
The leaf layout information for fast access to cells relative to current position.
Eigen::Vector4i min_b_
The minimum and maximum bin coordinates, the number of divisions, and the division multiplier.
Eigen::Vector4i max_b_
Eigen::Vector4i div_b_
Eigen::Vector4i divb_mul_
std::string filter_field_name_
The desired user filter field name.
double filter_limit_min_
The minimum allowed filter value a point will be considered from.
double filter_limit_max_
The maximum allowed filter value a point will be considered from.
bool filter_limit_negative_
Set to true if we want to return the data outside (filter_limit_min_;filter_limit_max_).
unsigned int min_points_per_voxel_
Minimum number of points per voxel for the centroid to be computed.
Protected Attributes inherited from pcl::Filter< PointT >
IndicesPtr removed_indices_
Indices of the points that are removed.
std::string filter_name_
The filter name.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Additional Inherited Members
Public Types inherited from pcl::VoxelGrid< PointT >
typedef boost::shared_ptr
< VoxelGrid< PointT > > Ptr
typedef boost::shared_ptr
< const VoxelGrid< PointT > > ConstPtr
Public Types inherited from pcl::Filter< PointT >
typedef boost::shared_ptr
< Filter< PointT > > Ptr
typedef boost::shared_ptr
< const Filter< PointT > > ConstPtr
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
Public Types inherited from pcl::PCLBase< PointT >
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Detailed Description
template<typename PointT>
class pcl::VoxelGridOcclusionEstimation< PointT >
VoxelGrid to estimate occluded space in the scene.
The ray traversal algorithm is implemented by the work of 'John Amanatides and Andrew Woo, A Fast Voxel Traversal Algorithm for Ray Tracing'
Author
Christian Potthast
Definition at line 56 of file voxel_grid_occlusion_estimation.h.
Member Typedef Documentation
template<typename PointT > typedef Filter<PointT>::PointCloud pcl::VoxelGridOcclusionEstimation< PointT >::PointCloud protected
Definition at line 65 of file voxel_grid_occlusion_estimation.h.
template<typename PointT > typedef PointCloud::ConstPtr pcl::VoxelGridOcclusionEstimation< PointT >::PointCloudConstPtr protected
Definition at line 67 of file voxel_grid_occlusion_estimation.h.
template<typename PointT > typedef PointCloud::Ptr pcl::VoxelGridOcclusionEstimation< PointT >::PointCloudPtr protected
Definition at line 66 of file voxel_grid_occlusion_estimation.h.
Constructor & Destructor Documentation
template<typename PointT > pcl::VoxelGridOcclusionEstimation< PointT >::VoxelGridOcclusionEstimation () inline
Empty constructor.
Definition at line 71 of file voxel_grid_occlusion_estimation.h.
References pcl::VoxelGridOcclusionEstimation< PointT >::initialized_, and pcl::VoxelGrid< PointT >::setSaveLeafLayout().
template<typename PointT > virtual pcl::VoxelGridOcclusionEstimation< PointT >::~VoxelGridOcclusionEstimation () inline virtual
Destructor.
Definition at line 78 of file voxel_grid_occlusion_estimation.h.
Member Function Documentation
template<typename PointT > Eigen::Vector4f pcl::VoxelGridOcclusionEstimation< PointT >::getCentroidCoordinate (const Eigen::Vector3i & ijk) inline
Returns the corresponding centroid (x,y,z) coordinates in the grid of voxel (i,j,k).
Parameters
[in] ijk the coordinate (i, j, k) of the voxel
Returns
the (x,y,z) coordinate of the voxel centroid
Definition at line 148 of file voxel_grid_occlusion_estimation.h.
References pcl::VoxelGridOcclusionEstimation< PointT >::b_min_, pcl::VoxelGrid< PointT >::leaf_size_, and pcl::VoxelGrid< PointT >::min_b_.
template<typename PointT > PointCloud pcl::VoxelGridOcclusionEstimation< PointT >::getFilteredPointCloud () inline
Returns the voxel grid filtered point cloud.
Returns
The voxel grid filtered point cloud
Definition at line 127 of file voxel_grid_occlusion_estimation.h.
References pcl::VoxelGridOcclusionEstimation< PointT >::filtered_cloud_.
template<typename PointT > Eigen::Vector3i pcl::VoxelGridOcclusionEstimation< PointT >::getGridCoordinatesRound (float x, float y, float z) inline protected
Returns the corresponding (i,j,k) coordinates in the grid of point (x,y,z).
Parameters
[in] x the X point coordinate to get the (i, j, k) index at
[in] y the Y point coordinate to get the (i, j, k) index at
[in] z the Z point coordinate to get the (i, j, k) index at
Definition at line 228 of file voxel_grid_occlusion_estimation.h.
References pcl::VoxelGrid< PointT >::inverse_leaf_size_, and pcl::VoxelGridOcclusionEstimation< PointT >::round().
template<typename PointT > Eigen::Vector3f pcl::VoxelGridOcclusionEstimation< PointT >::getMaxBoundCoordinates () inline
Returns the maximum bounding of coordinates of the voxel grid (x,y,z).
Returns
the maximum coordinates (x,y,z)
Definition at line 140 of file voxel_grid_occlusion_estimation.h.
References pcl::VoxelGridOcclusionEstimation< PointT >::b_max_.
template<typename PointT > Eigen::Vector3f pcl::VoxelGridOcclusionEstimation< PointT >::getMinBoundCoordinates () inline
Returns the minimum bounding of coordinates of the voxel grid (x,y,z).
Returns
the minimum coordinates (x,y,z)
Definition at line 134 of file voxel_grid_occlusion_estimation.h.
References pcl::VoxelGridOcclusionEstimation< PointT >::b_min_.
template<typename PointT > void pcl::VoxelGridOcclusionEstimation< PointT >::initializeVoxelGrid ()
Initialize the voxel grid, needs to be called first Builts the voxel grid and computes additional values for the ray traversal algorithm.
Definition at line 47 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > int pcl::VoxelGridOcclusionEstimation< PointT >::occlusionEstimation (int & out_state, const Eigen::Vector3i & in_target_voxel)
Computes the state (free = 0, occluded = 1) of the voxel after utilizing a ray traversal algorithm to a target voxel in (i, j, k) coordinates.
Parameters
[out] out_state The state of the voxel.
[in] in_target_voxel The target voxel coordinate (i, j, k) of the voxel.
Returns
0 upon success and -1 if an error occurs
Definition at line 70 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > int pcl::VoxelGridOcclusionEstimation< PointT >::occlusionEstimation (int & out_state, std::vector< Eigen::Vector3i, Eigen::aligned_allocator< Eigen::Vector3i > > & out_ray, const Eigen::Vector3i & in_target_voxel)
Computes the state (free = 0, occluded = 1) of the voxel after utilizing a ray traversal algorithm to a target voxel in (i, j, k) coordinates.
Additionally, this function returns the voxels penetrated of the ray-traversal algorithm till reaching the target voxel.
Parameters
[out] out_state The state of the voxel.
[out] out_ray The voxels penetrated of the ray-traversal algorithm.
[in] in_target_voxel The target voxel coordinate (i, j, k) of the voxel.
Returns
0 upon success and -1 if an error occurs
Definition at line 101 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > int pcl::VoxelGridOcclusionEstimation< PointT >::occlusionEstimationAll (std::vector< Eigen::Vector3i, Eigen::aligned_allocator< Eigen::Vector3i > > & occluded_voxels)
Computes the voxel coordinates (i, j, k) of all occluded voxels in the voxel grid.
Parameters
[out] occluded_voxels the coordinates (i, j, k) of all occluded voxels
Returns
0 upon success and -1 if an error occurs
Definition at line 133 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > float pcl::VoxelGridOcclusionEstimation< PointT >::rayBoxIntersection (const Eigen::Vector4f & origin, const Eigen::Vector4f & direction) protected
Returns the scaling value (tmin) were the ray intersects with the voxel grid bounding box.
(p_entry = origin + tmin * orientation)
Parameters
[in] origin The sensor origin
[in] direction The sensor orientation
Returns
the scaling value
Definition at line 176 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > int pcl::VoxelGridOcclusionEstimation< PointT >::rayTraversal (const Eigen::Vector3i & target_voxel, const Eigen::Vector4f & origin, const Eigen::Vector4f & direction, const float t_min) protected
Returns the state of the target voxel (0 = visible, 1 = occupied) unsing a ray traversal algorithm.
Parameters
[in] target_voxel The target voxel in the voxel grid with coordinate (i, j, k).
[in] origin The sensor origin.
[in] direction The sensor orientation
[in] t_min The scaling value (tmin).
Returns
The estimated voxel state.
Definition at line 243 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > int pcl::VoxelGridOcclusionEstimation< PointT >::rayTraversal (std::vector< Eigen::Vector3i, Eigen::aligned_allocator< Eigen::Vector3i > > & out_ray, const Eigen::Vector3i & target_voxel, const Eigen::Vector4f & origin, const Eigen::Vector4f & direction, const float t_min) protected
Returns the state of the target voxel (0 = visible, 1 = occupied) and the voxels penetrated by the ray unsing a ray traversal algorithm.
Parameters
[out] out_ray The voxels penetrated by the ray in (i, j, k) coordinates
[in] target_voxel The target voxel in the voxel grid with coordinate (i, j, k).
[in] origin The sensor origin.
[in] direction The sensor orientation
[in] t_min The scaling value (tmin).
Returns
The estimated voxel state.
Definition at line 337 of file voxel_grid_occlusion_estimation.hpp.
template<typename PointT > float pcl::VoxelGridOcclusionEstimation< PointT >::round (float d) inline protected
Returns a rounded value.
Parameters
[in] d
Returns
rounded value
Definition at line 216 of file voxel_grid_occlusion_estimation.h.
Referenced by pcl::VoxelGridOcclusionEstimation< PointT >::getGridCoordinatesRound().
Member Data Documentation
template<typename PointT > Eigen::Vector4f pcl::VoxelGridOcclusionEstimation< PointT >::b_max_ protected
Definition at line 242 of file voxel_grid_occlusion_estimation.h.
Referenced by pcl::VoxelGridOcclusionEstimation< PointT >::getMaxBoundCoordinates().
template<typename PointT > Eigen::Vector4f pcl::VoxelGridOcclusionEstimation< PointT >::b_min_ protected
Definition at line 242 of file voxel_grid_occlusion_estimation.h.
Referenced by pcl::VoxelGridOcclusionEstimation< PointT >::getCentroidCoordinate(), and pcl::VoxelGridOcclusionEstimation< PointT >::getMinBoundCoordinates().
template<typename PointT > PointCloud pcl::VoxelGridOcclusionEstimation< PointT >::filtered_cloud_ protected
Definition at line 245 of file voxel_grid_occlusion_estimation.h.
Referenced by pcl::VoxelGridOcclusionEstimation< PointT >::getFilteredPointCloud().
template<typename PointT > bool pcl::VoxelGridOcclusionEstimation< PointT >::initialized_ protected
Definition at line 236 of file voxel_grid_occlusion_estimation.h.
Referenced by pcl::VoxelGridOcclusionEstimation< PointT >::VoxelGridOcclusionEstimation().
template<typename PointT > Eigen::Quaternionf pcl::VoxelGridOcclusionEstimation< PointT >::sensor_orientation_ protected
Definition at line 239 of file voxel_grid_occlusion_estimation.h.
template<typename PointT > Eigen::Vector4f pcl::VoxelGridOcclusionEstimation< PointT >::sensor_origin_ protected
Definition at line 238 of file voxel_grid_occlusion_estimation.h.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/voxel_grid_occlusion_estimation.h
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/impl/voxel_grid_occlusion_estimation.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:25