Point Cloud Library (PCL): pcl::filters::Convolution< PointIn, PointOut > Class Template Reference
pcl::filters::Convolution< PointIn, PointOut > Class Template Reference
Module filters
Convolution is a mathematical operation on two functions f and g, producing a third function that is typically viewed as a modified version of one of the original functions.
#include <pcl/filters/convolution.h>
Public Types
enum BORDERS_POLICY { BORDERS_POLICY_IGNORE = -1, BORDERS_POLICY_MIRROR = 0, BORDERS_POLICY_DUPLICATE = 1 }
The borders policy available.
typedef pcl::PointCloud< PointIn > PointCloudIn
typedef PointCloudIn::Ptr PointCloudInPtr
typedef PointCloudIn::ConstPtr PointCloudInConstPtr
typedef pcl::PointCloud< PointOut > PointCloudOut
typedef boost::shared_ptr
< Convolution< PointIn,
PointOut > > Ptr
typedef boost::shared_ptr
< const Convolution< PointIn,
PointOut > > ConstPtr
Public Member Functions
Convolution ()
Constructor.
~Convolution ()
Empty destructor.
void setInputCloud (const PointCloudInConstPtr &cloud)
Provide a pointer to the input dataset.
void setKernel (const Eigen::ArrayXf &kernel)
Set convolving kernel.
void setBordersPolicy (int policy)
Set the borders policy.
int getBordersPolicy ()
Get the borders policy.
void setDistanceThreshold (const float &threshold)
const float & getDistanceThreshold () const
void setNumberOfThreads (unsigned int nr_threads=0)
Initialize the scheduler and set the number of threads to use.
void convolveRows (PointCloudOut &output)
Convolve a float image rows by a given kernel.
void convolveCols (PointCloudOut &output)
Convolve a float image columns by a given kernel.
void convolve (const Eigen::ArrayXf &h_kernel, const Eigen::ArrayXf &v_kernel, PointCloudOut &output)
Convolve point cloud with an horizontal kernel along rows then vertical kernel along columns : convolve separately.
void convolve (PointCloudOut &output)
Convolve point cloud with same kernel along rows and columns separately.
Protected Member Functions
void convolve_rows (PointCloudOut &output)
convolve rows and ignore borders
void convolve_cols (PointCloudOut &output)
convolve cols and ignore borders
void convolve_rows_mirror (PointCloudOut &output)
convolve rows and mirror borders
void convolve_cols_mirror (PointCloudOut &output)
convolve cols and mirror borders
void convolve_rows_duplicate (PointCloudOut &output)
convolve rows and duplicate borders
void convolve_cols_duplicate (PointCloudOut &output)
convolve cols and duplicate borders
void initCompute (PointCloudOut &output)
init compute is an internal method called before computation
void makeInfinite (PointOut &p)
template<>
void makeInfinite (pcl::RGB &p)
Protected Attributes
unsigned int threads_
The number of threads the scheduler should use.
Detailed Description
template<typename PointIn, typename PointOut>
class pcl::filters::Convolution< PointIn, PointOut >
Convolution is a mathematical operation on two functions f and g, producing a third function that is typically viewed as a modified version of one of the original functions.
see http://en.wikipedia.org/wiki/Convolution.
The class provides rows, column and separate convolving operations of a point cloud. Columns and separate convolution is only allowed on organised point clouds.
When convolving, computing the rows and cols elements at 1/2 kernel width distance from the borders is not defined. We allow for 3 policies:
Ignoring: elements at special locations are filled with zero (default behaviour)
Mirroring: the missing rows or columns are obtained through mirroring
Duplicating: the missing rows or columns are obtained through duplicating
Author
Nizar Sallem
Definition at line 77 of file convolution.h.
Member Typedef Documentation
template<typename PointIn, typename PointOut> typedef boost::shared_ptr< const Convolution<PointIn, PointOut> > pcl::filters::Convolution< PointIn, PointOut >::ConstPtr
Definition at line 85 of file convolution.h.
template<typename PointIn, typename PointOut> typedef pcl::PointCloud<PointIn> pcl::filters::Convolution< PointIn, PointOut >::PointCloudIn
Definition at line 80 of file convolution.h.
template<typename PointIn, typename PointOut> typedef PointCloudIn::ConstPtr pcl::filters::Convolution< PointIn, PointOut >::PointCloudInConstPtr
Definition at line 82 of file convolution.h.
template<typename PointIn, typename PointOut> typedef PointCloudIn::Ptr pcl::filters::Convolution< PointIn, PointOut >::PointCloudInPtr
Definition at line 81 of file convolution.h.
template<typename PointIn, typename PointOut> typedef pcl::PointCloud<PointOut> pcl::filters::Convolution< PointIn, PointOut >::PointCloudOut
Definition at line 83 of file convolution.h.
template<typename PointIn, typename PointOut> typedef boost::shared_ptr< Convolution<PointIn, PointOut> > pcl::filters::Convolution< PointIn, PointOut >::Ptr
Definition at line 84 of file convolution.h.
Member Enumeration Documentation
template<typename PointIn, typename PointOut> enum pcl::filters::Convolution::BORDERS_POLICY
The borders policy available.
Enumerator
BORDERS_POLICY_IGNORE
BORDERS_POLICY_MIRROR
BORDERS_POLICY_DUPLICATE
Definition at line 89 of file convolution.h.
Constructor & Destructor Documentation
template<typename PointIn , typename PointOut > pcl::filters::Convolution< PointIn, PointOut >::Convolution ()
Constructor.
Definition at line 47 of file convolution.hpp.
template<typename PointIn, typename PointOut> pcl::filters::Convolution< PointIn, PointOut >::~Convolution () inline
Empty destructor.
Definition at line 98 of file convolution.h.
Member Function Documentation
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve (const Eigen::ArrayXf & h_kernel, const Eigen::ArrayXf & v_kernel, PointCloudOut & output) inline
Convolve point cloud with an horizontal kernel along rows then vertical kernel along columns : convolve separately.
Parameters
[in] h_kernel kernel for convolving rows
[in] v_kernel kernel for convolving columns
[out] output the convolved cloud
Note
if output doesn't fit in input i.e. output.rows () < input.rows () or output.cols () < input.cols () then output is resized to input sizes.
Definition at line 129 of file convolution.hpp.
Referenced by pcl::ColorGradientModality< PointInT >::processInputData().
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve (PointCloudOut & output) inline
Convolve point cloud with same kernel along rows and columns separately.
Parameters
[out] output the convolved cloud
Note
if output doesn't fit in input i.e. output.rows () < input.rows () or output.cols () < input.cols () then output is resized to input sizes.
Definition at line 150 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve_cols (PointCloudOut & output) protected
convolve cols and ignore borders
Definition at line 539 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve_cols_duplicate (PointCloudOut & output) protected
convolve cols and duplicate borders
Definition at line 583 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve_cols_mirror (PointCloudOut & output) protected
convolve cols and mirror borders
Definition at line 628 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve_rows (PointCloudOut & output) protected
convolve rows and ignore borders
Definition at line 405 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve_rows_duplicate (PointCloudOut & output) protected
convolve rows and duplicate borders
Definition at line 449 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolve_rows_mirror (PointCloudOut & output) protected
convolve rows and mirror borders
Definition at line 494 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolveCols (PointCloudOut & output) inline
Convolve a float image columns by a given kernel.
Parameters
[out] output the convolved image
Note
if output doesn't fit in input i.e. output.rows () < input.rows () or output.cols () < input.cols () then output is resized to input sizes.
Definition at line 109 of file convolution.hpp.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::convolveRows (PointCloudOut & output) inline
Convolve a float image rows by a given kernel.
Parameters
[out] output the convolved cloud
Note
if output doesn't fit in input i.e. output.rows () < input.rows () or output.cols () < input.cols () then output is resized to input sizes.
Definition at line 89 of file convolution.hpp.
template<typename PointIn, typename PointOut> int pcl::filters::Convolution< PointIn, PointOut >::getBordersPolicy () inline
Get the borders policy.
Definition at line 115 of file convolution.h.
template<typename PointIn, typename PointOut> const float& pcl::filters::Convolution< PointIn, PointOut >::getDistanceThreshold () const inline
Returns
the distance threshold
Definition at line 127 of file convolution.h.
template<typename PointIn , typename PointOut > void pcl::filters::Convolution< PointIn, PointOut >::initCompute (PointCloudOut & output) protected
init compute is an internal method called before computation
Parameters
[in] output
Exceptions
pcl::InitFailedException
Definition at line 58 of file convolution.hpp.
References pcl::PointCloud< T >::height, pcl::PointCloud< T >::is_dense, pcl::PointCloud< T >::resize(), and pcl::PointCloud< T >::width.
template<typename PointIn, typename PointOut> void pcl::filters::Convolution< PointIn, PointOut >::makeInfinite (PointOut & p) inline protected
Definition at line 229 of file convolution.h.
template<> void pcl::filters::Convolution< pcl::RGB, pcl::RGB >::makeInfinite (pcl::RGB & p) protected
Definition at line 397 of file convolution.hpp.
template<typename PointIn, typename PointOut> void pcl::filters::Convolution< PointIn, PointOut >::setBordersPolicy (int policy) inline
Set the borders policy.
Definition at line 112 of file convolution.h.
template<typename PointIn, typename PointOut> void pcl::filters::Convolution< PointIn, PointOut >::setDistanceThreshold (const float & threshold) inline
Remarks
this is critical so please read it carefully. In 3D the next point in (u,v) coordinate can be really far so a distance threshold is used to keep us from ghost points. The value you set here is strongly related to the sensor. A good value for kinect data is 0.001. Default is std::numeric<float>::infinity ()
Parameters
[in] threshold maximum allowed distance between 2 juxtaposed points
Definition at line 124 of file convolution.h.
template<typename PointIn, typename PointOut> void pcl::filters::Convolution< PointIn, PointOut >::setInputCloud (const PointCloudInConstPtr & cloud) inline
Provide a pointer to the input dataset.
Parameters
cloud the const boost shared pointer to a PointCloud message
Remarks
Will perform a deep copy
Definition at line 104 of file convolution.h.
Referenced by pcl::ColorGradientModality< PointInT >::processInputData().
template<typename PointIn, typename PointOut> void pcl::filters::Convolution< PointIn, PointOut >::setKernel (const Eigen::ArrayXf & kernel) inline
Set convolving kernel.
Parameters
[in] kernel convolving element
Definition at line 109 of file convolution.h.
Referenced by pcl::ColorGradientModality< PointInT >::processInputData().
template<typename PointIn, typename PointOut> void pcl::filters::Convolution< PointIn, PointOut >::setNumberOfThreads (unsigned int nr_threads = 0) inline
Initialize the scheduler and set the number of threads to use.
Parameters
nr_threads the number of hardware threads to use (0 sets the value back to automatic)
Definition at line 132 of file convolution.h.
References pcl::filters::Convolution< PointIn, PointOut >::threads_.
Member Data Documentation
template<typename PointIn, typename PointOut> unsigned int pcl::filters::Convolution< PointIn, PointOut >::threads_ protected
The number of threads the scheduler should use.
Definition at line 226 of file convolution.h.
Referenced by pcl::filters::Convolution< PointIn, PointOut >::setNumberOfThreads().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/convolution.h
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/impl/convolution.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:57