Point Cloud Library (PCL): pcl::DistanceMap Class Reference
pcl::DistanceMap Class Reference
Represents a distance map obtained from a distance transformation.
#include <pcl/recognition/distance_map.h>
Public Member Functions
DistanceMap ()
Constructor.
virtual ~DistanceMap ()
Destructor.
size_t getWidth () const
Returns the width of the map.
size_t getHeight () const
Returns the height of the map.
float * getData ()
Returns a pointer to the beginning of map.
void resize (const size_t width, const size_t height)
Resizes the map to the specified size.
float & operator() (const size_t col_index, const size_t row_index)
Operator to access an element of the map.
const float & operator() (const size_t col_index, const size_t row_index) const
Operator to access an element of the map.
Protected Attributes
std::vector< float > data_
The storage for the distance map data.
size_t width_
The width of the map.
size_t height_
The height of the map.
Detailed Description
Represents a distance map obtained from a distance transformation.
Author
Stefan Holzer
Definition at line 47 of file distance_map.h.
Constructor & Destructor Documentation
pcl::DistanceMap::DistanceMap () inline
Constructor.
Definition at line 51 of file distance_map.h.
virtual pcl::DistanceMap::~DistanceMap () inline virtual
Destructor.
Definition at line 53 of file distance_map.h.
Member Function Documentation
float* pcl::DistanceMap::getData () inline
Returns a pointer to the beginning of map.
Definition at line 71 of file distance_map.h.
References data_.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), and pcl::SurfaceNormalModality< PointInT >::computeDistanceMap().
size_t pcl::DistanceMap::getHeight () const inline
Returns the height of the map.
Definition at line 64 of file distance_map.h.
References height_.
size_t pcl::DistanceMap::getWidth () const inline
Returns the width of the map.
Definition at line 57 of file distance_map.h.
References width_.
float& pcl::DistanceMap::operator() (const size_t col_index, const size_t row_index) inline
Operator to access an element of the map.
Parameters
[in] col_index the column index of the element to access.
[in] row_index the row index of the element to access.
Definition at line 93 of file distance_map.h.
References data_, and width_.
const float& pcl::DistanceMap::operator() (const size_t col_index, const size_t row_index) const inline
Operator to access an element of the map.
Parameters
[in] col_index the column index of the element to access.
[in] row_index the row index of the element to access.
Definition at line 103 of file distance_map.h.
References data_, and width_.
void pcl::DistanceMap::resize (const size_t width, const size_t height) inline
Resizes the map to the specified size.
Parameters
[in] width the new width of the map.
[in] height the new height of the map.
Definition at line 81 of file distance_map.h.
References data_, height_, and width_.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), and pcl::SurfaceNormalModality< PointInT >::computeDistanceMap().
Member Data Documentation
std::vector<float> pcl::DistanceMap::data_ protected
The storage for the distance map data.
Definition at line 110 of file distance_map.h.
Referenced by getData(), operator()(), and resize().
size_t pcl::DistanceMap::height_ protected
The height of the map.
Definition at line 114 of file distance_map.h.
Referenced by getHeight(), and resize().
size_t pcl::DistanceMap::width_ protected
The width of the map.
Definition at line 112 of file distance_map.h.
Referenced by getWidth(), operator()(), and resize().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/recognition/include/pcl/recognition/distance_map.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:35