Point Cloud Library (PCL): pcl::octree::OctreeBranchNode< ContainerT > Class Template Reference
pcl::octree::OctreeBranchNode< ContainerT > Class Template Reference
Abstract octree branch class
#include <pcl/octree/octree_nodes.h>
Public Member Functions
OctreeBranchNode ()
Empty constructor.
OctreeBranchNode (const OctreeBranchNode &source)
Empty constructor.
OctreeBranchNode & operator= (const OctreeBranchNode &source)
Copy operator.
virtual OctreeBranchNode * deepCopy () const
Octree deep copy method.
virtual ~OctreeBranchNode ()
Empty deconstructor.
OctreeNode *& operator[] (unsigned char child_idx_arg)
Access operator.
OctreeNode * getChildPtr (unsigned char child_idx_arg) const
Get pointer to child.
void setChildPtr (OctreeNode *child, unsigned char index)
Get pointer to child.
bool hasChild (unsigned char child_idx_arg) const
Check if branch is pointing to a particular child node.
virtual node_type_t getNodeType () const
Check if branch can be pruned.
void reset ()
const ContainerT * operator-> () const
Get const pointer to container.
ContainerT * operator-> ()
Get pointer to container.
const ContainerT & operator* () const
Get const reference to container.
ContainerT & operator* ()
Get reference to container.
const ContainerT & getContainer () const
Get const reference to container.
ContainerT & getContainer ()
Get reference to container.
const ContainerT * getContainerPtr () const
Get const pointer to container.
ContainerT * getContainerPtr ()
Get pointer to container.
Public Member Functions inherited from pcl::octree::OctreeNode
OctreeNode ()
virtual ~OctreeNode ()
Protected Attributes
OctreeNode * child_node_array_ [8]
ContainerT container_
Detailed Description
template<typename ContainerT>
class pcl::octree::OctreeBranchNode< ContainerT >
Abstract octree branch class
Note
Octree branch classes may collect data of type DataT
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 204 of file octree_nodes.h.
Constructor & Destructor Documentation
template<typename ContainerT > pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode () inline
Empty constructor.
Definition at line 209 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
template<typename ContainerT > pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode (const OctreeBranchNode< ContainerT > & source) inline
Empty constructor.
Definition at line 217 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeNode::deepCopy().
template<typename ContainerT > virtual pcl::octree::OctreeBranchNode< ContainerT >::~OctreeBranchNode () inline virtual
Empty deconstructor.
Definition at line 252 of file octree_nodes.h.
Member Function Documentation
template<typename ContainerT > virtual OctreeBranchNode* pcl::octree::OctreeBranchNode< ContainerT >::deepCopy () const inline virtual
Octree deep copy method.
Implements pcl::octree::OctreeNode.
Definition at line 245 of file octree_nodes.h.
template<typename ContainerT > OctreeNode* pcl::octree::OctreeBranchNode< ContainerT >::getChildPtr (unsigned char child_idx_arg) const inline
Get pointer to child.
Parameters
child_idx_arg index to child node
Returns
OctreeNode pointer
Definition at line 272 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::branchHasChild(), pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::getBranchBitPattern(), pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::getBranchChildPtr(), pcl::octree::OctreePointCloudVoxelCentroid< PointT, LeafContainerT, BranchContainerT >::getVoxelCentroidsRecursive(), and pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::serializeTreeRecursive().
template<typename ContainerT > const ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::getContainer () const inline
Get const reference to container.
Definition at line 366 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::getContainer () inline
Get reference to container.
Definition at line 373 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > const ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::getContainerPtr () const inline
Get const pointer to container.
Definition at line 380 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::getContainerPtr () inline
Get pointer to container.
Definition at line 387 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > virtual node_type_t pcl::octree::OctreeBranchNode< ContainerT >::getNodeType () const inline virtual
Check if branch can be pruned.
Note
if all children are leaf nodes AND contain identical containers, branch can be pruned
Returns
"true" if branch can be pruned; "false" otherwiseGet the type of octree node. Returns LEAVE_NODE type
Implements pcl::octree::OctreeNode.
Definition at line 323 of file octree_nodes.h.
References pcl::octree::BRANCH_NODE.
template<typename ContainerT > bool pcl::octree::OctreeBranchNode< ContainerT >::hasChild (unsigned char child_idx_arg) const inline
Check if branch is pointing to a particular child node.
Parameters
child_idx_arg index to child node
Returns
"true" if pointer to child node exists; "false" otherwise
Definition at line 292 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::deleteLeafRecursive(), pcl::octree::OctreePointCloudVoxelCentroid< PointT, LeafContainerT, BranchContainerT >::getVoxelCentroidsRecursive(), and pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >::serializeTreeRecursive().
template<typename ContainerT > const ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::operator* () const inline
Get const reference to container.
Definition at line 352 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT& pcl::octree::OctreeBranchNode< ContainerT >::operator* () inline
Get reference to container.
Definition at line 359 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > const ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::operator-> () const inline
Get const pointer to container.
Definition at line 338 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT* pcl::octree::OctreeBranchNode< ContainerT >::operator-> () inline
Get pointer to container.
Definition at line 345 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > OctreeBranchNode& pcl::octree::OctreeBranchNode< ContainerT >::operator= (const OctreeBranchNode< ContainerT > & source) inline
Copy operator.
Definition at line 231 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeNode::deepCopy().
template<typename ContainerT > OctreeNode*& pcl::octree::OctreeBranchNode< ContainerT >::operator[] (unsigned char child_idx_arg) inline
Access operator.
Parameters
child_idx_arg index to child node
Returns
OctreeNode pointer
Definition at line 261 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
template<typename ContainerT > void pcl::octree::OctreeBranchNode< ContainerT >::reset () inline
Definition at line 329 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeBranchNode< ContainerT >::container_.
template<typename ContainerT > void pcl::octree::OctreeBranchNode< ContainerT >::setChildPtr (OctreeNode * child, unsigned char index) inline
Get pointer to child.
Returns
OctreeNode pointer
Definition at line 281 of file octree_nodes.h.
References pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_.
Member Data Documentation
template<typename ContainerT > OctreeNode* pcl::octree::OctreeBranchNode< ContainerT >::child_node_array_[8] protected
Definition at line 393 of file octree_nodes.h.
Referenced by pcl::octree::OctreeBranchNode< ContainerT >::getChildPtr(), pcl::octree::OctreeBranchNode< ContainerT >::hasChild(), pcl::octree::OctreeBranchNode< ContainerT >::OctreeBranchNode(), pcl::octree::OctreeBranchNode< ContainerT >::operator=(), pcl::octree::OctreeBranchNode< ContainerT >::operator[](), pcl::octree::OctreeBranchNode< ContainerT >::reset(), and pcl::octree::OctreeBranchNode< ContainerT >::setChildPtr().
template<typename ContainerT > ContainerT pcl::octree::OctreeBranchNode< ContainerT >::container_ protected
Definition at line 395 of file octree_nodes.h.
Referenced by pcl::octree::OctreeBranchNode< ContainerT >::getContainer(), pcl::octree::OctreeBranchNode< ContainerT >::getContainerPtr(), pcl::octree::OctreeBranchNode< ContainerT >::operator*(), pcl::octree::OctreeBranchNode< ContainerT >::operator->(), and pcl::octree::OctreeBranchNode< ContainerT >::reset().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/octree/include/pcl/octree/octree_nodes.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:11