Point Cloud Library (PCL): pcl::registration::CorrespondenceRejectorSurfaceNormal Class Reference
pcl::registration::CorrespondenceRejectorSurfaceNormal Class Reference
Module registration
CorrespondenceRejectorSurfaceNormal implements a simple correspondence rejection method based on the angle between the normals at correspondent points.
#include <pcl/registration/correspondence_rejection_surface_normal.h>
Public Types
typedef boost::shared_ptr
< CorrespondenceRejectorSurfaceNormal > Ptr
typedef boost::shared_ptr
< const
CorrespondenceRejectorSurfaceNormal > ConstPtr
Public Types inherited from pcl::registration::CorrespondenceRejector
typedef boost::shared_ptr
< CorrespondenceRejector > Ptr
typedef boost::shared_ptr
< const CorrespondenceRejector > ConstPtr
Public Member Functions
CorrespondenceRejectorSurfaceNormal ()
Empty constructor.
void getRemainingCorrespondences (const pcl::Correspondences &original_correspondences, pcl::Correspondences &remaining_correspondences)
Get a list of valid correspondences after rejection from the original set of correspondences.
void setThreshold (double threshold)
Set the thresholding angle between the normals for correspondence rejection.
double getThreshold () const
Get the thresholding angle between the normals for correspondence rejection.
template<typename PointT , typename NormalT >
void initializeDataContainer ()
Initialize the data container object for the point type and the normal type.
template<typename PointT >
void setInputCloud (const typename pcl::PointCloud< PointT >::ConstPtr &input)
Provide a source point cloud dataset (must contain XYZ data!), used to compute the correspondence distance.
template<typename PointT >
void setInputSource (const typename pcl::PointCloud< PointT >::ConstPtr &input)
Provide a source point cloud dataset (must contain XYZ data!), used to compute the correspondence distance.
template<typename PointT >
pcl::PointCloud< PointT >::ConstPtr getInputSource () const
Get the target input point cloud.
template<typename PointT >
void setInputTarget (const typename pcl::PointCloud< PointT >::ConstPtr &target)
Provide a target point cloud dataset (must contain XYZ data!), used to compute the correspondence distance.
template<typename PointT >
void setSearchMethodTarget (const boost::shared_ptr< pcl::search::KdTree< PointT > > &tree, bool force_no_recompute=false)
Provide a pointer to the search object used to find correspondences in the target cloud.
template<typename PointT >
pcl::PointCloud< PointT >::ConstPtr getInputTarget () const
Get the target input point cloud.
template<typename PointT , typename NormalT >
void setInputNormals (const typename pcl::PointCloud< NormalT >::ConstPtr &normals)
Set the normals computed on the input point cloud.
template<typename NormalT >
pcl::PointCloud< NormalT >::Ptr getInputNormals () const
Get the normals computed on the input point cloud.
template<typename PointT , typename NormalT >
void setTargetNormals (const typename pcl::PointCloud< NormalT >::ConstPtr &normals)
Set the normals computed on the target point cloud.
template<typename NormalT >
pcl::PointCloud< NormalT >::Ptr getTargetNormals () const
Get the normals computed on the target point cloud.
bool requiresSourcePoints () const
See if this rejector requires source points.
void setSourcePoints (pcl::PCLPointCloud2::ConstPtr cloud2)
Blob method for setting the source cloud.
bool requiresTargetPoints () const
See if this rejector requires a target cloud.
void setTargetPoints (pcl::PCLPointCloud2::ConstPtr cloud2)
Method for setting the target cloud.
bool requiresSourceNormals () const
See if this rejector requires source normals.
void setSourceNormals (pcl::PCLPointCloud2::ConstPtr cloud2)
Blob method for setting the source normals.
bool requiresTargetNormals () const
See if this rejector requires target normals.
void setTargetNormals (pcl::PCLPointCloud2::ConstPtr cloud2)
Method for setting the target normals.
Public Member Functions inherited from pcl::registration::CorrespondenceRejector
CorrespondenceRejector ()
Empty constructor.
virtual ~CorrespondenceRejector ()
Empty destructor.
virtual void setInputCorrespondences (const CorrespondencesConstPtr &correspondences)
Provide a pointer to the vector of the input correspondences.
CorrespondencesConstPtr getInputCorrespondences ()
Get a pointer to the vector of the input correspondences.
void getCorrespondences (pcl::Correspondences &correspondences)
Run correspondence rejection.
void getRejectedQueryIndices (const pcl::Correspondences &correspondences, std::vector< int > &indices)
Determine the indices of query points of correspondences that have been rejected, i.e., the difference between the input correspondences (set via setInputCorrespondences) and the given correspondence vector.
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Types
typedef boost::shared_ptr
< DataContainerInterface > DataContainerPtr
Protected Member Functions
void applyRejection (pcl::Correspondences &correspondences)
Apply the rejection algorithm.
Protected Attributes
double threshold_
The median distance threshold between two correspondent points in source <-> target.
DataContainerPtr data_container_
A pointer to the DataContainer object containing the input and target point clouds.
Protected Attributes inherited from pcl::registration::CorrespondenceRejector
std::string rejection_name_
The name of the rejection method.
CorrespondencesConstPtr input_correspondences_
The input correspondences.
Detailed Description
CorrespondenceRejectorSurfaceNormal implements a simple correspondence rejection method based on the angle between the normals at correspondent points.
Note
If setInputCloud and setInputTarget are given, then the distances between correspondences will be estimated using the given XYZ data, and not read from the set of input correspondences.
Author
Aravindhan K Krishnan (original code from libpointmatcher: https://github.com/ethz-asl/libpointmatcher)
Definition at line 60 of file correspondence_rejection_surface_normal.h.
Member Typedef Documentation
typedef boost::shared_ptr<const CorrespondenceRejectorSurfaceNormal> pcl::registration::CorrespondenceRejectorSurfaceNormal::ConstPtr
Definition at line 68 of file correspondence_rejection_surface_normal.h.
typedef boost::shared_ptr<DataContainerInterface> pcl::registration::CorrespondenceRejectorSurfaceNormal::DataContainerPtr protected
Definition at line 316 of file correspondence_rejection_surface_normal.h.
typedef boost::shared_ptr<CorrespondenceRejectorSurfaceNormal> pcl::registration::CorrespondenceRejectorSurfaceNormal::Ptr
Definition at line 67 of file correspondence_rejection_surface_normal.h.
Constructor & Destructor Documentation
pcl::registration::CorrespondenceRejectorSurfaceNormal::CorrespondenceRejectorSurfaceNormal () inline
Empty constructor.
Sets the threshold to 1.0.
Definition at line 71 of file correspondence_rejection_surface_normal.h.
Member Function Documentation
void pcl::registration::CorrespondenceRejectorSurfaceNormal::applyRejection (pcl::Correspondences & correspondences) inline protected virtual
Apply the rejection algorithm.
Parameters
[out] correspondences the set of resultant correspondences.
Implements pcl::registration::CorrespondenceRejector.
Definition at line 308 of file correspondence_rejection_surface_normal.h.
template<typename NormalT > pcl::PointCloud<NormalT>::Ptr pcl::registration::CorrespondenceRejectorSurfaceNormal::getInputNormals () const inline
Get the normals computed on the input point cloud.
Definition at line 201 of file correspondence_rejection_surface_normal.h.
template<typename PointT > pcl::PointCloud<PointT>::ConstPtr pcl::registration::CorrespondenceRejectorSurfaceNormal::getInputSource () const inline
Get the target input point cloud.
Definition at line 134 of file correspondence_rejection_surface_normal.h.
template<typename PointT > pcl::PointCloud<PointT>::ConstPtr pcl::registration::CorrespondenceRejectorSurfaceNormal::getInputTarget () const inline
Get the target input point cloud.
Definition at line 175 of file correspondence_rejection_surface_normal.h.
void pcl::registration::CorrespondenceRejectorSurfaceNormal::getRemainingCorrespondences (const pcl::Correspondences & original_correspondences, pcl::Correspondences & remaining_correspondences) virtual
Get a list of valid correspondences after rejection from the original set of correspondences.
Parameters
[in] original_correspondences the set of initial correspondences given
[out] remaining_correspondences the resultant filtered set of remaining correspondences
Implements pcl::registration::CorrespondenceRejector.
template<typename NormalT > pcl::PointCloud<NormalT>::Ptr pcl::registration::CorrespondenceRejectorSurfaceNormal::getTargetNormals () const inline
Get the normals computed on the target point cloud.
Definition at line 227 of file correspondence_rejection_surface_normal.h.
double pcl::registration::CorrespondenceRejectorSurfaceNormal::getThreshold () const inline
Get the thresholding angle between the normals for correspondence rejection.
Definition at line 94 of file correspondence_rejection_surface_normal.h.
template<typename PointT , typename NormalT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::initializeDataContainer () inline
Initialize the data container object for the point type and the normal type.
Definition at line 98 of file correspondence_rejection_surface_normal.h.
bool pcl::registration::CorrespondenceRejectorSurfaceNormal::requiresSourceNormals () const inline virtual
See if this rejector requires source normals.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 272 of file correspondence_rejection_surface_normal.h.
bool pcl::registration::CorrespondenceRejectorSurfaceNormal::requiresSourcePoints () const inline virtual
See if this rejector requires source points.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 240 of file correspondence_rejection_surface_normal.h.
bool pcl::registration::CorrespondenceRejectorSurfaceNormal::requiresTargetNormals () const inline virtual
See if this rejector requires target normals.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 288 of file correspondence_rejection_surface_normal.h.
bool pcl::registration::CorrespondenceRejectorSurfaceNormal::requiresTargetPoints () const inline virtual
See if this rejector requires a target cloud.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 256 of file correspondence_rejection_surface_normal.h.
template<typename PointT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::setInputCloud (const typename pcl::PointCloud< PointT >::ConstPtr & input) inline
Provide a source point cloud dataset (must contain XYZ data!), used to compute the correspondence distance.
Parameters
[in] input a cloud containing XYZ data
Definition at line 107 of file correspondence_rejection_surface_normal.h.
template<typename PointT , typename NormalT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::setInputNormals (const typename pcl::PointCloud< NormalT >::ConstPtr & normals) inline
Set the normals computed on the input point cloud.
Parameters
[in] normals the normals computed for the input cloud
Definition at line 189 of file correspondence_rejection_surface_normal.h.
template<typename PointT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::setInputSource (const typename pcl::PointCloud< PointT >::ConstPtr & input) inline
Provide a source point cloud dataset (must contain XYZ data!), used to compute the correspondence distance.
Parameters
[in] input a cloud containing XYZ data
Definition at line 122 of file correspondence_rejection_surface_normal.h.
template<typename PointT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::setInputTarget (const typename pcl::PointCloud< PointT >::ConstPtr & target) inline
Provide a target point cloud dataset (must contain XYZ data!), used to compute the correspondence distance.
Parameters
[in] target a cloud containing XYZ data
Definition at line 148 of file correspondence_rejection_surface_normal.h.
template<typename PointT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::setSearchMethodTarget (const boost::shared_ptr< pcl::search::KdTree< PointT > > & tree, bool force_no_recompute = false) inline
Provide a pointer to the search object used to find correspondences in the target cloud.
Parameters
[in] tree a pointer to the spatial search object.
[in] force_no_recompute If set to true, this tree will NEVER be recomputed, regardless of calls to setInputTarget. Only use if you are confident that the tree will be set correctly.
Definition at line 166 of file correspondence_rejection_surface_normal.h.
void pcl::registration::CorrespondenceRejectorSurfaceNormal::setSourceNormals (pcl::PCLPointCloud2::ConstPtr cloud2) inline virtual
Blob method for setting the source normals.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 277 of file correspondence_rejection_surface_normal.h.
References pcl::fromPCLPointCloud2().
void pcl::registration::CorrespondenceRejectorSurfaceNormal::setSourcePoints (pcl::PCLPointCloud2::ConstPtr cloud2) inline virtual
Blob method for setting the source cloud.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 245 of file correspondence_rejection_surface_normal.h.
References pcl::fromPCLPointCloud2().
template<typename PointT , typename NormalT > void pcl::registration::CorrespondenceRejectorSurfaceNormal::setTargetNormals (const typename pcl::PointCloud< NormalT >::ConstPtr & normals) inline
Set the normals computed on the target point cloud.
Parameters
[in] normals the normals computed for the input cloud
Definition at line 215 of file correspondence_rejection_surface_normal.h.
void pcl::registration::CorrespondenceRejectorSurfaceNormal::setTargetNormals (pcl::PCLPointCloud2::ConstPtr cloud2) inline virtual
Method for setting the target normals.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 293 of file correspondence_rejection_surface_normal.h.
References pcl::fromPCLPointCloud2().
void pcl::registration::CorrespondenceRejectorSurfaceNormal::setTargetPoints (pcl::PCLPointCloud2::ConstPtr cloud2) inline virtual
Method for setting the target cloud.
Reimplemented from pcl::registration::CorrespondenceRejector.
Definition at line 261 of file correspondence_rejection_surface_normal.h.
References pcl::fromPCLPointCloud2().
void pcl::registration::CorrespondenceRejectorSurfaceNormal::setThreshold (double threshold) inline
Set the thresholding angle between the normals for correspondence rejection.
Parameters
[in] threshold cosine of the thresholding angle between the normals for rejection
Definition at line 90 of file correspondence_rejection_surface_normal.h.
Member Data Documentation
DataContainerPtr pcl::registration::CorrespondenceRejectorSurfaceNormal::data_container_ protected
A pointer to the DataContainer object containing the input and target point clouds.
Definition at line 318 of file correspondence_rejection_surface_normal.h.
double pcl::registration::CorrespondenceRejectorSurfaceNormal::threshold_ protected
The median distance threshold between two correspondent points in source <-> target.
Definition at line 314 of file correspondence_rejection_surface_normal.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/registration/include/pcl/registration/correspondence_rejection_surface_normal.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:20