Point Cloud Library (PCL): pcl::cuda::ScopeTimeGPU Class Reference
pcl::cuda::ScopeTimeGPU Class Reference
Class to measure the time spent in a scope.
#include </home/travis/build/PointCloudLibrary/pcl/cuda/common/include/pcl/cuda/time_gpu.h>
Public Member Functions
ScopeTimeGPU (const char *title)
Constructor.
~ScopeTimeGPU ()
Destructor.
void start ()
Start the timer.
void stop ()
Stop the timer.
void stop_print ()
Stop and print the timer.
Detailed Description
Class to measure the time spent in a scope.
To use this class, e.g. to measure the time spent in a function, just create an instance at the beginning of the function.
Definition at line 54 of file time_gpu.h.
Constructor & Destructor Documentation
pcl::cuda::ScopeTimeGPU::ScopeTimeGPU (const char * title) inline
Constructor.
Definition at line 58 of file time_gpu.h.
References start().
pcl::cuda::ScopeTimeGPU::~ScopeTimeGPU () inline
Destructor.
Definition at line 64 of file time_gpu.h.
References stop().
Member Function Documentation
void pcl::cuda::ScopeTimeGPU::start () inline
Start the timer.
Definition at line 72 of file time_gpu.h.
Referenced by ScopeTimeGPU().
void pcl::cuda::ScopeTimeGPU::stop () inline
Stop the timer.
Definition at line 83 of file time_gpu.h.
Referenced by stop_print(), and ~ScopeTimeGPU().
void pcl::cuda::ScopeTimeGPU::stop_print () inline
Stop and print the timer.
Definition at line 97 of file time_gpu.h.
References stop().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/cuda/common/include/pcl/cuda/time_gpu.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:54