Point Cloud Library (PCL): pcl::SampleConsensusModelPlane< PointT > Class Template Reference
pcl::SampleConsensusModelPlane< PointT > Class Template Reference
Module sample_consensus
SampleConsensusModelPlane defines a model for 3D plane segmentation.
#include <pcl/sample_consensus/sac_model_plane.h>
Public Types
typedef SampleConsensusModel
< PointT >::PointCloud PointCloud
typedef SampleConsensusModel
< PointT >::PointCloudPtr PointCloudPtr
typedef SampleConsensusModel
< PointT >::PointCloudConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< SampleConsensusModelPlane > Ptr
Public Types inherited from pcl::SampleConsensusModel< PointT >
typedef pcl::PointCloud< PointT > PointCloud
typedef pcl::PointCloud
< PointT >::ConstPtr PointCloudConstPtr
typedef pcl::PointCloud
< PointT >::Ptr PointCloudPtr
typedef pcl::search::Search
< PointT >::Ptr SearchPtr
typedef boost::shared_ptr
< SampleConsensusModel > Ptr
typedef boost::shared_ptr
< const SampleConsensusModel > ConstPtr
Public Member Functions
SampleConsensusModelPlane (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModelPlane.
SampleConsensusModelPlane (const PointCloudConstPtr &cloud, const std::vector< int > &indices, bool random=false)
Constructor for base SampleConsensusModelPlane.
virtual ~SampleConsensusModelPlane ()
Empty destructor.
bool computeModelCoefficients (const std::vector< int > &samples, Eigen::VectorXf &model_coefficients) const
Check whether the given index samples can form a valid plane model, compute the model coefficients from these samples and store them internally in model_coefficients_.
void getDistancesToModel (const Eigen::VectorXf &model_coefficients, std::vector< double > &distances) const
Compute all distances from the cloud data to a given plane model.
void selectWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold, std::vector< int > &inliers)
Select all the points which respect the given model coefficients as inliers.
virtual int countWithinDistance (const Eigen::VectorXf &model_coefficients, const double threshold) const
Count all the points which respect the given model coefficients as inliers.
void optimizeModelCoefficients (const std::vector< int > &inliers, const Eigen::VectorXf &model_coefficients, Eigen::VectorXf &optimized_coefficients) const
Recompute the plane coefficients using the given inlier set and return them to the user.
void projectPoints (const std::vector< int > &inliers, const Eigen::VectorXf &model_coefficients, PointCloud &projected_points, bool copy_data_fields=true) const
Create a new point cloud with inliers projected onto the plane model.
bool doSamplesVerifyModel (const std::set< int > &indices, const Eigen::VectorXf &model_coefficients, const double threshold) const
Verify whether a subset of indices verifies the given plane model coefficients.
pcl::SacModel getModelType () const
Return an unique id for this model (SACMODEL_PLANE).
Public Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (const PointCloudConstPtr &cloud, bool random=false)
Constructor for base SampleConsensusModel.
SampleConsensusModel (const PointCloudConstPtr &cloud, const std::vector< int > &indices, bool random=false)
Constructor for base SampleConsensusModel.
virtual ~SampleConsensusModel ()
Destructor for base SampleConsensusModel.
virtual void getSamples (int &iterations, std::vector< int > &samples)
Get a set of random data samples and return them as point indices.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const boost::shared_ptr< std::vector< int > > &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const std::vector< int > &indices)
Provide the vector of indices that represents the input data.
boost::shared_ptr< std::vector
< int > > getIndices () const
Get a pointer to the vector of indices used.
const std::string & getClassName () const
Get a string representation of the name of this class.
unsigned int getSampleSize () const
Return the size of a sample from which the model is computed.
unsigned int getModelSize () const
Return the number of coefficients in the model.
void setRadiusLimits (const double &min_radius, const double &max_radius)
Set the minimum and maximum allowable radius limits for the model (applicable to models that estimate a radius)
void getRadiusLimits (double &min_radius, double &max_radius) const
Get the minimum and maximum allowable radius limits for the model as set by the user.
void setSamplesMaxDist (const double &radius, SearchPtr search)
Set the maximum distance allowed when drawing random samples.
void getSamplesMaxDist (double &radius) const
Get maximum distance allowed when drawing random samples.
double computeVariance (const std::vector< double > &error_sqr_dists) const
Compute the variance of the errors to the model.
double computeVariance () const
Compute the variance of the errors to the model from the internally estimated vector of distances.
Additional Inherited Members
Protected Member Functions inherited from pcl::SampleConsensusModel< PointT >
SampleConsensusModel (bool random=false)
Empty constructor for base SampleConsensusModel.
void drawIndexSample (std::vector< int > &sample)
Fills a sample array with random samples from the indices_ vector.
void drawIndexSampleRadius (std::vector< int > &sample)
Fills a sample array with one random sample from the indices_ vector and other random samples that are closer than samples_radius_.
virtual bool isModelValid (const Eigen::VectorXf &model_coefficients) const
Check whether a model is valid given the user constraints.
int rnd ()
Boost-based random number generator.
Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
std::string model_name_
The model name.
PointCloudConstPtr input_
A boost shared pointer to the point cloud data array.
boost::shared_ptr< std::vector
< int > > indices_
A pointer to the vector of point indices to use.
double radius_min_
The minimum and maximum radius limits for the model.
double radius_max_
double samples_radius_
The maximum distance of subsequent samples from the first (radius search)
SearchPtr samples_radius_search_
The search object for picking subsequent samples using radius search.
std::vector< int > shuffled_indices_
Data containing a shuffled version of the indices.
boost::mt19937 rng_alg_
Boost-based random number generator algorithm.
boost::shared_ptr
< boost::uniform_int<> > rng_dist_
Boost-based random number generator distribution.
boost::shared_ptr
< boost::variate_generator
< boost::mt19937
&, boost::uniform_int<> > > rng_gen_
Boost-based random number generator.
std::vector< double > error_sqr_dists_
A vector holding the distances to the computed model.
unsigned int sample_size_
The size of a sample from which the model is computed.
unsigned int model_size_
The number of coefficients in the model.
Static Protected Attributes inherited from pcl::SampleConsensusModel< PointT >
static const unsigned int max_sample_checks_ = 1000
The maximum number of samples to try until we get a good one.
Detailed Description
template<typename PointT>
class pcl::SampleConsensusModelPlane< PointT >
SampleConsensusModelPlane defines a model for 3D plane segmentation.
The model coefficients are defined as:
a : the X coordinate of the plane's normal (normalized)
b : the Y coordinate of the plane's normal (normalized)
c : the Z coordinate of the plane's normal (normalized)
d : the fourth Hessian component of the plane's equation
Author
Radu B. Rusu
Definition at line 136 of file sac_model_plane.h.
Member Typedef Documentation
template<typename PointT> typedef SampleConsensusModel<PointT>::PointCloud pcl::SampleConsensusModelPlane< PointT >::PointCloud
Definition at line 145 of file sac_model_plane.h.
template<typename PointT> typedef SampleConsensusModel<PointT>::PointCloudConstPtr pcl::SampleConsensusModelPlane< PointT >::PointCloudConstPtr
Definition at line 147 of file sac_model_plane.h.
template<typename PointT> typedef SampleConsensusModel<PointT>::PointCloudPtr pcl::SampleConsensusModelPlane< PointT >::PointCloudPtr
Definition at line 146 of file sac_model_plane.h.
template<typename PointT> typedef boost::shared_ptr<SampleConsensusModelPlane> pcl::SampleConsensusModelPlane< PointT >::Ptr
Definition at line 149 of file sac_model_plane.h.
Constructor & Destructor Documentation
template<typename PointT> pcl::SampleConsensusModelPlane< PointT >::SampleConsensusModelPlane (const PointCloudConstPtr & cloud, bool random = false) inline
Constructor for base SampleConsensusModelPlane.
Parameters
[in] cloud the input point cloud dataset
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 155 of file sac_model_plane.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
template<typename PointT> pcl::SampleConsensusModelPlane< PointT >::SampleConsensusModelPlane (const PointCloudConstPtr & cloud, const std::vector< int > & indices, bool random = false) inline
Constructor for base SampleConsensusModelPlane.
Parameters
[in] cloud the input point cloud dataset
[in] indices a vector of point indices to be used from cloud
[in] random if true set the random seed to the current time, else set to 12345 (default: false)
Definition at line 168 of file sac_model_plane.h.
References pcl::SampleConsensusModel< PointT >::model_name_, pcl::SampleConsensusModel< PointT >::model_size_, and pcl::SampleConsensusModel< PointT >::sample_size_.
template<typename PointT> virtual pcl::SampleConsensusModelPlane< PointT >::~SampleConsensusModelPlane () inline virtual
Empty destructor.
Definition at line 179 of file sac_model_plane.h.
Member Function Documentation
template<typename PointT > bool pcl::SampleConsensusModelPlane< PointT >::computeModelCoefficients (const std::vector< int > & samples, Eigen::VectorXf & model_coefficients) const virtual
Check whether the given index samples can form a valid plane model, compute the model coefficients from these samples and store them internally in model_coefficients_.
The plane coefficients are: a, b, c, d (ax+by+cz+d=0)
Parameters
[in] samples the point indices found as possible good candidates for creating a valid model
[out] model_coefficients the resultant model coefficients
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 69 of file sac_model_plane.hpp.
Referenced by pcl::registration::FPCSInitialAlignment< PointSource, PointTarget, NormalT, Scalar >::selectBase().
template<typename PointT > int pcl::SampleConsensusModelPlane< PointT >::countWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold) const virtual
Count all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a model that we need to compute distances to
[in] threshold maximum admissible distance threshold for determining the inliers from the outliers
Returns
the resultant number of inliers
Implements pcl::SampleConsensusModel< PointT >.
Reimplemented in pcl::SampleConsensusModelPerpendicularPlane< PointT >, pcl::SampleConsensusModelParallelPlane< PointT >, and pcl::SampleConsensusModelNormalPlane< PointT, PointNT >.
Definition at line 183 of file sac_model_plane.hpp.
template<typename PointT > bool pcl::SampleConsensusModelPlane< PointT >::doSamplesVerifyModel (const std::set< int > & indices, const Eigen::VectorXf & model_coefficients, const double threshold) const virtual
Verify whether a subset of indices verifies the given plane model coefficients.
Parameters
[in] indices the data indices that need to be tested against the plane model
[in] model_coefficients the plane model coefficients
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 345 of file sac_model_plane.hpp.
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::getDistancesToModel (const Eigen::VectorXf & model_coefficients, std::vector< double > & distances) const virtual
Compute all distances from the cloud data to a given plane model.
Parameters
[in] model_coefficients the coefficients of a plane model that we need to compute distances to
[out] distances the resultant estimated distances
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 112 of file sac_model_plane.hpp.
template<typename PointT> pcl::SacModel pcl::SampleConsensusModelPlane< PointT >::getModelType () const inline virtual
Return an unique id for this model (SACMODEL_PLANE).
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 254 of file sac_model_plane.h.
References pcl::SACMODEL_PLANE.
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::optimizeModelCoefficients (const std::vector< int > & inliers, const Eigen::VectorXf & model_coefficients, Eigen::VectorXf & optimized_coefficients) const virtual
Recompute the plane coefficients using the given inlier set and return them to the user.
Note
: these are the coefficients of the plane model after refinement (e.g. after SVD)
Parameters
[in] inliers the data inliers found as supporting the model
[in] model_coefficients the initial guess for the model coefficients
[out] optimized_coefficients the resultant recomputed coefficients after non-linear optimization
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 212 of file sac_model_plane.hpp.
References pcl::computeMeanAndCovarianceMatrix(), pcl::eigen33(), and pcl::EIGEN_ALIGN16.
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::projectPoints (const std::vector< int > & inliers, const Eigen::VectorXf & model_coefficients, PointCloud & projected_points, bool copy_data_fields = true) const virtual
Create a new point cloud with inliers projected onto the plane model.
Parameters
[in] inliers the data inliers that we want to project on the plane model
[in] model_coefficients the normalized coefficients of a plane model
[out] projected_points the resultant projected points
[in] copy_data_fields set to true if we need to copy the other data fields
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 261 of file sac_model_plane.hpp.
References pcl::PointCloud< T >::header, pcl::PointCloud< T >::height, pcl::PointCloud< T >::is_dense, pcl::PointCloud< T >::points, and pcl::PointCloud< T >::width.
Referenced by pcl::ExtractPolygonalPrismData< PointT >::segment().
template<typename PointT > void pcl::SampleConsensusModelPlane< PointT >::selectWithinDistance (const Eigen::VectorXf & model_coefficients, const double threshold, std::vector< int > & inliers) virtual
Select all the points which respect the given model coefficients as inliers.
Parameters
[in] model_coefficients the coefficients of a plane model that we need to compute distances to
[in] threshold a maximum admissible distance threshold for determining the inliers from the outliers
[out] inliers the resultant model inliers
Implements pcl::SampleConsensusModel< PointT >.
Definition at line 143 of file sac_model_plane.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/sample_consensus/include/pcl/sample_consensus/sac_model_plane.h
/home/travis/build/PointCloudLibrary/pcl/sample_consensus/include/pcl/sample_consensus/impl/sac_model_plane.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:44