Point Cloud Library (PCL): pcl::gpu::AsyncCopy< T > Class Template Reference
pcl::gpu::AsyncCopy< T > Class Template Reference
#include </home/travis/build/PointCloudLibrary/pcl/gpu/people/src/cuda_async_copy.h>
Public Member Functions
AsyncCopy (T *ptr, size_t size)
AsyncCopy (std::vector< T > &data)
~AsyncCopy ()
void download (const DeviceArray< T > &arr)
void download (const DeviceArray2D< T > &arr)
void upload (const DeviceArray< T > &arr) const
void upload (const DeviceArray2D< T > &arr) const
void waitForCompeltion ()
Detailed Description
template<class T>
class pcl::gpu::AsyncCopy< T >
Definition at line 51 of file cuda_async_copy.h.
Constructor & Destructor Documentation
template<class T > pcl::gpu::AsyncCopy< T >::AsyncCopy (T * ptr, size_t size) inline
Definition at line 54 of file cuda_async_copy.h.
template<class T > pcl::gpu::AsyncCopy< T >::AsyncCopy (std::vector< T > & data) inline
Definition at line 60 of file cuda_async_copy.h.
template<class T > pcl::gpu::AsyncCopy< T >::~AsyncCopy () inline
Definition at line 66 of file cuda_async_copy.h.
Member Function Documentation
template<class T > void pcl::gpu::AsyncCopy< T >::download (const DeviceArray< T > & arr) inline
Definition at line 72 of file cuda_async_copy.h.
References pcl::gpu::DeviceArray< T >::ptr(), and pcl::gpu::DeviceMemory::sizeBytes().
template<class T > void pcl::gpu::AsyncCopy< T >::download (const DeviceArray2D< T > & arr) inline
Definition at line 77 of file cuda_async_copy.h.
References pcl::gpu::DeviceArray2D< T >::cols(), pcl::gpu::DeviceMemory2D::colsBytes(), pcl::gpu::DeviceArray2D< T >::ptr(), pcl::gpu::DeviceArray2D< T >::rows(), and pcl::gpu::DeviceMemory2D::step().
template<class T > void pcl::gpu::AsyncCopy< T >::upload (const DeviceArray< T > & arr) const inline
Definition at line 82 of file cuda_async_copy.h.
References pcl::gpu::DeviceArray< T >::ptr(), and pcl::gpu::DeviceArray< T >::size().
template<class T > void pcl::gpu::AsyncCopy< T >::upload (const DeviceArray2D< T > & arr) const inline
Definition at line 87 of file cuda_async_copy.h.
References pcl::gpu::DeviceArray2D< T >::cols(), pcl::gpu::DeviceMemory2D::colsBytes(), pcl::gpu::DeviceArray2D< T >::ptr(), pcl::gpu::DeviceArray2D< T >::rows(), and pcl::gpu::DeviceMemory2D::step().
template<class T > void pcl::gpu::AsyncCopy< T >::waitForCompeltion () inline
Definition at line 92 of file cuda_async_copy.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/gpu/people/src/cuda_async_copy.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:03