Point Cloud Library (PCL): pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT > Class Template Reference
pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT > Class Template Reference
Module keypoints
HarrisKeypoint3D uses the idea of 2D Harris keypoints, but instead of using image gradients, it uses surface normals.
#include <pcl/keypoints/harris_3d.h>
Public Types
enum ResponseMethod {
HARRIS = 1, NOBLE, LOWE, TOMASI,
CURVATURE
}
typedef boost::shared_ptr
< HarrisKeypoint3D< PointInT,
PointOutT, NormalT > > Ptr
typedef boost::shared_ptr
< const HarrisKeypoint3D
< PointInT, PointOutT, NormalT > > ConstPtr
typedef Keypoint< PointInT,
PointOutT >::PointCloudIn PointCloudIn
typedef Keypoint< PointInT,
PointOutT >::PointCloudOut PointCloudOut
typedef Keypoint< PointInT,
PointOutT >::KdTree KdTree
typedef PointCloudIn::ConstPtr PointCloudInConstPtr
typedef pcl::PointCloud< NormalT > PointCloudN
typedef PointCloudN::Ptr PointCloudNPtr
typedef PointCloudN::ConstPtr PointCloudNConstPtr
Public Types inherited from pcl::Keypoint< PointInT, PointOutT >
typedef boost::shared_ptr
< Keypoint< PointInT,
PointOutT > > Ptr
typedef boost::shared_ptr
< const Keypoint< PointInT,
PointOutT > > ConstPtr
typedef PCLBase< PointInT > BaseClass
typedef pcl::search::Search
< PointInT > KdTree
typedef pcl::search::Search
< PointInT >::Ptr KdTreePtr
typedef pcl::PointCloud< PointInT > PointCloudIn
typedef PointCloudIn::Ptr PointCloudInPtr
typedef PointCloudIn::ConstPtr PointCloudInConstPtr
typedef pcl::PointCloud
< PointOutT > PointCloudOut
typedef boost::function< int(int,
double, std::vector< int >
&, std::vector< float > &)> SearchMethod
typedef boost::function< int(const
PointCloudIn &cloud, int index,
double, std::vector< int >
&, std::vector< float > &)> SearchMethodSurface
Public Types inherited from pcl::PCLBase< PointInT >
typedef pcl::PointCloud< PointInT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Public Member Functions
HarrisKeypoint3D (ResponseMethod method=HARRIS, float radius=0.01f, float threshold=0.0f)
Constructor.
virtual ~HarrisKeypoint3D ()
Empty destructor.
virtual void setInputCloud (const PointCloudInConstPtr &cloud)
Provide a pointer to the input dataset.
void setMethod (ResponseMethod type)
Set the method of the response to be calculated.
void setRadius (float radius)
Set the radius for normal estimation and non maxima supression.
void setThreshold (float threshold)
Set the threshold value for detecting corners.
void setNonMaxSupression (bool=false)
Whether non maxima suppression should be applied or the response for each point should be returned.
void setRefine (bool do_refine)
Whether the detected key points should be refined or not.
void setNormals (const PointCloudNConstPtr &normals)
Set normals if precalculated normals are available.
virtual void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
void setNumberOfThreads (unsigned int nr_threads=0)
Initialize the scheduler and set the number of threads to use.
Public Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
Keypoint ()
void harrisCorner (ImageType &output, ImageType &input, const float sigma_d, const float sigma_i, const float alpha, const float thresh)
void hessianBlob (ImageType &output, ImageType &input, const float sigma, bool SCALE)
void hessianBlob (ImageType &output, ImageType &input, const float start_scale, const float scaling_factor, const int num_scales)
void imageElementMultiply (ImageType &output, ImageType &input1, ImageType &input2)
Keypoint ()
Empty constructor.
virtual ~Keypoint ()
Empty destructor.
PointCloudInConstPtr getSearchSurface ()
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod ()
Get a pointer to the search method used.
double getSearchParameter ()
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch ()
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the key point detection.
double getRadiusSearch ()
Get the sphere radius used for determining the neighbors.
pcl::PointIndicesConstPtr getKeypointsIndices ()
void compute (PointCloudOut &output)
Base method for key point detection for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
int searchForNeighbors (int index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (size_t row_start, size_t col_start, size_t nb_rows, size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute ()
void detectKeypoints (PointCloudOut &output)
Abstract key point detection method.
void responseHarris (PointCloudOut &output) const
gets the corner response for valid input points
void responseNoble (PointCloudOut &output) const
void responseLowe (PointCloudOut &output) const
void responseTomasi (PointCloudOut &output) const
void responseCurvature (PointCloudOut &output) const
void refineCorners (PointCloudOut &corners) const
void calculateNormalCovar (const std::vector< int > &neighbors, float *coefficients) const
calculates the upper triangular part of unnormalized covariance matrix over the normals given by the indices.
Protected Member Functions inherited from pcl::Keypoint< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Keypoint< PointInT, PointOutT >
std::string name_
The key point detection method's name.
SearchMethod search_method_
The search method template for indices.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (casted from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
pcl::PointIndicesPtr keypoints_indices_
Indices of the keypoints in the input cloud.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT, typename NormalT = pcl::Normal>
class pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >
HarrisKeypoint3D uses the idea of 2D Harris keypoints, but instead of using image gradients, it uses surface normals.
Author
Suat Gedikli
Definition at line 52 of file harris_3d.h.
Member Typedef Documentation
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef boost::shared_ptr<const HarrisKeypoint3D<PointInT, PointOutT, NormalT> > pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::ConstPtr
Definition at line 56 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef Keypoint<PointInT, PointOutT>::KdTree pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::KdTree
Definition at line 60 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef Keypoint<PointInT, PointOutT>::PointCloudIn pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::PointCloudIn
Definition at line 58 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef PointCloudIn::ConstPtr pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::PointCloudInConstPtr
Definition at line 61 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef pcl::PointCloud<NormalT> pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::PointCloudN
Definition at line 63 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef PointCloudN::ConstPtr pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::PointCloudNConstPtr
Definition at line 65 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef PointCloudN::Ptr pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::PointCloudNPtr
Definition at line 64 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef Keypoint<PointInT, PointOutT>::PointCloudOut pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::PointCloudOut
Definition at line 59 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> typedef boost::shared_ptr<HarrisKeypoint3D<PointInT, PointOutT, NormalT> > pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::Ptr
Definition at line 55 of file harris_3d.h.
Member Enumeration Documentation
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> enum pcl::HarrisKeypoint3D::ResponseMethod
Enumerator
HARRIS
NOBLE
LOWE
TOMASI
CURVATURE
Definition at line 79 of file harris_3d.h.
Constructor & Destructor Documentation
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::HarrisKeypoint3D (ResponseMethod method = HARRIS, float radius = 0.01f, float threshold = 0.0f) inline
Constructor.
Parameters
[in] method the method to be used to determine the corner responses
[in] radius the radius for normal estimation as well as for non maxima suppression
[in] threshold the threshold to filter out weak corners
Definition at line 86 of file harris_3d.h.
References pcl::Keypoint< PointInT, PointOutT >::name_, and pcl::Keypoint< PointInT, PointOutT >::search_radius_.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> virtual pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::~HarrisKeypoint3D () inline virtual
Empty destructor.
Definition at line 98 of file harris_3d.h.
Member Function Documentation
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::calculateNormalCovar (const std::vector< int > & neighbors, float * coefficients) const protected
calculates the upper triangular part of unnormalized covariance matrix over the normals given by the indices.
Definition at line 106 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::detectKeypoints (PointCloudOut & output) protected virtual
Abstract key point detection method.
Implements pcl::Keypoint< PointInT, PointOutT >.
Definition at line 241 of file harris_3d.hpp.
References pcl::PointCloud< T >::height, pcl::PointCloud< T >::is_dense, pcl::isFinite(), pcl::PointCloud< T >::points, and pcl::PointCloud< T >::width.
template<typename PointInT , typename PointOutT , typename NormalT > bool pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::initCompute () protected virtual
Reimplemented from pcl::Keypoint< PointInT, PointOutT >.
Definition at line 195 of file harris_3d.hpp.
References pcl::Feature< PointInT, PointOutT >::compute(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalEstimationMethod(), pcl::IntegralImageNormalEstimation< PointInT, PointOutT >::setNormalSmoothingSize(), and pcl::Feature< PointInT, PointOutT >::setRadiusSearch().
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::refineCorners (PointCloudOut & corners) const protected
Definition at line 498 of file harris_3d.hpp.
References pcl::invert3x3SymMatrix(), pcl::PointCloud< T >::points, and pcl::PointCloud< T >::size().
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::responseCurvature (PointCloudOut & output) const protected
Definition at line 437 of file harris_3d.hpp.
References pcl::PointCloud< T >::height, pcl::PointCloud< T >::points, and pcl::PointCloud< T >::width.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::responseHarris (PointCloudOut & output) const protected
gets the corner response for valid input points
Definition at line 322 of file harris_3d.hpp.
References pcl::PointCloud< T >::height, pcl::isFinite(), pcl::PointCloud< T >::resize(), and pcl::PointCloud< T >::width.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::responseLowe (PointCloudOut & output) const protected
Definition at line 399 of file harris_3d.hpp.
References pcl::PointCloud< T >::height, pcl::isFinite(), pcl::PointCloud< T >::resize(), and pcl::PointCloud< T >::width.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::responseNoble (PointCloudOut & output) const protected
Definition at line 361 of file harris_3d.hpp.
References pcl::PointCloud< T >::height, pcl::isFinite(), pcl::PointCloud< T >::resize(), and pcl::PointCloud< T >::width.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::responseTomasi (PointCloudOut & output) const protected
Definition at line 455 of file harris_3d.hpp.
References pcl::eigen33(), pcl::EIGEN_ALIGN16, pcl::PointCloud< T >::height, pcl::isFinite(), pcl::PointCloud< T >::resize(), and pcl::PointCloud< T >::width.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setInputCloud (const PointCloudInConstPtr & cloud) virtual
Provide a pointer to the input dataset.
Parameters
[in] cloud the const boost shared pointer to a PointCloud message
Reimplemented from pcl::PCLBase< PointInT >.
Definition at line 55 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setMethod (ResponseMethod type)
Set the method of the response to be calculated.
Parameters
[in] type
Definition at line 64 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setNonMaxSupression (bool nonmax = false)
Whether non maxima suppression should be applied or the response for each point should be returned.
Note
this value needs to be turned on in order to apply thresholding and refinement
Parameters
[in] nonmax default is false
Definition at line 92 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setNormals (const PointCloudNConstPtr & normals)
Set normals if precalculated normals are available.
Parameters
normals
Definition at line 99 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setNumberOfThreads (unsigned int nr_threads = 0) inline
Initialize the scheduler and set the number of threads to use.
Parameters
nr_threads the number of hardware threads to use (0 sets the value back to automatic)
Definition at line 159 of file harris_3d.h.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setRadius (float radius)
Set the radius for normal estimation and non maxima supression.
Parameters
[in] radius
Definition at line 78 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setRefine (bool do_refine)
Whether the detected key points should be refined or not.
If turned of, the key points are a subset of the original point cloud. Otherwise the key points may be arbitrary. note non maxima supression needs to be on in order to use this feature.
Parameters
[in] do_refine
Definition at line 85 of file harris_3d.hpp.
template<typename PointInT , typename PointOutT , typename NormalT = pcl::Normal> virtual void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setSearchSurface (const PointCloudInConstPtr & cloud) inline virtual
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
This is optional, if this is not set, it will only use the data in the input cloud to estimate the features. This is useful when you only need to compute the features for a downsampled cloud.
Parameters
[in] cloud a pointer to a PointCloud message
Reimplemented from pcl::Keypoint< PointInT, PointOutT >.
Definition at line 153 of file harris_3d.h.
References pcl::Keypoint< PointInT, PointOutT >::surface_.
template<typename PointInT , typename PointOutT , typename NormalT > void pcl::HarrisKeypoint3D< PointInT, PointOutT, NormalT >::setThreshold (float threshold)
Set the threshold value for detecting corners.
This is only evaluated if non maxima suppression is turned on. note non maxima suppression needs to be activated in order to use this feature.
Parameters
[in] threshold
Definition at line 71 of file harris_3d.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/keypoints/include/pcl/keypoints/harris_3d.h
/home/travis/build/PointCloudLibrary/pcl/keypoints/include/pcl/keypoints/impl/harris_3d.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:31