Point Cloud Library (PCL): pcl::gpu::DeviceMemory Class Reference
pcl::gpu::DeviceMemory Class Reference
DeviceMemory class
#include </home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/device_memory.h>
Public Member Functions
DeviceMemory ()
Empty constructor.
~DeviceMemory ()
Destructor.
DeviceMemory (size_t sizeBytes_arg)
Allocates internal buffer in GPU memory.
DeviceMemory (void *ptr_arg, size_t sizeBytes_arg)
Initializes with user allocated buffer.
DeviceMemory (const DeviceMemory &other_arg)
Copy constructor.
DeviceMemory & operator= (const DeviceMemory &other_arg)
Assignment operator.
void create (size_t sizeBytes_arg)
Allocates internal buffer in GPU memory.
void release ()
Decrements reference counter and releases internal buffer if needed.
void copyTo (DeviceMemory &other) const
Performs data copying.
void upload (const void *host_ptr_arg, size_t sizeBytes_arg)
Uploads data to internal buffer in GPU memory.
void download (void *host_ptr_arg) const
Downloads data from internal buffer to CPU memory.
void swap (DeviceMemory &other_arg)
Performs swap of data pointed with another device memory.
template<class T >
T * ptr ()
Returns pointer for internal buffer in GPU memory.
template<class T >
const T * ptr () const
Returns constant pointer for internal buffer in GPU memory.
template<class U >
operator PtrSz< U > () const
Conversion to PtrSz for passing to kernel functions.
bool empty () const
Returns true if unallocated otherwise false.
size_t sizeBytes () const
Detailed Description
DeviceMemory class
Note
This is a BLOB container class with reference counting for GPU memory.
Author
Anatoly Baksheev
Definition at line 55 of file device_memory.h.
Constructor & Destructor Documentation
pcl::gpu::DeviceMemory::DeviceMemory ()
Empty constructor.
pcl::gpu::DeviceMemory::~DeviceMemory ()
Destructor.
pcl::gpu::DeviceMemory::DeviceMemory (size_t sizeBytes_arg)
Allocates internal buffer in GPU memory.
Parameters
sizeBytes_arg amount of memory to allocate
pcl::gpu::DeviceMemory::DeviceMemory (void * ptr_arg, size_t sizeBytes_arg)
Initializes with user allocated buffer.
Reference counting is disabled in this case.
Parameters
ptr_arg pointer to buffer
sizeBytes_arg buffer size
pcl::gpu::DeviceMemory::DeviceMemory (const DeviceMemory & other_arg)
Copy constructor.
Just increments reference counter.
Member Function Documentation
void pcl::gpu::DeviceMemory::copyTo (DeviceMemory & other) const
Performs data copying.
If destination size differs it will be reallocated.
Parameters
other destination container
Referenced by pcl::gpu::DeviceArray< T >::copyTo().
void pcl::gpu::DeviceMemory::create (size_t sizeBytes_arg)
Allocates internal buffer in GPU memory.
If internal buffer was created before the function recreates it with new size. If new and old sizes are equal it does nothing.
Parameters
sizeBytes_arg buffer size
Referenced by pcl::gpu::DeviceArray< T >::create().
void pcl::gpu::DeviceMemory::download (void * host_ptr_arg) const
Downloads data from internal buffer to CPU memory.
Parameters
host_ptr_arg pointer to buffer to download
Referenced by pcl::gpu::DeviceArray< T >::download().
bool pcl::gpu::DeviceMemory::empty () const
Returns true if unallocated otherwise false.
Referenced by pcl::gpu::kinfuLS::StandaloneMarchingCubes< PointT >::convertTrianglesToMesh().
template<class U > pcl::gpu::DeviceMemory::operator PtrSz< U > () const
Conversion to PtrSz for passing to kernel functions.
DeviceMemory& pcl::gpu::DeviceMemory::operator= (const DeviceMemory & other_arg)
Assignment operator.
Just increments reference counter.
Referenced by pcl::gpu::DeviceArray< T >::operator=().
template<class T > T * pcl::gpu::DeviceMemory::ptr () inline
Returns pointer for internal buffer in GPU memory.
Definition at line 42 of file device_memory.hpp.
template<class T > const T * pcl::gpu::DeviceMemory::ptr () const inline
Returns constant pointer for internal buffer in GPU memory.
Definition at line 43 of file device_memory.hpp.
void pcl::gpu::DeviceMemory::release ()
Decrements reference counter and releases internal buffer if needed.
Referenced by pcl::gpu::DeviceArray< T >::release().
size_t pcl::gpu::DeviceMemory::sizeBytes () const
Referenced by pcl::gpu::AsyncCopy< T >::download(), and pcl::gpu::TextureBinder::TextureBinder().
void pcl::gpu::DeviceMemory::swap (DeviceMemory & other_arg)
Performs swap of data pointed with another device memory.
Parameters
other_arg device memory to swap with
Referenced by pcl::gpu::DeviceArray< T >::swap().
void pcl::gpu::DeviceMemory::upload (const void * host_ptr_arg, size_t sizeBytes_arg)
Uploads data to internal buffer in GPU memory.
It calls create() inside to ensure that intenal buffer size is enough.
Parameters
host_ptr_arg pointer to buffer to upload
sizeBytes_arg buffer size
Referenced by pcl::gpu::DeviceArray< T >::upload().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/device_memory.h
/home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/impl/device_memory.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:00