Point Cloud Library (PCL): pcl::SVMTrain Class Reference
pcl::SVMTrain Class Reference
SVM (Support Vector Machines) training class for the SVM machine learning.
#include <pcl/ml/svm_wrapper.h>
Public Member Functions
SVMTrain ()
Constructor.
~SVMTrain ()
Destructor.
void setParameters (SVMParam param)
Change default training parameters (pcl::SVMParam).
SVMParam getParameters ()
Return the current training parameters.
SVMModel getClassifierModel ()
Return the result of the training.
void setInputTrainingSet (std::vector< SVMData > training_set)
It adds/store the training set with labelled data.
std::vector< SVMData > getInputTrainingSet ()
Return the current training set.
void resetTrainingSet ()
Reset the training set.
bool trainClassifier ()
Start the training of the SVM classifier.
bool loadProblem (const char *filename)
Read in a problem (in svmlight format).
void setDebugMode (bool in)
Set to 1 for debugging info.
bool saveTrainingSet (const char *filename)
Save the raw training set in a file (in svmlight format).
bool saveNormTrainingSet (const char *filename)
Save the normalized training set in a file (in svmlight format).
Public Member Functions inherited from pcl::SVM
SVM ()
Constructor.
~SVM ()
Destructor.
void getLabel (std::vector< int > &labels)
Return the labels order from the classifier model.
void saveClassifierModel (const char *filename)
Save the classifier model in an extern file (in svmlight format).
Protected Member Functions
void doCrossValidation ()
To cross validate the classifier.
void scaleFactors (std::vector< SVMData > training_set, svm_scaling &scaling)
It extracts scaling factors from the input training_set.
Protected Member Functions inherited from pcl::SVM
char * readline (FILE *input)
To read a line from the input file.
void exitInputError (int line_num)
Outputs an error in file reading.
const std::string & getClassName () const
Get a string representation of the name of this class.
void adaptInputToLibSVM (std::vector< SVMData > training_set, svm_problem &prob)
Convert the input format (vector of SVMData) into a readable format for libSVM.
void adaptLibSVMToInput (std::vector< SVMData > &training_set, svm_problem prob)
Convert the libSVM format (svm_problem) into a easier output format.
bool loadProblem (const char *filename, svm_problem &prob)
Load a problem from an extern file.
bool saveProblem (const char *filename, bool labelled)
Save the raw problem in an extern file.
bool saveProblemNorm (const char *filename, svm_problem prob_, bool labelled)
Save the problem (with normalized values) in an extern file.
Protected Attributes
bool debug_
int cross_validation_
int nr_fold_
Protected Attributes inherited from pcl::SVM
std::vector< SVMData > training_set_
svm_problem prob_
SVMModel model_
svm_scaling scaling_
SVMParam param_
std::string class_name_
char * line_
int max_line_len_
bool labelled_training_set_
Additional Inherited Members
Static Protected Member Functions inherited from pcl::SVM
static void printNull (const char *)
Set for output printings during classification.
Detailed Description
SVM (Support Vector Machines) training class for the SVM machine learning.
It creates a model for the classifier from a labelled input dataset. OPTIONAL: pcl::SVMParam has to be given as input to vary the default training method and parameters.
Definition at line 236 of file svm_wrapper.h.
Constructor & Destructor Documentation
pcl::SVMTrain::SVMTrain () inline
Constructor.
Definition at line 264 of file svm_wrapper.h.
References pcl::SVM::class_name_, and pcl::SVM::printNull().
pcl::SVMTrain::~SVMTrain () inline
Destructor.
Definition at line 271 of file svm_wrapper.h.
References svm_model::l, and pcl::SVM::model_.
Member Function Documentation
void pcl::SVMTrain::doCrossValidation () protected
To cross validate the classifier.
It is automatic for probability estimate.
SVMModel pcl::SVMTrain::getClassifierModel () inline
Return the result of the training.
Definition at line 293 of file svm_wrapper.h.
References pcl::SVM::model_.
std::vector<SVMData> pcl::SVMTrain::getInputTrainingSet () inline
Return the current training set.
Definition at line 307 of file svm_wrapper.h.
References pcl::SVM::training_set_.
SVMParam pcl::SVMTrain::getParameters () inline
Return the current training parameters.
Definition at line 286 of file svm_wrapper.h.
References pcl::SVM::param_.
bool pcl::SVMTrain::loadProblem (const char * filename) inline
Read in a problem (in svmlight format).
Returns
false if fails.
Definition at line 327 of file svm_wrapper.h.
References pcl::SVM::loadProblem(), and pcl::SVM::prob_.
void pcl::SVMTrain::resetTrainingSet () inline
Reset the training set.
Definition at line 314 of file svm_wrapper.h.
References pcl::SVM::training_set_.
bool pcl::SVMTrain::saveNormTrainingSet (const char * filename) inline
Save the normalized training set in a file (in svmlight format).
Returns
false if fails.
Definition at line 355 of file svm_wrapper.h.
References pcl::SVM::prob_, and pcl::SVM::saveProblemNorm().
bool pcl::SVMTrain::saveTrainingSet (const char * filename) inline
Save the raw training set in a file (in svmlight format).
Returns
false if fails.
Definition at line 347 of file svm_wrapper.h.
References pcl::SVM::saveProblem().
void pcl::SVMTrain::scaleFactors (std::vector< SVMData > training_set, svm_scaling & scaling) protected
It extracts scaling factors from the input training_set.
The scaling of the training_set is a mandatory for a good training of the classifier.
void pcl::SVMTrain::setDebugMode (bool in) inline
Set to 1 for debugging info.
Definition at line 334 of file svm_wrapper.h.
References debug_, and pcl::SVM::printNull().
void pcl::SVMTrain::setInputTrainingSet (std::vector< SVMData > training_set) inline
It adds/store the training set with labelled data.
Definition at line 300 of file svm_wrapper.h.
References pcl::SVM::training_set_.
void pcl::SVMTrain::setParameters (SVMParam param) inline
Change default training parameters (pcl::SVMParam).
Definition at line 279 of file svm_wrapper.h.
References pcl::SVM::param_.
bool pcl::SVMTrain::trainClassifier ()
Start the training of the SVM classifier.
Returns
false if fails.
Member Data Documentation
int pcl::SVMTrain::cross_validation_ protected
Definition at line 250 of file svm_wrapper.h.
bool pcl::SVMTrain::debug_ protected
Definition at line 249 of file svm_wrapper.h.
Referenced by setDebugMode().
int pcl::SVMTrain::nr_fold_ protected
Definition at line 251 of file svm_wrapper.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/ml/include/pcl/ml/svm_wrapper.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:34