Point Cloud Library (PCL): pcl::visualization::PointCloudColorHandlerRGBAField< PointT > Class Template Reference
pcl::visualization::PointCloudColorHandlerRGBAField< PointT > Class Template Reference
Module visualization
RGBA handler class for colors.
#include <pcl/visualization/point_cloud_color_handlers.h>
Public Types
typedef boost::shared_ptr
< PointCloudColorHandlerRGBAField
< PointT > > Ptr
typedef boost::shared_ptr
< const
PointCloudColorHandlerRGBAField
< PointT > > ConstPtr
Public Types inherited from pcl::visualization::PointCloudColorHandler< PointT >
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointCloudColorHandler
< PointT > > Ptr
typedef boost::shared_ptr
< const PointCloudColorHandler
< PointT > > ConstPtr
Public Member Functions
PointCloudColorHandlerRGBAField ()
Constructor.
PointCloudColorHandlerRGBAField (const PointCloudConstPtr &cloud)
Constructor.
virtual ~PointCloudColorHandlerRGBAField ()
Destructor.
virtual std::string getFieldName () const
Get the name of the field used.
virtual bool getColor (vtkSmartPointer< vtkDataArray > &scalars) const
Obtain the actual color for the input dataset as vtk scalars.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Set the input cloud to be used.
Public Member Functions inherited from pcl::visualization::PointCloudColorHandler< PointT >
PointCloudColorHandler ()
Constructor.
PointCloudColorHandler (const PointCloudConstPtr &cloud)
Constructor.
virtual ~PointCloudColorHandler ()
Destructor.
bool isCapable () const
Check if this handler is capable of handling the input data or not.
Protected Member Functions
virtual std::string getName () const
Class getName method.
Additional Inherited Members
Protected Attributes inherited from pcl::visualization::PointCloudColorHandler< PointT >
PointCloudConstPtr cloud_
A pointer to the input dataset.
bool capable_
True if this handler is capable of handling the input data, false otherwise.
int field_idx_
The index of the field holding the data that represents the color.
std::vector< pcl::PCLPointField > fields_
The list of fields available for this PointCloud.
Detailed Description
template<typename PointT>
class pcl::visualization::PointCloudColorHandlerRGBAField< PointT >
RGBA handler class for colors.
Uses the data present in the "rgba" field as the color at each point. Transparency is handled.
Author
Nizar Sallem
Definition at line 442 of file point_cloud_color_handlers.h.
Member Typedef Documentation
template<typename PointT> typedef boost::shared_ptr<const PointCloudColorHandlerRGBAField<PointT> > pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::ConstPtr
Definition at line 450 of file point_cloud_color_handlers.h.
template<typename PointT> typedef boost::shared_ptr<PointCloudColorHandlerRGBAField<PointT> > pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::Ptr
Definition at line 449 of file point_cloud_color_handlers.h.
Constructor & Destructor Documentation
template<typename PointT> pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::PointCloudColorHandlerRGBAField () inline
Constructor.
Definition at line 453 of file point_cloud_color_handlers.h.
References pcl::visualization::PointCloudColorHandler< PointT >::capable_.
template<typename PointT> pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::PointCloudColorHandlerRGBAField (const PointCloudConstPtr & cloud) inline
Constructor.
Definition at line 459 of file point_cloud_color_handlers.h.
References pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::setInputCloud().
template<typename PointT> virtual pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::~PointCloudColorHandlerRGBAField () inline virtual
Destructor.
Definition at line 466 of file point_cloud_color_handlers.h.
Member Function Documentation
template<typename PointT > bool pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::getColor (vtkSmartPointer< vtkDataArray > & scalars) const virtual
Obtain the actual color for the input dataset as vtk scalars.
Parameters
[out] scalars the output scalars containing the color for the dataset
Returns
true if the operation was successful (the handler is capable and the input cloud was given as a valid pointer), false otherwise
Implements pcl::visualization::PointCloudColorHandler< PointT >.
Definition at line 456 of file point_cloud_color_handlers.hpp.
template<typename PointT> virtual std::string pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::getFieldName () const inline virtual
Get the name of the field used.
Implements pcl::visualization::PointCloudColorHandler< PointT >.
Definition at line 470 of file point_cloud_color_handlers.h.
template<typename PointT> virtual std::string pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::getName () const inline protected virtual
Class getName method.
Implements pcl::visualization::PointCloudColorHandler< PointT >.
Definition at line 489 of file point_cloud_color_handlers.h.
template<typename PointT > void pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::setInputCloud (const PointCloudConstPtr & cloud) virtual
Set the input cloud to be used.
Parameters
[in] cloud the input cloud to be used by the handler
Reimplemented from pcl::visualization::PointCloudColorHandler< PointT >.
Definition at line 442 of file point_cloud_color_handlers.hpp.
References pcl::getFieldIndex(), and pcl::visualization::PointCloudColorHandler< PointT >::setInputCloud().
Referenced by pcl::visualization::PointCloudColorHandlerRGBAField< PointT >::PointCloudColorHandlerRGBAField().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/visualization/include/pcl/visualization/point_cloud_color_handlers.h
/home/travis/build/PointCloudLibrary/pcl/visualization/include/pcl/visualization/impl/point_cloud_color_handlers.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:33