Point Cloud Library (PCL): pcl::recognition::ModelLibrary::Model Class Reference
pcl::recognition::ModelLibrary::Model Class Reference
Stores some information about the model.
#include <pcl/recognition/ransac_based/model_library.h>
Public Member Functions
Model (const PointCloudIn &points, const PointCloudN &normals, float voxel_size, const std::string &object_name, float frac_of_points_for_registration, void *user_data=NULL)
virtual ~Model ()
const std::string & getObjectName () const
const ORROctree & getOctree () const
void * getUserData () const
const float * getOctreeCenterOfMass () const
const float * getBoundsOfOctreePoints () const
const PointCloudIn & getPointsForRegistration () const
Protected Attributes
const std::string obj_name_
ORROctree octree_
float octree_center_of_mass_ [3]
float bounds_of_octree_points_ [6]
PointCloudIn points_for_registration_
void * user_data_
Detailed Description
Stores some information about the model.
Definition at line 66 of file model_library.h.
Constructor & Destructor Documentation
pcl::recognition::ModelLibrary::Model::Model (const PointCloudIn & points, const PointCloudN & normals, float voxel_size, const std::string & object_name, float frac_of_points_for_registration, void * user_data = NULL) inline
Definition at line 69 of file model_library.h.
References pcl::recognition::aux::add3(), pcl::recognition::aux::copy3(), pcl::recognition::aux::expandBoundingBoxToContainPoint(), pcl::recognition::aux::mult3(), pcl::common::UniformGenerator< T >::run(), and pcl::common::UniformGenerator< T >::setParameters().
virtual pcl::recognition::ModelLibrary::Model::~Model () inline virtual
Definition at line 125 of file model_library.h.
Member Function Documentation
const float* pcl::recognition::ModelLibrary::Model::getBoundsOfOctreePoints () const inline
Definition at line 154 of file model_library.h.
Referenced by pcl::recognition::Hypothesis::computeBounds().
const std::string& pcl::recognition::ModelLibrary::Model::getObjectName () const inline
Definition at line 130 of file model_library.h.
const ORROctree& pcl::recognition::ModelLibrary::Model::getOctree () const inline
Definition at line 136 of file model_library.h.
const float* pcl::recognition::ModelLibrary::Model::getOctreeCenterOfMass () const inline
Definition at line 148 of file model_library.h.
Referenced by pcl::recognition::Hypothesis::computeCenterOfMass().
const PointCloudIn& pcl::recognition::ModelLibrary::Model::getPointsForRegistration () const inline
Definition at line 160 of file model_library.h.
void* pcl::recognition::ModelLibrary::Model::getUserData () const inline
Definition at line 142 of file model_library.h.
Member Data Documentation
float pcl::recognition::ModelLibrary::Model::bounds_of_octree_points_[6] protected
Definition at line 169 of file model_library.h.
const std::string pcl::recognition::ModelLibrary::Model::obj_name_ protected
Definition at line 166 of file model_library.h.
ORROctree pcl::recognition::ModelLibrary::Model::octree_ protected
Definition at line 167 of file model_library.h.
float pcl::recognition::ModelLibrary::Model::octree_center_of_mass_[3] protected
Definition at line 168 of file model_library.h.
PointCloudIn pcl::recognition::ModelLibrary::Model::points_for_registration_ protected
Definition at line 170 of file model_library.h.
void* pcl::recognition::ModelLibrary::Model::user_data_ protected
Definition at line 171 of file model_library.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/recognition/include/pcl/recognition/ransac_based/model_library.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:17