Point Cloud Library (PCL): pcl::FilterIndices< pcl::PCLPointCloud2 > Class Template Reference
pcl::FilterIndices< pcl::PCLPointCloud2 > Class Template Reference abstract
Module filters
FilterIndices represents the base class for filters that are about binary point removal.
#include <pcl/filters/filter_indices.h>
Public Types
typedef pcl::PCLPointCloud2 PCLPointCloud2
Public Types inherited from pcl::Filter< pcl::PCLPointCloud2 >
typedef boost::shared_ptr
< Filter< pcl::PCLPointCloud2 > > Ptr
typedef boost::shared_ptr
< const Filter
< pcl::PCLPointCloud2 > > ConstPtr
typedef pcl::PCLPointCloud2 PCLPointCloud2
typedef PCLPointCloud2::Ptr PCLPointCloud2Ptr
typedef PCLPointCloud2::ConstPtr PCLPointCloud2ConstPtr
Public Types inherited from pcl::PCLBase< pcl::PCLPointCloud2 >
typedef pcl::PCLPointCloud2 PCLPointCloud2
typedef boost::shared_ptr
< PCLPointCloud2 > PCLPointCloud2Ptr
typedef boost::shared_ptr
< PCLPointCloud2 const > PCLPointCloud2ConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Public Member Functions
FilterIndices (bool extract_removed_indices=false)
Constructor.
virtual ~FilterIndices ()
Empty virtual destructor.
virtual void filter (PCLPointCloud2 &output)
void filter (std::vector< int > &indices)
Calls the filtering method and returns the filtered point cloud indices.
void setNegative (bool negative)
Set whether the regular conditions for points filtering should apply, or the inverted conditions.
bool getNegative () const
Get whether the regular conditions for points filtering should apply, or the inverted conditions.
void setKeepOrganized (bool keep_organized)
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
bool getKeepOrganized () const
Get whether the filtered points should be kept and set to the value given through setUserFilterValue (default = NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
void setUserFilterValue (float value)
Provide a value that the filtered points should be set to instead of removing them.
Public Member Functions inherited from pcl::Filter< pcl::PCLPointCloud2 >
Filter (bool extract_removed_indices=false)
Empty constructor.
virtual ~Filter ()
Empty destructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PCLPointCloud2 &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< pcl::PCLPointCloud2 >
PCLBase ()
Empty constructor.
virtual ~PCLBase ()
destructor.
void setInputCloud (const PCLPointCloud2ConstPtr &cloud)
Provide a pointer to the input dataset.
PCLPointCloud2ConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
IndicesPtr const getIndices () const
Get a pointer to the vector of indices used.
Protected Member Functions
virtual void applyFilter (std::vector< int > &indices)=0
Abstract filter method for point cloud indices.
virtual void applyFilter (PCLPointCloud2 &output)=0
Abstract filter method for point cloud.
Protected Member Functions inherited from pcl::Filter< pcl::PCLPointCloud2 >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< pcl::PCLPointCloud2 >
bool initCompute ()
bool deinitCompute ()
Protected Attributes
bool negative_
False = normal filter behavior (default), true = inverted behavior.
bool keep_organized_
False = remove points (default), true = redefine points, keep structure.
float user_filter_value_
The user given value that the filtered point dimensions should be set to (default = NaN).
Protected Attributes inherited from pcl::Filter< pcl::PCLPointCloud2 >
IndicesPtr removed_indices_
Indices of the points that are removed.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
std::string filter_name_
The filter name.
Protected Attributes inherited from pcl::PCLBase< pcl::PCLPointCloud2 >
PCLPointCloud2ConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
std::vector< int > field_sizes_
The size of each individual field.
int x_idx_
The x-y-z fields indices.
int y_idx_
int z_idx_
std::string x_field_name_
The desired x-y-z field names.
std::string y_field_name_
std::string z_field_name_
Detailed Description
template<>
class pcl::FilterIndices< pcl::PCLPointCloud2 >
FilterIndices represents the base class for filters that are about binary point removal.
All derived classes have to implement the filter (PointCloud &output) and the filter (std::vector<int> &indices) methods. Ideally they also make use of the negative_, keep_organized_ and extract_removed_indices_ systems. The distinguishment between the negative_ and extract_removed_indices_ systems only makes sense if the class automatically filters non-finite entries in the filtering methods (recommended).
Author
Justin Rosen
Definition at line 205 of file filter_indices.h.
Member Typedef Documentation
typedef pcl::PCLPointCloud2 pcl::FilterIndices< pcl::PCLPointCloud2 >::PCLPointCloud2
Definition at line 208 of file filter_indices.h.
Constructor & Destructor Documentation
pcl::FilterIndices< pcl::PCLPointCloud2 >::FilterIndices (bool extract_removed_indices = false) inline
Constructor.
Parameters
[in] extract_removed_indices Set to true if you want to extract the indices of points being removed (default = false).
Definition at line 213 of file filter_indices.h.
virtual pcl::FilterIndices< pcl::PCLPointCloud2 >::~FilterIndices () inline virtual
Empty virtual destructor.
Definition at line 223 of file filter_indices.h.
Member Function Documentation
virtual void pcl::FilterIndices< pcl::PCLPointCloud2 >::applyFilter (std::vector< int > & indices) protected pure virtual
Abstract filter method for point cloud indices.
Implemented in pcl::CropBox< pcl::PCLPointCloud2 >, pcl::StatisticalOutlierRemoval< pcl::PCLPointCloud2 >, pcl::RandomSample< pcl::PCLPointCloud2 >, and pcl::ExtractIndices< pcl::PCLPointCloud2 >.
virtual void pcl::FilterIndices< pcl::PCLPointCloud2 >::applyFilter (PCLPointCloud2 & output) protected pure virtual
Abstract filter method for point cloud.
Implements pcl::Filter< pcl::PCLPointCloud2 >.
Implemented in pcl::CropBox< pcl::PCLPointCloud2 >, pcl::StatisticalOutlierRemoval< pcl::PCLPointCloud2 >, pcl::RandomSample< pcl::PCLPointCloud2 >, and pcl::ExtractIndices< pcl::PCLPointCloud2 >.
virtual void pcl::FilterIndices< pcl::PCLPointCloud2 >::filter (PCLPointCloud2 & output) inline virtual
Definition at line 228 of file filter_indices.h.
References pcl::Filter< PointT >::filter().
Referenced by pcl::outofcore::OutofcoreOctreeBaseNode< ContainerT, PointT >::addPointCloud_and_genLOD(), pcl::outofcore::OutofcoreOctreeBase< ContainerT, PointT >::buildLODRecursive(), and pcl::outofcore::OutofcoreOctreeBaseNode< ContainerT, PointT >::queryBBIncludes_subsample().
void pcl::FilterIndices< pcl::PCLPointCloud2 >::filter (std::vector< int > & indices)
Calls the filtering method and returns the filtered point cloud indices.
Parameters
[out] indices the resultant filtered point cloud indices
bool pcl::FilterIndices< pcl::PCLPointCloud2 >::getKeepOrganized () const inline
Get whether the filtered points should be kept and set to the value given through setUserFilterValue (default = NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
Returns
The value of the internal keep_organized_ parameter; false = remove points (default), true = redefine points, keep structure.
Definition at line 272 of file filter_indices.h.
bool pcl::FilterIndices< pcl::PCLPointCloud2 >::getNegative () const inline
Get whether the regular conditions for points filtering should apply, or the inverted conditions.
Returns
The value of the internal negative_ parameter; false = normal filter behavior (default), true = inverted behavior.
Definition at line 252 of file filter_indices.h.
void pcl::FilterIndices< pcl::PCLPointCloud2 >::setKeepOrganized (bool keep_organized) inline
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
Parameters
[in] keep_organized false = remove points (default), true = redefine points, keep structure.
Definition at line 262 of file filter_indices.h.
void pcl::FilterIndices< pcl::PCLPointCloud2 >::setNegative (bool negative) inline
Set whether the regular conditions for points filtering should apply, or the inverted conditions.
Parameters
[in] negative false = normal filter behavior (default), true = inverted behavior.
Definition at line 243 of file filter_indices.h.
Referenced by pcl::outofcore::OutofcoreOctreeBaseNode< ContainerT, PointT >::addPointCloud_and_genLOD().
void pcl::FilterIndices< pcl::PCLPointCloud2 >::setUserFilterValue (float value) inline
Provide a value that the filtered points should be set to instead of removing them.
Used in conjunction with setKeepOrganized ().
Parameters
[in] value the user given value that the filtered point dimensions should be set to (default = NaN).
Definition at line 282 of file filter_indices.h.
Member Data Documentation
bool pcl::FilterIndices< pcl::PCLPointCloud2 >::keep_organized_ protected
False = remove points (default), true = redefine points, keep structure.
Definition at line 293 of file filter_indices.h.
bool pcl::FilterIndices< pcl::PCLPointCloud2 >::negative_ protected
False = normal filter behavior (default), true = inverted behavior.
Definition at line 290 of file filter_indices.h.
float pcl::FilterIndices< pcl::PCLPointCloud2 >::user_filter_value_ protected
The user given value that the filtered point dimensions should be set to (default = NaN).
Definition at line 296 of file filter_indices.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/filter_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:19