Point Cloud Library (PCL): pcl::DisparityMapConverter< PointT > Class Template Reference
pcl::DisparityMapConverter< PointT > Class Template Reference
Compute point cloud from the disparity map.
#include <pcl/stereo/disparity_map_converter.h>
Public Member Functions
DisparityMapConverter ()
DisparityMapConverter constructor.
virtual ~DisparityMapConverter ()
Empty destructor.
void setImageCenterX (const float center_x)
Set x-coordinate of the image center.
float getImageCenterX () const
Get x-coordinate of the image center.
void setImageCenterY (const float center_y)
Set y-coordinate of the image center.
float getImageCenterY () const
Get y-coordinate of the image center.
void setFocalLength (const float focal_length)
Set focal length.
float getFocalLength () const
Get focal length.
void setBaseline (const float baseline)
Set baseline.
float getBaseline () const
Get baseline.
void setDisparityThresholdMin (const float disparity_threshold_min)
Set min disparity threshold.
float getDisparityThresholdMin () const
Get min disparity threshold.
void setDisparityThresholdMax (const float disparity_threshold_max)
Set max disparity threshold.
float getDisparityThresholdMax () const
Get max disparity threshold.
void setImage (const pcl::PointCloud< pcl::RGB >::ConstPtr &image)
Set an image, that will be used for coloring of the output cloud.
pcl::PointCloud< RGB >::Ptr getImage ()
Get the image, that is used for coloring of the output cloud.
bool loadDisparityMap (const std::string &file_name)
Load the disparity map.
bool loadDisparityMap (const std::string &file_name, const size_t width, const size_t height)
Load the disparity map and initialize it's size.
void setDisparityMap (const std::vector< float > &disparity_map)
Set the disparity map.
void setDisparityMap (const std::vector< float > &disparity_map, const size_t width, const size_t height)
Set the disparity map and initialize it's size.
std::vector< float > getDisparityMap ()
Get the disparity map.
virtual void compute (PointCloud &out_cloud)
Compute the output cloud.
Protected Types
typedef pcl::PointCloud< PointT > PointCloud
Protected Member Functions
PointXYZ translateCoordinates (size_t row, size_t column, float disparity) const
Translate point from image coordinates and disparity to 3D-coordinates.
Protected Attributes
float center_x_
X-coordinate of the image center.
float center_y_
Y-coordinate of the image center.
float focal_length_
Focal length.
float baseline_
Baseline.
bool is_color_
Is color image is set.
pcl::PointCloud< pcl::RGB >
::ConstPtr image_
Color image of the scene.
std::vector< float > disparity_map_
Vector for the disparity map.
size_t disparity_map_width_
X-size of the disparity map.
size_t disparity_map_height_
Y-size of the disparity map.
float disparity_threshold_min_
Thresholds of the disparity.
float disparity_threshold_max_
Detailed Description
template<typename PointT>
class pcl::DisparityMapConverter< PointT >
Compute point cloud from the disparity map.
Example of usage:
pcl::PointCloud<pcl::PointXYZI>::Ptr cloud (new
  pcl::PointCloud<pcl::PointXYZI>);
pcl::PointCloud<pcl::RGB>::Ptr left_image (new
  pcl::PointCloud<pcl::RGB>);
// Fill left image cloud.
pcl::DisparityMapConverter<pcl::PointXYZI> dmc;
dmc.setBaseline (0.8387445f);
dmc.setFocalLength (368.534700f);
dmc.setImageCenterX (318.112200f);
dmc.setImageCenterY (224.334900f);
dmc.setDisparityThresholdMin(15.0f);
// Left view of the scene.
dmc.setImage (left_image);
// Disparity map of the scene.
dmc.loadDisparityMap ("disparity_map.txt", 640, 480);
dmc.compute(*cloud);
Author
Timur Ibadov (ibado.nosp@m.v.ti.nosp@m.mur@g.nosp@m.mail.nosp@m..com)
Definition at line 77 of file disparity_map_converter.h.
Member Typedef Documentation
template<typename PointT> typedef pcl::PointCloud<PointT> pcl::DisparityMapConverter< PointT >::PointCloud protected
Definition at line 80 of file disparity_map_converter.h.
Constructor & Destructor Documentation
template<typename PointT > pcl::DisparityMapConverter< PointT >::DisparityMapConverter ()
DisparityMapConverter constructor.
Definition at line 49 of file disparity_map_converter.hpp.
template<typename PointT > pcl::DisparityMapConverter< PointT >::~DisparityMapConverter () virtual
Empty destructor.
Definition at line 63 of file disparity_map_converter.hpp.
Member Function Documentation
template<typename PointT > void pcl::DisparityMapConverter< PointT >::compute (PointCloud & out_cloud) virtual
Compute the output cloud.
Parameters
[out] out_cloud the variable to return the resulting cloud.
Definition at line 231 of file disparity_map_converter.hpp.
References pcl::PointCloud< T >::clear(), pcl::PointCloud< T >::height, pcl::PointCloud< T >::resize(), pcl::common::IntensityFieldAccessor< PointT >::set(), and pcl::PointCloud< T >::width.
template<typename PointT > float pcl::DisparityMapConverter< PointT >::getBaseline () const inline
Get baseline.
Returns
the baseline.
Definition at line 110 of file disparity_map_converter.hpp.
template<typename PointT > std::vector< float > pcl::DisparityMapConverter< PointT >::getDisparityMap ()
Get the disparity map.
Returns
the disparity map.
Definition at line 225 of file disparity_map_converter.hpp.
template<typename PointT > float pcl::DisparityMapConverter< PointT >::getDisparityThresholdMax () const inline
Get max disparity threshold.
Returns
max disparity threshold.
Definition at line 136 of file disparity_map_converter.hpp.
template<typename PointT > float pcl::DisparityMapConverter< PointT >::getDisparityThresholdMin () const inline
Get min disparity threshold.
Returns
min disparity threshold.
Definition at line 123 of file disparity_map_converter.hpp.
template<typename PointT > float pcl::DisparityMapConverter< PointT >::getFocalLength () const inline
Get focal length.
Returns
the focal length.
Definition at line 98 of file disparity_map_converter.hpp.
template<typename PointT > pcl::PointCloud< pcl::RGB >::Ptr pcl::DisparityMapConverter< PointT >::getImage ()
Get the image, that is used for coloring of the output cloud.
Returns
the image.
Definition at line 155 of file disparity_map_converter.hpp.
template<typename PointT > float pcl::DisparityMapConverter< PointT >::getImageCenterX () const inline
Get x-coordinate of the image center.
Returns
x-coordinate of the image center.
Definition at line 74 of file disparity_map_converter.hpp.
template<typename PointT > float pcl::DisparityMapConverter< PointT >::getImageCenterY () const inline
Get y-coordinate of the image center.
Returns
y-coordinate of the image center.
Definition at line 86 of file disparity_map_converter.hpp.
template<typename PointT > bool pcl::DisparityMapConverter< PointT >::loadDisparityMap (const std::string & file_name)
Load the disparity map.
Parameters
[in] file_name the name of the disparity map file.
Returns
"true" if the disparity map was successfully loaded; "false" otherwise
Definition at line 163 of file disparity_map_converter.hpp.
template<typename PointT > bool pcl::DisparityMapConverter< PointT >::loadDisparityMap (const std::string & file_name, const size_t width, const size_t height)
Load the disparity map and initialize it's size.
Parameters
[in] file_name the name of the disparity map file.
[in] width width of the disparity map.
[in] height height of the disparity map.
Returns
"true" if the disparity map was successfully loaded; "false" otherwise
Definition at line 195 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setBaseline (const float baseline) inline
Set baseline.
Parameters
[in] baseline baseline.
Definition at line 104 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setDisparityMap (const std::vector< float > & disparity_map)
Set the disparity map.
Parameters
[in] disparity_map the disparity map.
Definition at line 207 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setDisparityMap (const std::vector< float > & disparity_map, const size_t width, const size_t height)
Set the disparity map and initialize it's size.
Parameters
[in] disparity_map the disparity map.
[in] width width of the disparity map.
[in] height height of the disparity map.
Returns
"true" if the disparity map was successfully loaded; "false" otherwise
Definition at line 214 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setDisparityThresholdMax (const float disparity_threshold_max) inline
Set max disparity threshold.
Parameters
[in] disparity_threshold_max max disparity threshold.
Definition at line 129 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setDisparityThresholdMin (const float disparity_threshold_min) inline
Set min disparity threshold.
Parameters
[in] disparity_threshold_min min disparity threshold.
Definition at line 116 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setFocalLength (const float focal_length) inline
Set focal length.
Parameters
[in] focal_length the focal length.
Definition at line 92 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setImage (const pcl::PointCloud< pcl::RGB >::ConstPtr & image)
Set an image, that will be used for coloring of the output cloud.
Parameters
[in] image the image.
Definition at line 142 of file disparity_map_converter.hpp.
References pcl::PointCloud< T >::width.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setImageCenterX (const float center_x) inline
Set x-coordinate of the image center.
Parameters
[in] center_x x-coordinate of the image center.
Definition at line 68 of file disparity_map_converter.hpp.
template<typename PointT > void pcl::DisparityMapConverter< PointT >::setImageCenterY (const float center_y) inline
Set y-coordinate of the image center.
Parameters
[in] center_y y-coordinate of the image center.
Definition at line 80 of file disparity_map_converter.hpp.
template<typename PointT > pcl::PointXYZ pcl::DisparityMapConverter< PointT >::translateCoordinates (size_t row, size_t column, float disparity) const protected
Translate point from image coordinates and disparity to 3D-coordinates.
Parameters
[in] row
[in] column
[in] disparity
Returns
the 3D point, that corresponds to the input parametres and the camera calibration.
Definition at line 290 of file disparity_map_converter.hpp.
Member Data Documentation
template<typename PointT> float pcl::DisparityMapConverter< PointT >::baseline_ protected
Baseline.
Definition at line 233 of file disparity_map_converter.h.
template<typename PointT> float pcl::DisparityMapConverter< PointT >::center_x_ protected
X-coordinate of the image center.
Definition at line 227 of file disparity_map_converter.h.
template<typename PointT> float pcl::DisparityMapConverter< PointT >::center_y_ protected
Y-coordinate of the image center.
Definition at line 229 of file disparity_map_converter.h.
template<typename PointT> std::vector<float> pcl::DisparityMapConverter< PointT >::disparity_map_ protected
Vector for the disparity map.
Definition at line 241 of file disparity_map_converter.h.
template<typename PointT> size_t pcl::DisparityMapConverter< PointT >::disparity_map_height_ protected
Y-size of the disparity map.
Definition at line 245 of file disparity_map_converter.h.
template<typename PointT> size_t pcl::DisparityMapConverter< PointT >::disparity_map_width_ protected
X-size of the disparity map.
Definition at line 243 of file disparity_map_converter.h.
template<typename PointT> float pcl::DisparityMapConverter< PointT >::disparity_threshold_max_ protected
Definition at line 249 of file disparity_map_converter.h.
template<typename PointT> float pcl::DisparityMapConverter< PointT >::disparity_threshold_min_ protected
Thresholds of the disparity.
Definition at line 248 of file disparity_map_converter.h.
template<typename PointT> float pcl::DisparityMapConverter< PointT >::focal_length_ protected
Focal length.
Definition at line 231 of file disparity_map_converter.h.
template<typename PointT> pcl::PointCloud<pcl::RGB>::ConstPtr pcl::DisparityMapConverter< PointT >::image_ protected
Color image of the scene.
Definition at line 238 of file disparity_map_converter.h.
template<typename PointT> bool pcl::DisparityMapConverter< PointT >::is_color_ protected
Is color image is set.
Definition at line 236 of file disparity_map_converter.h.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/stereo/include/pcl/stereo/disparity_map_converter.h
/home/travis/build/PointCloudLibrary/pcl/stereo/include/pcl/stereo/impl/disparity_map_converter.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:49