Point Cloud Library (PCL): pcl::DecisionTree< NodeType > Class Template Reference
pcl::DecisionTree< NodeType > Class Template Reference
Class representing a decision tree.
#include <pcl/ml/dt/decision_tree.h>
Public Member Functions
DecisionTree ()
Constructor.
virtual ~DecisionTree ()
Destructor.
void setRoot (const NodeType &root)
Sets the root node of the tree.
NodeType & getRoot ()
Returns the root node of the tree.
void serialize (::std::ostream &stream) const
Serializes the decision tree.
void deserialize (::std::istream &stream)
Deserializes the decision tree.
Detailed Description
template<class NodeType>
class pcl::DecisionTree< NodeType >
Class representing a decision tree.
Definition at line 51 of file decision_tree.h.
Constructor & Destructor Documentation
template<class NodeType> pcl::DecisionTree< NodeType >::DecisionTree () inline
Constructor.
Definition at line 57 of file decision_tree.h.
template<class NodeType> virtual pcl::DecisionTree< NodeType >::~DecisionTree () inline virtual
Destructor.
Definition at line 60 of file decision_tree.h.
Member Function Documentation
template<class NodeType> void pcl::DecisionTree< NodeType >::deserialize (::std::istream & stream) inline
Deserializes the decision tree.
Parameters
[in] stream The source for the deserialization.
Definition at line 90 of file decision_tree.h.
template<class NodeType> NodeType& pcl::DecisionTree< NodeType >::getRoot () inline
Returns the root node of the tree.
Definition at line 73 of file decision_tree.h.
Referenced by pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluate(), pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluateAndAdd(), pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::getNodes(), and pcl::DecisionTreeTrainer< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::train().
template<class NodeType> void pcl::DecisionTree< NodeType >::serialize (::std::ostream & stream) const inline
Serializes the decision tree.
Parameters
[out] stream The destination for the serialization.
Definition at line 82 of file decision_tree.h.
template<class NodeType> void pcl::DecisionTree< NodeType >::setRoot (const NodeType & root) inline
Sets the root node of the tree.
Parameters
[in] root The root node.
Definition at line 66 of file decision_tree.h.
Referenced by pcl::DecisionTreeTrainer< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::train().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/ml/include/pcl/ml/dt/decision_tree.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:32