Point Cloud Library (PCL): pcl::MomentInvariantsEstimation< PointInT, PointOutT > Class Template Reference
pcl::MomentInvariantsEstimation< PointInT, PointOutT > Class Template Reference
Module features
MomentInvariantsEstimation estimates the 3 moment invariants (j1, j2, j3) at each 3D point.
#include <pcl/features/moment_invariants.h>
Public Types
typedef boost::shared_ptr
< MomentInvariantsEstimation
< PointInT, PointOutT > > Ptr
typedef boost::shared_ptr
< const
MomentInvariantsEstimation
< PointInT, PointOutT > > ConstPtr
typedef Feature< PointInT,
PointOutT >::PointCloudOut PointCloudOut
Public Types inherited from pcl::Feature< PointInT, PointOutT >
typedef PCLBase< PointInT > BaseClass
typedef boost::shared_ptr
< Feature< PointInT, PointOutT > > Ptr
typedef boost::shared_ptr
< const Feature< PointInT,
PointOutT > > ConstPtr
typedef pcl::search::Search
< PointInT > KdTree
typedef pcl::search::Search
< PointInT >::Ptr KdTreePtr
typedef pcl::PointCloud< PointInT > PointCloudIn
typedef PointCloudIn::Ptr PointCloudInPtr
typedef PointCloudIn::ConstPtr PointCloudInConstPtr
typedef pcl::PointCloud
< PointOutT > PointCloudOut
typedef boost::function< int(size_t,
double, std::vector< int >
&, std::vector< float > &)> SearchMethod
typedef boost::function< int(const
PointCloudIn &cloud, size_t
index, double, std::vector
< int > &, std::vector< float > &)> SearchMethodSurface
Public Types inherited from pcl::PCLBase< PointInT >
typedef pcl::PointCloud< PointInT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Public Member Functions
MomentInvariantsEstimation ()
Empty constructor.
void computePointMomentInvariants (const pcl::PointCloud< PointInT > &cloud, const std::vector< int > &indices, float &j1, float &j2, float &j3)
Compute the 3 moment invariants (j1, j2, j3) for a given set of points, using their indices.
void computePointMomentInvariants (const pcl::PointCloud< PointInT > &cloud, float &j1, float &j2, float &j3)
Compute the 3 moment invariants (j1, j2, j3) for a given set of points, using their indices.
Public Member Functions inherited from pcl::Feature< PointInT, PointOutT >
Feature ()
Empty constructor.
virtual ~Feature ()
Empty destructor.
void setSearchSurface (const PointCloudInConstPtr &cloud)
Provide a pointer to a dataset to add additional information to estimate the features for every point in the input dataset.
PointCloudInConstPtr getSearchSurface () const
Get a pointer to the surface point cloud dataset.
void setSearchMethod (const KdTreePtr &tree)
Provide a pointer to the search object.
KdTreePtr getSearchMethod () const
Get a pointer to the search method used.
double getSearchParameter () const
Get the internal search parameter.
void setKSearch (int k)
Set the number of k nearest neighbors to use for the feature estimation.
int getKSearch () const
get the number of k nearest neighbors used for the feature estimation.
void setRadiusSearch (double radius)
Set the sphere radius that is to be used for determining the nearest neighbors used for the feature estimation.
double getRadiusSearch () const
Get the sphere radius used for determining the neighbors.
void compute (PointCloudOut &output)
Base method for feature estimation for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Public Member Functions inherited from pcl::PCLBase< PointInT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (size_t row_start, size_t col_start, size_t nb_rows, size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointInT & operator[] (size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
void computeFeature (PointCloudOut &output)
Estimate moment invariants for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Protected Member Functions inherited from pcl::Feature< PointInT, PointOutT >
const std::string & getClassName () const
Get a string representation of the name of this class.
virtual bool initCompute ()
This method should get called before starting the actual computation.
virtual bool deinitCompute ()
This method should get called after ending the actual computation.
int searchForNeighbors (size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
int searchForNeighbors (const PointCloudIn &cloud, size_t index, double parameter, std::vector< int > &indices, std::vector< float > &distances) const
Search for k-nearest neighbors using the spatial locator from setSearchmethod, and the given surface from setSearchSurface.
Protected Member Functions inherited from pcl::PCLBase< PointInT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::Feature< PointInT, PointOutT >
std::string feature_name_
The feature name.
SearchMethodSurface search_method_surface_
The search method template for points.
PointCloudInConstPtr surface_
An input point cloud describing the surface that is to be used for nearest neighbors estimation.
KdTreePtr tree_
A pointer to the spatial search object.
double search_parameter_
The actual search parameter (from either search_radius_ or k_).
double search_radius_
The nearest neighbors search radius for each point.
int k_
The number of K nearest neighbors to use for each point.
bool fake_surface_
If no surface is given, we use the input PointCloud as the surface.
Protected Attributes inherited from pcl::PCLBase< PointInT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointInT, typename PointOutT>
class pcl::MomentInvariantsEstimation< PointInT, PointOutT >
MomentInvariantsEstimation estimates the 3 moment invariants (j1, j2, j3) at each 3D point.
Note
The code is stateful as we do not expect this class to be multicore parallelized. Please look at NormalEstimationOMP for an example on how to extend this to parallel implementations.
Author
Radu B. Rusu
Definition at line 56 of file moment_invariants.h.
Member Typedef Documentation
template<typename PointInT , typename PointOutT > typedef boost::shared_ptr<const MomentInvariantsEstimation<PointInT, PointOutT> > pcl::MomentInvariantsEstimation< PointInT, PointOutT >::ConstPtr
Definition at line 60 of file moment_invariants.h.
template<typename PointInT , typename PointOutT > typedef Feature<PointInT, PointOutT>::PointCloudOut pcl::MomentInvariantsEstimation< PointInT, PointOutT >::PointCloudOut
Definition at line 69 of file moment_invariants.h.
template<typename PointInT , typename PointOutT > typedef boost::shared_ptr<MomentInvariantsEstimation<PointInT, PointOutT> > pcl::MomentInvariantsEstimation< PointInT, PointOutT >::Ptr
Definition at line 59 of file moment_invariants.h.
Constructor & Destructor Documentation
template<typename PointInT , typename PointOutT > pcl::MomentInvariantsEstimation< PointInT, PointOutT >::MomentInvariantsEstimation () inline
Empty constructor.
Definition at line 72 of file moment_invariants.h.
References pcl::Feature< PointInT, PointOutT >::feature_name_.
Member Function Documentation
template<typename PointInT , typename PointOutT > void pcl::MomentInvariantsEstimation< PointInT, PointOutT >::computeFeature (PointCloudOut & output) protected virtual
Estimate moment invariants for all points given in <setInputCloud (), setIndices ()> using the surface in setSearchSurface () and the spatial locator in setSearchMethod ()
Parameters
[out] output the resultant point cloud model dataset that contains the moment invariants
Implements pcl::Feature< PointInT, PointOutT >.
Definition at line 116 of file moment_invariants.hpp.
References pcl::PointCloud< T >::is_dense, pcl::isFinite(), and pcl::PointCloud< T >::points.
template<typename PointInT , typename PointOutT > void pcl::MomentInvariantsEstimation< PointInT, PointOutT >::computePointMomentInvariants (const pcl::PointCloud< PointInT > & cloud, const std::vector< int > & indices, float & j1, float & j2, float & j3)
Compute the 3 moment invariants (j1, j2, j3) for a given set of points, using their indices.
Parameters
[in] cloud the input point cloud
[in] indices the point cloud indices that need to be used
[out] j1 the resultant first moment invariant
[out] j2 the resultant second moment invariant
[out] j3 the resultant third moment invariant
Definition at line 49 of file moment_invariants.hpp.
References pcl::compute3DCentroid(), and pcl::PointCloud< T >::points.
template<typename PointInT , typename PointOutT > void pcl::MomentInvariantsEstimation< PointInT, PointOutT >::computePointMomentInvariants (const pcl::PointCloud< PointInT > & cloud, float & j1, float & j2, float & j3)
Compute the 3 moment invariants (j1, j2, j3) for a given set of points, using their indices.
Parameters
[in] cloud the input point cloud
[out] j1 the resultant first moment invariant
[out] j2 the resultant second moment invariant
[out] j3 the resultant third moment invariant
Definition at line 83 of file moment_invariants.hpp.
References pcl::compute3DCentroid(), and pcl::PointCloud< T >::points.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/features/include/pcl/features/moment_invariants.h
/home/travis/build/PointCloudLibrary/pcl/features/include/pcl/features/impl/moment_invariants.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:10