Point Cloud Library (PCL): pcl::Filter< PointT > Class Template Reference
pcl::Filter< PointT > Class Template Reference abstract
Module filters
Filter represents the base filter class.
#include <pcl/filters/filter.h>
Public Types
typedef boost::shared_ptr
< Filter< PointT > > Ptr
typedef boost::shared_ptr
< const Filter< PointT > > ConstPtr
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
Public Types inherited from pcl::PCLBase< PointT >
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Public Member Functions
Filter (bool extract_removed_indices=false)
Empty constructor.
virtual ~Filter ()
Empty destructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PointCloud &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (size_t row_start, size_t col_start, size_t nb_rows, size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
virtual void applyFilter (PointCloud &output)=0
Abstract filter method.
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
IndicesPtr removed_indices_
Indices of the points that are removed.
std::string filter_name_
The filter name.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointT>
class pcl::Filter< PointT >
Filter represents the base filter class.
All filters must inherit from this interface.
Author
Radu B. Rusu
Definition at line 84 of file filter.h.
Member Typedef Documentation
template<typename PointT> typedef boost::shared_ptr< const Filter<PointT> > pcl::Filter< PointT >::ConstPtr
Definition at line 91 of file filter.h.
template<typename PointT> typedef pcl::PointCloud<PointT> pcl::Filter< PointT >::PointCloud
Definition at line 94 of file filter.h.
template<typename PointT> typedef PointCloud::ConstPtr pcl::Filter< PointT >::PointCloudConstPtr
Definition at line 96 of file filter.h.
template<typename PointT> typedef PointCloud::Ptr pcl::Filter< PointT >::PointCloudPtr
Definition at line 95 of file filter.h.
template<typename PointT> typedef boost::shared_ptr< Filter<PointT> > pcl::Filter< PointT >::Ptr
Definition at line 90 of file filter.h.
Constructor & Destructor Documentation
template<typename PointT> pcl::Filter< PointT >::Filter (bool extract_removed_indices = false) inline
Empty constructor.
Parameters
[in] extract_removed_indices set to true if the filtered data indices should be saved in a separate list. Default: false.
Definition at line 102 of file filter.h.
template<typename PointT> virtual pcl::Filter< PointT >::~Filter () inline virtual
Empty destructor.
Definition at line 110 of file filter.h.
Member Function Documentation
template<typename PointT> virtual void pcl::Filter< PointT >::applyFilter (PointCloud & output) protected pure virtual
Abstract filter method.
The implementation needs to set output.{points, width, height, is_dense}.
Parameters
[out] output the resultant filtered point cloud
Implemented in pcl::ConditionalRemoval< PointT >, pcl::VoxelGridCovariance< PointT >, pcl::VoxelGridCovariance< PointTarget >, pcl::VoxelGrid< PointT >, pcl::VoxelGrid< pcl::PointXYZRGB >, pcl::VoxelGrid< PointTarget >, pcl::VoxelGrid< pcl::PointXYZRGBL >, pcl::ApproximateVoxelGrid< PointT >, pcl::FrustumCulling< PointT >, pcl::ModelOutlierRemoval< PointT >, pcl::PassThrough< PointT >, pcl::PassThrough< PointInT >, pcl::FilterIndices< PointT >, pcl::FilterIndices< PointInT >, pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >, pcl::CropBox< PointT >, pcl::NormalSpaceSampling< PointT, NormalT >, pcl::StatisticalOutlierRemoval< PointT >, pcl::RadiusOutlierRemoval< PointT >, pcl::CovarianceSampling< PointT, PointNT >, pcl::ProjectInliers< PointT >, pcl::SamplingSurfaceNormal< PointT >, pcl::Convolution< PointInT >, pcl::CropHull< PointT >, pcl::UniformSampling< PointT >, pcl::RandomSample< PointT >, pcl::RandomSample< pcl::pcl::PCLPointCloud2 >, pcl::ExtractIndices< PointT >, pcl::ShadowPoints< PointT, NormalT >, pcl::GridMinimum< PointT >, pcl::FastBilateralFilter< PointT >, pcl::MedianFilter< PointT >, pcl::LocalMaximum< PointT >, pcl::FastBilateralFilterOMP< PointT >, pcl::BilateralFilter< PointT >, and pcl::VoxelGridLabel.
Referenced by pcl::Filter< pcl::PointXYZRGBL >::filter().
template<typename PointT> void pcl::Filter< PointT >::filter (PointCloud & output) inline
Calls the filtering method and returns the filtered dataset in output.
Parameters
[out] output the resultant filtered point cloud dataset
Definition at line 132 of file filter.h.
Referenced by pcl::LocalMaximum< PointT >::applyFilterIndices(), pcl::GRSDEstimation< PointInT, PointNT, PointOutT >::computeFeature(), pcl::CrfSegmentation< PointT >::createVoxelGrid(), pcl::SIFTKeypoint< PointInT, PointOutT >::detectKeypoints(), pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::filter(), pcl::FilterIndices< pcl::PCLPointCloud2 >::filter(), pcl::people::GroundBasedPeopleDetectionApp< PointT >::filter(), pcl::kinfuLS::WorldModel< PointT >::getExistingData(), pcl::kinfuLS::WorldModel< PointT >::getWorldAsCubes(), pcl::HypothesisVerification< ModelT, SceneT >::setSceneCloud(), pcl::kinfuLS::WorldModel< PointT >::setSliceAsNans(), and pcl::ism::ImplicitShapeModelEstimation< FeatureSize, PointT, NormalT >::simplifyCloud().
template<typename PointT> const std::string& pcl::Filter< PointT >::getClassName () const inline protected
Get a string representation of the name of this class.
Definition at line 182 of file filter.h.
Referenced by pcl::VoxelGridCovariance< PointTarget >::nearestKSearch(), pcl::VoxelGridCovariance< PointTarget >::radiusSearch(), and pcl::VoxelGridCovariance< PointTarget >::setMinPointPerVoxel().
template<typename PointT> IndicesConstPtr const pcl::Filter< PointT >::getRemovedIndices () const inline
Get the point indices being removed.
Definition at line 114 of file filter.h.
Referenced by pcl::kinfuLS::WorldModel< PointT >::setSliceAsNans().
template<typename PointT> void pcl::Filter< PointT >::getRemovedIndices (PointIndices & pi) inline
Get the point indices being removed.
Parameters
[out] pi the resultant point indices that have been removed
Definition at line 123 of file filter.h.
Member Data Documentation
template<typename PointT> bool pcl::Filter< PointT >::extract_removed_indices_ protected
Set to true if we want to return the indices of the removed points.
Definition at line 169 of file filter.h.
Referenced by pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::FilterIndices().
template<typename PointT> std::string pcl::Filter< PointT >::filter_name_ protected
The filter name.
Definition at line 166 of file filter.h.
Referenced by pcl::ApproximateVoxelGrid< PointT >::ApproximateVoxelGrid(), pcl::ConditionalRemoval< PointT >::ConditionalRemoval(), pcl::CovarianceSampling< PointT, PointNT >::CovarianceSampling(), pcl::CropBox< PointT >::CropBox(), pcl::CropHull< PointT >::CropHull(), pcl::ExtractIndices< PointT >::ExtractIndices(), pcl::FrustumCulling< PointT >::FrustumCulling(), pcl::Filter< pcl::PointXYZRGBL >::getClassName(), pcl::GridMinimum< PointT >::GridMinimum(), pcl::LocalMaximum< PointT >::LocalMaximum(), pcl::ModelOutlierRemoval< PointT >::ModelOutlierRemoval(), pcl::NormalSpaceSampling< PointT, NormalT >::NormalSpaceSampling(), pcl::PassThrough< PointInT >::PassThrough(), pcl::ProjectInliers< PointT >::ProjectInliers(), pcl::RadiusOutlierRemoval< PointT >::RadiusOutlierRemoval(), pcl::RandomSample< pcl::pcl::PCLPointCloud2 >::RandomSample(), pcl::SamplingSurfaceNormal< PointT >::SamplingSurfaceNormal(), pcl::ShadowPoints< PointT, NormalT >::ShadowPoints(), pcl::StatisticalOutlierRemoval< PointT >::StatisticalOutlierRemoval(), pcl::UniformSampling< PointT >::UniformSampling(), pcl::VoxelGrid< pcl::PointXYZRGBL >::VoxelGrid(), and pcl::VoxelGridCovariance< PointTarget >::VoxelGridCovariance().
template<typename PointT> IndicesPtr pcl::Filter< PointT >::removed_indices_ protected
Indices of the points that are removed.
Definition at line 163 of file filter.h.
Referenced by pcl::Filter< pcl::PointXYZRGBL >::getRemovedIndices().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/filter.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:19