Point Cloud Library (PCL): pcl::octree::BufferedBranchNode< ContainerT > Class Template Reference
pcl::octree::BufferedBranchNode< ContainerT > Class Template Reference
#include <pcl/octree/octree2buf_base.h>
Public Member Functions
BufferedBranchNode ()
Empty constructor.
BufferedBranchNode (const BufferedBranchNode &source)
Copy constructor.
BufferedBranchNode & operator= (const BufferedBranchNode &source_arg)
Copy operator.
virtual ~BufferedBranchNode ()
Empty constructor.
virtual BufferedBranchNode * deepCopy () const
Method to perform a deep copy of the octree.
OctreeNode * getChildPtr (unsigned char buffer_arg, unsigned char index_arg) const
Get child pointer in current branch node.
void setChildPtr (unsigned char buffer_arg, unsigned char index_arg, OctreeNode *newNode_arg)
Set child pointer in current branch node.
bool hasChild (unsigned char buffer_arg, unsigned char index_arg) const
Check if branch is pointing to a particular child node.
virtual node_type_t getNodeType () const
Get the type of octree node.
void reset ()
Reset branch node container for every branch buffer.
const ContainerT * operator-> () const
Get const pointer to container.
ContainerT * operator-> ()
Get pointer to container.
const ContainerT & operator* () const
Get const reference to container.
ContainerT & operator* ()
Get reference to container.
const ContainerT & getContainer () const
Get const reference to container.
ContainerT & getContainer ()
Get reference to container.
const ContainerT * getContainerPtr () const
Get const pointer to container.
ContainerT * getContainerPtr ()
Get pointer to container.
Public Member Functions inherited from pcl::octree::OctreeNode
OctreeNode ()
virtual ~OctreeNode ()
Protected Attributes
ContainerT container_
OctreeNode * child_node_array_ [2][8]
Detailed Description
template<typename ContainerT>
class pcl::octree::BufferedBranchNode< ContainerT >
Definition at line 56 of file octree2buf_base.h.
Constructor & Destructor Documentation
template<typename ContainerT > pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode () inline
Empty constructor.
Definition at line 61 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::reset().
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::deepCopy().
template<typename ContainerT > pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode (const BufferedBranchNode< ContainerT > & source) inline
Copy constructor.
Definition at line 67 of file octree2buf_base.h.
template<typename ContainerT > virtual pcl::octree::BufferedBranchNode< ContainerT >::~BufferedBranchNode () inline virtual
Empty constructor.
Definition at line 91 of file octree2buf_base.h.
Member Function Documentation
template<typename ContainerT > virtual BufferedBranchNode* pcl::octree::BufferedBranchNode< ContainerT >::deepCopy () const inline virtual
Method to perform a deep copy of the octree.
Implements pcl::octree::OctreeNode.
Definition at line 97 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode().
template<typename ContainerT > OctreeNode* pcl::octree::BufferedBranchNode< ContainerT >::getChildPtr (unsigned char buffer_arg, unsigned char index_arg) const inline
Get child pointer in current branch node.
Parameters
buffer_arg buffer selector
index_arg index of child in node
Returns
pointer to child node
Definition at line 108 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::branchHasChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranch(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deserializeTreeRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::findLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::getBranchBitPattern(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::getBranchChildPtr(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::getBranchXORBitPattern(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::serializeTreeRecursive(), and pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::treeCleanUpRecursive().
template<typename ContainerT > const ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::getContainer () const inline
Get const reference to container.
Definition at line 179 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::getContainer () inline
Get reference to container.
Definition at line 186 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > const ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::getContainerPtr () const inline
Get const pointer to container.
Definition at line 193 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::getContainerPtr () inline
Get pointer to container.
Definition at line 200 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > virtual node_type_t pcl::octree::BufferedBranchNode< ContainerT >::getNodeType () const inline virtual
Get the type of octree node.
Returns LEAVE_NODE type
Implements pcl::octree::OctreeNode.
Definition at line 138 of file octree2buf_base.h.
References pcl::octree::BRANCH_NODE.
template<typename ContainerT > bool pcl::octree::BufferedBranchNode< ContainerT >::hasChild (unsigned char buffer_arg, unsigned char index_arg) const inline
Check if branch is pointing to a particular child node.
Parameters
buffer_arg buffer selector
index_arg index of child in node
Returns
"true" if pointer to child node exists; "false" otherwise
Definition at line 131 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deserializeTreeRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::findLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::serializeTreeRecursive(), and pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::treeCleanUpRecursive().
template<typename ContainerT > const ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::operator* () const inline
Get const reference to container.
Definition at line 165 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT& pcl::octree::BufferedBranchNode< ContainerT >::operator* () inline
Get reference to container.
Definition at line 172 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > const ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::operator-> () const inline
Get const pointer to container.
Definition at line 151 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > ContainerT* pcl::octree::BufferedBranchNode< ContainerT >::operator-> () inline
Get pointer to container.
Definition at line 158 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::container_.
template<typename ContainerT > BufferedBranchNode& pcl::octree::BufferedBranchNode< ContainerT >::operator= (const BufferedBranchNode< ContainerT > & source_arg) inline
Copy operator.
Definition at line 74 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_, and pcl::octree::OctreeNode::deepCopy().
template<typename ContainerT > void pcl::octree::BufferedBranchNode< ContainerT >::reset () inline
Reset branch node container for every branch buffer.
Definition at line 144 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::BufferedBranchNode().
template<typename ContainerT > void pcl::octree::BufferedBranchNode< ContainerT >::setChildPtr (unsigned char buffer_arg, unsigned char index_arg, OctreeNode * newNode_arg) inline
Set child pointer in current branch node.
Parameters
buffer_arg buffer selector
index_arg index of child in node
newNode_arg pointer to new child node
Definition at line 119 of file octree2buf_base.h.
References pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_.
Referenced by pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::createLeafRecursive(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranch(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deleteBranchChild(), pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::deserializeTreeRecursive(), and pcl::octree::Octree2BufBase< LeafContainerT, BranchContainerT >::setBranchChildPtr().
Member Data Documentation
template<typename ContainerT > OctreeNode* pcl::octree::BufferedBranchNode< ContainerT >::child_node_array_[2][8] protected
Definition at line 208 of file octree2buf_base.h.
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::getChildPtr(), pcl::octree::BufferedBranchNode< ContainerT >::hasChild(), pcl::octree::BufferedBranchNode< ContainerT >::operator=(), pcl::octree::BufferedBranchNode< ContainerT >::reset(), and pcl::octree::BufferedBranchNode< ContainerT >::setChildPtr().
template<typename ContainerT > ContainerT pcl::octree::BufferedBranchNode< ContainerT >::container_ protected
Definition at line 206 of file octree2buf_base.h.
Referenced by pcl::octree::BufferedBranchNode< ContainerT >::getContainer(), pcl::octree::BufferedBranchNode< ContainerT >::getContainerPtr(), pcl::octree::BufferedBranchNode< ContainerT >::operator*(), and pcl::octree::BufferedBranchNode< ContainerT >::operator->().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/octree/include/pcl/octree/octree2buf_base.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:09