Point Cloud Library (PCL): pcl::gpu::DeviceArray< T > Class Template Reference
pcl::gpu::DeviceArray< T > Class Template Reference
DeviceArray class
#include </home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/device_array.h>
Public Types
enum { elem_size = sizeof(T) }
Element size.
typedef T type
Element type.
Public Member Functions
DeviceArray ()
Empty constructor.
DeviceArray (size_t size)
Allocates internal buffer in GPU memory.
DeviceArray (T *ptr, size_t size)
Initializes with user allocated buffer.
DeviceArray (const DeviceArray &other)
Copy constructor.
DeviceArray & operator= (const DeviceArray &other)
Assignment operator.
void create (size_t size)
Allocates internal buffer in GPU memory.
void release ()
Decrements reference counter and releases internal buffer if needed.
void copyTo (DeviceArray &other) const
Performs data copying.
void upload (const T *host_ptr, size_t size)
Uploads data to internal buffer in GPU memory.
void download (T *host_ptr) const
Downloads data from internal buffer to CPU memory.
template<class A >
void upload (const std::vector< T, A > &data)
Uploads data to internal buffer in GPU memory.
template<typename A >
void download (std::vector< T, A > &data) const
Downloads data from internal buffer to CPU memory.
void swap (DeviceArray &other_arg)
Performs swap of data pointed with another device array.
T * ptr ()
Returns pointer for internal buffer in GPU memory.
const T * ptr () const
Returns const pointer for internal buffer in GPU memory.
operator T * ()
Returns pointer for internal buffer in GPU memory.
operator const T * () const
Returns const pointer for internal buffer in GPU memory.
size_t size () const
Returns size in elements.
Public Member Functions inherited from pcl::gpu::DeviceMemory
DeviceMemory ()
Empty constructor.
~DeviceMemory ()
Destructor.
DeviceMemory (size_t sizeBytes_arg)
Allocates internal buffer in GPU memory.
DeviceMemory (void *ptr_arg, size_t sizeBytes_arg)
Initializes with user allocated buffer.
DeviceMemory (const DeviceMemory &other_arg)
Copy constructor.
DeviceMemory & operator= (const DeviceMemory &other_arg)
Assignment operator.
void create (size_t sizeBytes_arg)
Allocates internal buffer in GPU memory.
void release ()
Decrements reference counter and releases internal buffer if needed.
void copyTo (DeviceMemory &other) const
Performs data copying.
void upload (const void *host_ptr_arg, size_t sizeBytes_arg)
Uploads data to internal buffer in GPU memory.
void download (void *host_ptr_arg) const
Downloads data from internal buffer to CPU memory.
void swap (DeviceMemory &other_arg)
Performs swap of data pointed with another device memory.
template<class T >
T * ptr ()
Returns pointer for internal buffer in GPU memory.
template<class T >
const T * ptr () const
Returns constant pointer for internal buffer in GPU memory.
template<class U >
operator PtrSz< U > () const
Conversion to PtrSz for passing to kernel functions.
bool empty () const
Returns true if unallocated otherwise false.
size_t sizeBytes () const
Detailed Description
template<class T>
class pcl::gpu::DeviceArray< T >
DeviceArray class
Note
Typed container for GPU memory with reference counting.
Author
Anatoly Baksheev
Definition at line 57 of file device_array.h.
Member Typedef Documentation
template<class T> typedef T pcl::gpu::DeviceArray< T >::type
Element type.
Definition at line 61 of file device_array.h.
Member Enumeration Documentation
template<class T> anonymous enum
Element size.
Enumerator
elem_size
Definition at line 64 of file device_array.h.
Constructor & Destructor Documentation
template<class T > pcl::gpu::DeviceArray< T >::DeviceArray () inline
Empty constructor.
Definition at line 43 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray< T >::DeviceArray (size_t size) inline
Allocates internal buffer in GPU memory.
Parameters
size number of elements to allocate
Definition at line 44 of file device_array.hpp.
template<class T> pcl::gpu::DeviceArray< T >::DeviceArray (T * ptr, size_t size) inline
Initializes with user allocated buffer.
Reference counting is disabled in this case.
Parameters
ptr pointer to buffer
size elements number
Definition at line 45 of file device_array.hpp.
template<class T> pcl::gpu::DeviceArray< T >::DeviceArray (const DeviceArray< T > & other) inline
Copy constructor.
Just increments reference counter.
Definition at line 46 of file device_array.hpp.
Member Function Documentation
template<class T > void pcl::gpu::DeviceArray< T >::copyTo (DeviceArray< T > & other) const inline
Performs data copying.
If destination size differs it will be reallocated.
Parameters
other destination container
Definition at line 55 of file device_array.hpp.
References pcl::gpu::DeviceMemory::copyTo().
template<class T > void pcl::gpu::DeviceArray< T >::create (size_t size) inline
Allocates internal buffer in GPU memory.
If internal buffer was created before the function recreates it with new size. If new and old sizes are equal it does nothing.
Parameters
size elements number
Definition at line 50 of file device_array.hpp.
References pcl::gpu::DeviceMemory::create().
Referenced by pcl::gpu::copyFieldsEx(), pcl::gpu::NeighborIndices::create(), and pcl::gpu::extractEuclideanClusters().
template<class T> void pcl::gpu::DeviceArray< T >::download (T * host_ptr) const inline
Downloads data from internal buffer to CPU memory.
Parameters
host_ptr pointer to buffer to download
Definition at line 59 of file device_array.hpp.
References pcl::gpu::DeviceMemory::download().
Referenced by pcl::gpu::kinfuLS::StandaloneMarchingCubes< PointT >::convertTrianglesToMesh(), pcl::gpu::extractEuclideanClusters(), and pcl::gpu::extractLabeledEuclideanClusters().
template<class T> template<class A > void pcl::gpu::DeviceArray< T >::download (std::vector< T, A > & data) const inline
Downloads data from internal buffer to CPU memory.
Parameters
data host vector to download to
Definition at line 72 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray< T >::operator const T * () const inline
Returns const pointer for internal buffer in GPU memory.
Definition at line 65 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray< T >::operator T * () inline
Returns pointer for internal buffer in GPU memory.
Definition at line 64 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray< T > & pcl::gpu::DeviceArray< T >::operator= (const DeviceArray< T > & other) inline
Assignment operator.
Just increments reference counter.
Definition at line 47 of file device_array.hpp.
References pcl::gpu::DeviceMemory::operator=().
template<class T > T * pcl::gpu::DeviceArray< T >::ptr () inline
Returns pointer for internal buffer in GPU memory.
Definition at line 68 of file device_array.hpp.
Referenced by pcl::gpu::copyFieldsEx(), pcl::gpu::AsyncCopy< T >::download(), pcl::gpu::extractEuclideanClusters(), pcl::gpu::NeighborIndices::operator PtrStep< int >(), pcl::gpu::TextureBinder::TextureBinder(), and pcl::gpu::AsyncCopy< T >::upload().
template<class T > const T * pcl::gpu::DeviceArray< T >::ptr () const inline
Returns const pointer for internal buffer in GPU memory.
Definition at line 69 of file device_array.hpp.
template<class T > void pcl::gpu::DeviceArray< T >::release () inline
Decrements reference counter and releases internal buffer if needed.
Definition at line 52 of file device_array.hpp.
References pcl::gpu::DeviceMemory::release().
template<class T > size_t pcl::gpu::DeviceArray< T >::size () const inline
Returns size in elements.
Definition at line 66 of file device_array.hpp.
Referenced by pcl::gpu::kinfuLS::StandaloneMarchingCubes< PointT >::convertTrianglesToMesh(), pcl::gpu::copyFieldsEx(), pcl::gpu::NeighborIndices::neighboors_size(), pcl::gpu::AsyncCopy< T >::upload(), and pcl::gpu::NeighborIndices::validate().
template<class T > void pcl::gpu::DeviceArray< T >::swap (DeviceArray< T > & other_arg)
Performs swap of data pointed with another device array.
Parameters
other_arg device array to swap with
Definition at line 62 of file device_array.hpp.
References pcl::gpu::DeviceMemory::swap().
template<class T> void pcl::gpu::DeviceArray< T >::upload (const T * host_ptr, size_t size) inline
Uploads data to internal buffer in GPU memory.
It calls create() inside to ensure that intenal buffer size is enough.
Parameters
host_ptr pointer to buffer to upload
size elements number
Definition at line 57 of file device_array.hpp.
References pcl::gpu::DeviceMemory::upload().
Referenced by pcl::gpu::extractEuclideanClusters(), and pcl::gpu::extractLabeledEuclideanClusters().
template<class T> template<class A > void pcl::gpu::DeviceArray< T >::upload (const std::vector< T, A > & data) inline
Uploads data to internal buffer in GPU memory.
It calls create() inside to ensure that intenal buffer size is enough.
Parameters
data host vector to upload from
Definition at line 71 of file device_array.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/device_array.h
/home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/impl/device_array.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:00