Point Cloud Library (PCL): pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT > Class Template Reference
pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT > Class Template Reference
Module octree
Octree pointcloud search class
#include <pcl/octree/octree_search.h>
Classes
class prioBranchQueueEntry
Priority queue entry for branch nodes
class prioPointQueueEntry
Priority queue entry for point candidates
Public Types
typedef boost::shared_ptr
< std::vector< int > > IndicesPtr
typedef boost::shared_ptr
< const std::vector< int > > IndicesConstPtr
typedef pcl::PointCloud< PointT > PointCloud
typedef boost::shared_ptr
< PointCloud > PointCloudPtr
typedef boost::shared_ptr
< const PointCloud > PointCloudConstPtr
typedef boost::shared_ptr
< OctreePointCloudSearch
< PointT, LeafContainerT,
BranchContainerT > > Ptr
typedef boost::shared_ptr
< const OctreePointCloudSearch
< PointT, LeafContainerT,
BranchContainerT > > ConstPtr
typedef std::vector< PointT,
Eigen::aligned_allocator
< PointT > > AlignedPointTVector
typedef OctreePointCloud
< PointT, LeafContainerT,
BranchContainerT > OctreeT
typedef OctreeT::LeafNode LeafNode
typedef OctreeT::BranchNode BranchNode
Public Types inherited from pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >
typedef OctreeBase
< LeafContainerT,
BranchContainerT > Base
typedef OctreeBase
< LeafContainerT,
BranchContainerT >::LeafNode LeafNode
typedef OctreeBase
< LeafContainerT,
BranchContainerT >::BranchNode BranchNode
typedef boost::shared_ptr
< std::vector< int > > IndicesPtr
typedef boost::shared_ptr
< const std::vector< int > > IndicesConstPtr
typedef pcl::PointCloud< PointT > PointCloud
typedef boost::shared_ptr
< PointCloud > PointCloudPtr
typedef boost::shared_ptr
< const PointCloud > PointCloudConstPtr
typedef OctreePointCloud
< PointT, LeafContainerT,
BranchContainerT, OctreeBase
< LeafContainerT > > SingleBuffer
typedef boost::shared_ptr
< OctreePointCloud< PointT,
LeafContainerT,
BranchContainerT, OctreeBase
< LeafContainerT,
BranchContainerT > > > Ptr
typedef boost::shared_ptr
< const OctreePointCloud
< PointT, LeafContainerT,
BranchContainerT, OctreeBase
< LeafContainerT,
BranchContainerT > > > ConstPtr
typedef std::vector< PointT,
Eigen::aligned_allocator
< PointT > > AlignedPointTVector
typedef std::vector< PointXYZ,
Eigen::aligned_allocator
< PointXYZ > > AlignedPointXYZVector
Public Types inherited from pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >
typedef OctreeBase
< LeafContainerT,
BranchContainerT > OctreeT
typedef OctreeBranchNode
< BranchContainerT > BranchNode
typedef OctreeLeafNode
< LeafContainerT > LeafNode
typedef BranchContainerT BranchContainer
typedef LeafContainerT LeafContainer
typedef
OctreeDepthFirstIterator
< OctreeT > Iterator
typedef const
OctreeDepthFirstIterator
< OctreeT > ConstIterator
typedef
OctreeLeafNodeDepthFirstIterator
< OctreeT > LeafNodeIterator
typedef const
OctreeLeafNodeDepthFirstIterator
< OctreeT > ConstLeafNodeIterator
typedef
OctreeLeafNodeDepthFirstIterator
< OctreeT > LeafNodeDepthFirstIterator
typedef const
OctreeLeafNodeDepthFirstIterator
< OctreeT > ConstLeafNodeDepthFirstIterator
typedef
OctreeDepthFirstIterator
< OctreeT > DepthFirstIterator
typedef const
OctreeDepthFirstIterator
< OctreeT > ConstDepthFirstIterator
typedef
OctreeBreadthFirstIterator
< OctreeT > BreadthFirstIterator
typedef const
OctreeBreadthFirstIterator
< OctreeT > ConstBreadthFirstIterator
typedef
OctreeFixedDepthIterator
< OctreeT > FixedDepthIterator
typedef const
OctreeFixedDepthIterator
< OctreeT > ConstFixedDepthIterator
typedef
OctreeLeafNodeBreadthFirstIterator
< OctreeT > LeafNodeBreadthFirstIterator
typedef const
OctreeLeafNodeBreadthFirstIterator
< OctreeT > ConstLeafNodeBreadthFirstIterator
Public Member Functions
OctreePointCloudSearch (const double resolution)
Constructor.
virtual ~OctreePointCloudSearch ()
Empty class destructor.
bool voxelSearch (const PointT &point, std::vector< int > &point_idx_data)
Search for neighbors within a voxel at given point.
bool voxelSearch (const int index, std::vector< int > &point_idx_data)
Search for neighbors within a voxel at given point referenced by a point index.
int nearestKSearch (const PointCloud &cloud, int index, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances)
Search for k-nearest neighbors at the query point.
int nearestKSearch (const PointT &p_q, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances)
Search for k-nearest neighbors at given query point.
int nearestKSearch (int index, int k, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances)
Search for k-nearest neighbors at query point.
void approxNearestSearch (const PointCloud &cloud, int query_index, int &result_index, float &sqr_distance)
Search for approx.
void approxNearestSearch (const PointT &p_q, int &result_index, float &sqr_distance)
Search for approx.
void approxNearestSearch (int query_index, int &result_index, float &sqr_distance)
Search for approx.
int radiusSearch (const PointCloud &cloud, int index, double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0)
Search for all neighbors of query point that are within a given radius.
int radiusSearch (const PointT &p_q, const double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0) const
Search for all neighbors of query point that are within a given radius.
int radiusSearch (int index, const double radius, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn=0) const
Search for all neighbors of query point that are within a given radius.
int getIntersectedVoxelCenters (Eigen::Vector3f origin, Eigen::Vector3f direction, AlignedPointTVector &voxel_center_list, int max_voxel_count=0) const
Get a PointT vector of centers of all voxels that intersected by a ray (origin, direction).
int getIntersectedVoxelIndices (Eigen::Vector3f origin, Eigen::Vector3f direction, std::vector< int > &k_indices, int max_voxel_count=0) const
Get indices of all voxels that are intersected by a ray (origin, direction).
int boxSearch (const Eigen::Vector3f &min_pt, const Eigen::Vector3f &max_pt, std::vector< int > &k_indices) const
Search for points within rectangular search area Points exactly on the edges of the search rectangle are included.
Public Member Functions inherited from pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >
OctreePointCloud (const double resolution_arg)
Octree pointcloud constructor.
virtual ~OctreePointCloud ()
Empty deconstructor.
void setInputCloud (const PointCloudConstPtr &cloud_arg, const IndicesConstPtr &indices_arg=IndicesConstPtr())
Provide a pointer to the input data set.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
PointCloudConstPtr getInputCloud () const
Get a pointer to the input point cloud dataset.
void setEpsilon (double eps)
Set the search epsilon precision (error bound) for nearest neighbors searches.
double getEpsilon () const
Get the search epsilon precision (error bound) for nearest neighbors searches.
void setResolution (double resolution_arg)
Set/change the octree voxel resolution.
double getResolution () const
Get octree voxel resolution.
unsigned int getTreeDepth () const
Get the maximum depth of the octree.
void addPointsFromInputCloud ()
Add points from input point cloud to octree.
void addPointFromCloud (const int point_idx_arg, IndicesPtr indices_arg)
Add point at given index from input point cloud to octree.
void addPointToCloud (const PointT &point_arg, PointCloudPtr cloud_arg)
Add point simultaneously to octree and input point cloud.
void addPointToCloud (const PointT &point_arg, PointCloudPtr cloud_arg, IndicesPtr indices_arg)
Add point simultaneously to octree and input point cloud.
bool isVoxelOccupiedAtPoint (const PointT &point_arg) const
Check if voxel at given point exist.
bool isVoxelOccupiedAtPoint (const double point_x_arg, const double point_y_arg, const double point_z_arg) const
Check if voxel at given point coordinates exist.
bool isVoxelOccupiedAtPoint (const int &point_idx_arg) const
Check if voxel at given point from input cloud exist.
void deleteTree ()
Delete the octree structure and its leaf nodes.
int getOccupiedVoxelCenters (AlignedPointTVector &voxel_center_list_arg) const
Get a PointT vector of centers of all occupied voxels.
int getApproxIntersectedVoxelCentersBySegment (const Eigen::Vector3f &origin, const Eigen::Vector3f &end, AlignedPointTVector &voxel_center_list, float precision=0.2)
Get a PointT vector of centers of voxels intersected by a line segment.
void deleteVoxelAtPoint (const PointT &point_arg)
Delete leaf node / voxel at given point.
void deleteVoxelAtPoint (const int &point_idx_arg)
Delete leaf node / voxel at given point from input cloud.
void defineBoundingBox ()
Investigate dimensions of pointcloud data set and define corresponding bounding box for octree.
void defineBoundingBox (const double min_x_arg, const double min_y_arg, const double min_z_arg, const double max_x_arg, const double max_y_arg, const double max_z_arg)
Define bounding box for octree.
void defineBoundingBox (const double max_x_arg, const double max_y_arg, const double max_z_arg)
Define bounding box for octree.
void defineBoundingBox (const double cubeLen_arg)
Define bounding box cube for octree.
void getBoundingBox (double &min_x_arg, double &min_y_arg, double &min_z_arg, double &max_x_arg, double &max_y_arg, double &max_z_arg) const
Get bounding box for octree.
double getVoxelSquaredDiameter (unsigned int tree_depth_arg) const
Calculates the squared diameter of a voxel at given tree depth.
double getVoxelSquaredDiameter () const
Calculates the squared diameter of a voxel at leaf depth.
double getVoxelSquaredSideLen (unsigned int tree_depth_arg) const
Calculates the squared voxel cube side length at given tree depth.
double getVoxelSquaredSideLen () const
Calculates the squared voxel cube side length at leaf level.
void getVoxelBounds (const OctreeIteratorBase< OctreeBase< LeafContainerT, BranchContainerT > > &iterator, Eigen::Vector3f &min_pt, Eigen::Vector3f &max_pt) const
Generate bounds of the current voxel of an octree iterator.
void enableDynamicDepth (size_t maxObjsPerLeaf)
Enable dynamic octree structure.
Public Member Functions inherited from pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >
Iterator begin (unsigned int max_depth_arg=0u)
const Iterator end ()
LeafNodeIterator leaf_begin (unsigned int max_depth_arg=0u)
const LeafNodeIterator leaf_end ()
LeafNodeDepthFirstIterator leaf_depth_begin (unsigned int max_depth_arg=0u)
const LeafNodeDepthFirstIterator leaf_depth_end ()
DepthFirstIterator depth_begin (unsigned int max_depth_arg=0u)
const DepthFirstIterator depth_end ()
BreadthFirstIterator breadth_begin (unsigned int max_depth_arg=0u)
const BreadthFirstIterator breadth_end ()
FixedDepthIterator fixed_depth_begin (unsigned int fixed_depth_arg=0u)
const FixedDepthIterator fixed_depth_end ()
LeafNodeBreadthFirstIterator leaf_breadth_begin (unsigned int max_depth_arg=0u)
const LeafNodeBreadthFirstIterator leaf_breadth_end ()
OctreeBase ()
Empty constructor.
virtual ~OctreeBase ()
Empty deconstructor.
OctreeBase (const OctreeBase &source)
Copy constructor.
OctreeBase & operator= (const OctreeBase &source)
Copy operator.
void setMaxVoxelIndex (unsigned int max_voxel_index_arg)
Set the maximum amount of voxels per dimension.
void setTreeDepth (unsigned int max_depth_arg)
Set the maximum depth of the octree.
unsigned int getTreeDepth () const
Get the maximum depth of the octree.
LeafContainerT * createLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg)
Create new leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
LeafContainerT * findLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg)
Find leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
bool existLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg) const
idx_x_arg for the existence of leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
void removeLeaf (unsigned int idx_x_arg, unsigned int idx_y_arg, unsigned int idx_z_arg)
Remove leaf node at (idx_x_arg, idx_y_arg, idx_z_arg).
std::size_t getLeafCount () const
Return the amount of existing leafs in the octree.
std::size_t getBranchCount () const
Return the amount of existing branch nodes in the octree.
void deleteTree ()
Delete the octree structure and its leaf nodes.
void serializeTree (std::vector< char > &binary_tree_out_arg)
Serialize octree into a binary output vector describing its branch node structure.
void serializeTree (std::vector< char > &binary_tree_out_arg, std::vector< LeafContainerT * > &leaf_container_vector_arg)
Serialize octree into a binary output vector describing its branch node structure and push all LeafContainerT elements stored in the octree to a vector.
void serializeLeafs (std::vector< LeafContainerT * > &leaf_container_vector_arg)
Outputs a vector of all LeafContainerT elements that are stored within the octree leaf nodes.
void deserializeTree (std::vector< char > &binary_tree_input_arg)
Deserialize a binary octree description vector and create a corresponding octree structure.
void deserializeTree (std::vector< char > &binary_tree_input_arg, std::vector< LeafContainerT * > &leaf_container_vector_arg)
Deserialize a binary octree description and create a corresponding octree structure.
Protected Member Functions
float pointSquaredDist (const PointT &point_a, const PointT &point_b) const
Helper function to calculate the squared distance between two points.
void getNeighborsWithinRadiusRecursive (const PointT &point, const double radiusSquared, const BranchNode *node, const OctreeKey &key, unsigned int tree_depth, std::vector< int > &k_indices, std::vector< float > &k_sqr_distances, unsigned int max_nn) const
Recursive search method that explores the octree and finds neighbors within a given radius.
double getKNearestNeighborRecursive (const PointT &point, unsigned int K, const BranchNode *node, const OctreeKey &key, unsigned int tree_depth, const double squared_search_radius, std::vector< prioPointQueueEntry > &point_candidates) const
Recursive search method that explores the octree and finds the K nearest neighbors.
void approxNearestSearchRecursive (const PointT &point, const BranchNode *node, const OctreeKey &key, unsigned int tree_depth, int &result_index, float &sqr_distance)
Recursive search method that explores the octree and finds the approximate nearest neighbor.
int getIntersectedVoxelCentersRecursive (double min_x, double min_y, double min_z, double max_x, double max_y, double max_z, unsigned char a, const OctreeNode *node, const OctreeKey &key, AlignedPointTVector &voxel_center_list, int max_voxel_count) const
Recursively search the tree for all intersected leaf nodes and return a vector of voxel centers.
void boxSearchRecursive (const Eigen::Vector3f &min_pt, const Eigen::Vector3f &max_pt, const BranchNode *node, const OctreeKey &key, unsigned int tree_depth, std::vector< int > &k_indices) const
Recursive search method that explores the octree and finds points within a rectangular search area.
int getIntersectedVoxelIndicesRecursive (double min_x, double min_y, double min_z, double max_x, double max_y, double max_z, unsigned char a, const OctreeNode *node, const OctreeKey &key, std::vector< int > &k_indices, int max_voxel_count) const
Recursively search the tree for all intersected leaf nodes and return a vector of indices.
void initIntersectedVoxel (Eigen::Vector3f &origin, Eigen::Vector3f &direction, double &min_x, double &min_y, double &min_z, double &max_x, double &max_y, double &max_z, unsigned char &a) const
Initialize raytracing algorithm.
int getFirstIntersectedNode (double min_x, double min_y, double min_z, double mid_x, double mid_y, double mid_z) const
Find first child node ray will enter.
int getNextIntersectedNode (double x, double y, double z, int a, int b, int c) const
Get the next visited node given the current node upper bounding box corner.
Protected Member Functions inherited from pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >
virtual void addPointIdx (const int point_idx_arg)
Add point at index from input pointcloud dataset to octree.
void expandLeafNode (LeafNode *leaf_node, BranchNode *parent_branch, unsigned char child_idx, unsigned int depth_mask)
Add point at index from input pointcloud dataset to octree.
const PointT & getPointByIndex (const unsigned int index_arg) const
Get point at index from input pointcloud dataset.
LeafContainerT * findLeafAtPoint (const PointT &point_arg) const
Find octree leaf node at a given point.
void getKeyBitSize ()
Define octree key setting and octree depth based on defined bounding box.
void adoptBoundingBoxToPoint (const PointT &point_idx_arg)
Grow the bounding box/octree until point fits.
bool isPointWithinBoundingBox (const PointT &point_idx_arg) const
Checks if given point is within the bounding box of the octree.
void genOctreeKeyforPoint (const PointT &point_arg, OctreeKey &key_arg) const
Generate octree key for voxel at a given point.
void genOctreeKeyforPoint (const double point_x_arg, const double point_y_arg, const double point_z_arg, OctreeKey &key_arg) const
Generate octree key for voxel at a given point.
virtual bool genOctreeKeyForDataT (const int &data_arg, OctreeKey &key_arg) const
Virtual method for generating octree key for a given point index.
void genLeafNodeCenterFromOctreeKey (const OctreeKey &key_arg, PointT &point_arg) const
Generate a point at center of leaf node voxel.
void genVoxelCenterFromOctreeKey (const OctreeKey &key_arg, unsigned int tree_depth_arg, PointT &point_arg) const
Generate a point at center of octree voxel at given tree level.
void genVoxelBoundsFromOctreeKey (const OctreeKey &key_arg, unsigned int tree_depth_arg, Eigen::Vector3f &min_pt, Eigen::Vector3f &max_pt) const
Generate bounds of an octree voxel using octree key and tree depth arguments.
int getOccupiedVoxelCentersRecursive (const BranchNode *node_arg, const OctreeKey &key_arg, AlignedPointTVector &voxel_center_list_arg) const
Recursively search the tree for all leaf nodes and return a vector of voxel centers.
Protected Member Functions inherited from pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >
LeafContainerT * createLeaf (const OctreeKey &key_arg)
Create a leaf node.
LeafContainerT * findLeaf (const OctreeKey &key_arg) const
Find leaf node.
bool existLeaf (const OctreeKey &key_arg) const
Check for existence of a leaf node in the octree.
void removeLeaf (const OctreeKey &key_arg)
Remove leaf node from octree.
OctreeNode * getRootNode () const
Retrieve root node.
bool branchHasChild (const BranchNode &branch_arg, unsigned char child_idx_arg) const
Check if branch is pointing to a particular child node.
OctreeNode * getBranchChildPtr (const BranchNode &branch_arg, unsigned char child_idx_arg) const
Retrieve a child node pointer for child node at child_idx.
void setBranchChildPtr (BranchNode &branch_arg, unsigned char child_idx_arg, OctreeNode *new_child_arg)
Assign new child node to branch.
char getBranchBitPattern (const BranchNode &branch_arg) const
Generate bit pattern reflecting the existence of child node pointers.
void deleteBranchChild (BranchNode &branch_arg, unsigned char child_idx_arg)
Delete child node and all its subchilds from octree.
void deleteBranch (BranchNode &branch_arg)
Delete branch and all its subchilds from octree.
BranchNode * createBranchChild (BranchNode &branch_arg, unsigned char child_idx_arg)
Create and add a new branch child to a branch class.
LeafNode * createLeafChild (BranchNode &branch_arg, unsigned char child_idx_arg)
Create and add a new leaf child to a branch class.
unsigned int createLeafRecursive (const OctreeKey &key_arg, unsigned int depth_mask_arg, BranchNode *branch_arg, LeafNode *&return_leaf_arg, BranchNode *&parent_of_leaf_arg)
Create a leaf node at octree key.
void findLeafRecursive (const OctreeKey &key_arg, unsigned int depth_mask_arg, BranchNode *branch_arg, LeafContainerT *&result_arg) const
Recursively search for a given leaf node and return a pointer.
bool deleteLeafRecursive (const OctreeKey &key_arg, unsigned int depth_mask_arg, BranchNode *branch_arg)
Recursively search and delete leaf node.
void serializeTreeRecursive (const BranchNode *branch_arg, OctreeKey &key_arg, std::vector< char > *binary_tree_out_arg, typename std::vector< LeafContainerT * > *leaf_container_vector_arg) const
Recursively explore the octree and output binary octree description together with a vector of leaf node LeafContainerTs.
void deserializeTreeRecursive (BranchNode *branch_arg, unsigned int depth_mask_arg, OctreeKey &key_arg, typename std::vector< char >::const_iterator &binary_tree_input_it_arg, typename std::vector< char >::const_iterator &binary_tree_input_it_end_arg, typename std::vector< LeafContainerT * >::const_iterator *leaf_container_vector_it_arg, typename std::vector< LeafContainerT * >::const_iterator *leaf_container_vector_it_end_arg)
Recursive method for deserializing octree structure.
virtual void serializeTreeCallback (LeafContainerT &, const OctreeKey &) const
Callback executed for every leaf node during serialization.
virtual void deserializeTreeCallback (LeafContainerT &, const OctreeKey &)
Callback executed for every leaf node during deserialization.
double Log2 (double n_arg)
Helper function to calculate the binary logarithm.
bool octreeCanResize ()
Test if octree is able to dynamically change its depth.
Additional Inherited Members
Protected Attributes inherited from pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >
PointCloudConstPtr input_
Pointer to input point cloud dataset.
IndicesConstPtr indices_
A pointer to the vector of point indices to use.
double epsilon_
Epsilon precision (error bound) for nearest neighbors searches.
double resolution_
Octree resolution.
double min_x_
double max_x_
double min_y_
double max_y_
double min_z_
double max_z_
bool bounding_box_defined_
Flag indicating if octree has defined bounding box.
std::size_t max_objs_per_leaf_
Amount of DataT objects per leafNode before expanding branch.
Protected Attributes inherited from pcl::octree::OctreeBase< LeafContainerT, BranchContainerT >
std::size_t leaf_count_
Amount of leaf nodes.
std::size_t branch_count_
Amount of branch nodes.
BranchNode * root_node_
Pointer to root branch node of octree.
unsigned int depth_mask_
Depth mask based on octree depth.
unsigned int octree_depth_
Octree depth.
bool dynamic_depth_enabled_
Enable dynamic_depth.
OctreeKey max_key_
key range
Detailed Description
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty>
class pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >
Octree pointcloud search class
Note
This class provides several methods for spatial neighbor search based on octree structure
typename: PointT: type of point used in pointcloud
Author
Julius Kammerl (juliu.nosp@m.s@ka.nosp@m.mmerl.nosp@m..de)
Definition at line 57 of file octree_search.h.
Member Typedef Documentation
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef std::vector<PointT, Eigen::aligned_allocator<PointT> > pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::AlignedPointTVector
Definition at line 73 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef OctreeT::BranchNode pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::BranchNode
Definition at line 77 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef boost::shared_ptr<const OctreePointCloudSearch<PointT, LeafContainerT, BranchContainerT> > pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::ConstPtr
Definition at line 70 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef boost::shared_ptr<const std::vector<int> > pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::IndicesConstPtr
Definition at line 62 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef boost::shared_ptr<std::vector<int> > pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::IndicesPtr
Definition at line 61 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef OctreeT::LeafNode pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::LeafNode
Definition at line 76 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef OctreePointCloud<PointT, LeafContainerT, BranchContainerT> pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::OctreeT
Definition at line 75 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef pcl::PointCloud<PointT> pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::PointCloud
Definition at line 64 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef boost::shared_ptr<const PointCloud> pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::PointCloudConstPtr
Definition at line 66 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef boost::shared_ptr<PointCloud> pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::PointCloudPtr
Definition at line 65 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> typedef boost::shared_ptr<OctreePointCloudSearch<PointT, LeafContainerT, BranchContainerT> > pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::Ptr
Definition at line 69 of file octree_search.h.
Constructor & Destructor Documentation
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::OctreePointCloudSearch (const double resolution) inline
Constructor.
Parameters
[in] resolution octree resolution at lowest octree level
Definition at line 82 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> virtual pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::~OctreePointCloudSearch () inline virtual
Empty class destructor.
Definition at line 89 of file octree_search.h.
Member Function Documentation
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::approxNearestSearch (const PointCloud & cloud, int query_index, int & result_index, float & sqr_distance) inline
Search for approx.
nearest neighbor at the query point.
Parameters
[in] cloud the point cloud data
[in] query_index the index in cloud representing the query point
[out] result_index the resultant index of the neighbor point
[out] sqr_distance the resultant squared distance to the neighboring point
Returns
number of neighbors found
Definition at line 156 of file octree_search.h.
References pcl::PointCloud< T >::points.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::approxNearestSearch (const PointT & p_q, int & result_index, float & sqr_distance)
Search for approx.
nearest neighbor at the query point.
Parameters
[in] p_q the given query point
[out] result_index the resultant index of the neighbor point
[out] sqr_distance the resultant squared distance to the neighboring point
Definition at line 131 of file octree_search.hpp.
References pcl::isFinite(), pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::approxNearestSearch (int query_index, int & result_index, float & sqr_distance)
Search for approx.
nearest neighbor at the query point.
Parameters
[in] query_index index representing the query point in the dataset given by setInputCloud. If indices were given in setInputCloud, index will be the position in the indices vector.
[out] result_index the resultant index of the neighbor point
[out] sqr_distance the resultant squared distance to the neighboring point
Returns
number of neighbors found
Definition at line 148 of file octree_search.hpp.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::approxNearestSearchRecursive (const PointT & point, const BranchNode * node, const OctreeKey & key, unsigned int tree_depth, int & result_index, float & sqr_distance) protected
Recursive search method that explores the octree and finds the approximate nearest neighbor.
Parameters
[in] point query point
[in] node current octree node to be explored
[in] key octree key addressing a leaf node.
[in] tree_depth current depth/level in the octree
[out] result_index result index is written to this reference
[out] sqr_distance squared distance to search
Definition at line 402 of file octree_search.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::boxSearch (const Eigen::Vector3f & min_pt, const Eigen::Vector3f & max_pt, std::vector< int > & k_indices) const
Search for points within rectangular search area Points exactly on the edges of the search rectangle are included.
Parameters
[in] min_pt lower corner of search area
[in] max_pt upper corner of search area
[out] k_indices the resultant point indices
Returns
number of points found within search area
Definition at line 190 of file octree_search.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::boxSearchRecursive (const Eigen::Vector3f & min_pt, const Eigen::Vector3f & max_pt, const BranchNode * node, const OctreeKey & key, unsigned int tree_depth, std::vector< int > & k_indices) const protected
Recursive search method that explores the octree and finds points within a rectangular search area.
Parameters
[in] min_pt lower corner of search area
[in] max_pt upper corner of search area
[in] node current octree node to be explored
[in] key octree key addressing a leaf node.
[in] tree_depth current depth/level in the octree
[out] k_indices the resultant point indices
Definition at line 506 of file octree_search.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getFirstIntersectedNode (double min_x, double min_y, double min_z, double mid_x, double mid_y, double mid_z) const inline protected
Find first child node ray will enter.
Parameters
[in] min_x octree nodes X coordinate of lower bounding box corner
[in] min_y octree nodes Y coordinate of lower bounding box corner
[in] min_z octree nodes Z coordinate of lower bounding box corner
[in] mid_x octree nodes X coordinate of bounding box mid line
[in] mid_y octree nodes Y coordinate of bounding box mid line
[in] mid_z octree nodes Z coordinate of bounding box mid line
Returns
the first child node ray will enter
Definition at line 520 of file octree_search.h.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getIntersectedVoxelCenters (Eigen::Vector3f origin, Eigen::Vector3f direction, AlignedPointTVector & voxel_center_list, int max_voxel_count = 0) const
Get a PointT vector of centers of all voxels that intersected by a ray (origin, direction).
Parameters
[in] origin ray origin
[in] direction ray direction vector
[out] voxel_center_list results are written to this vector of PointT elements
[in] max_voxel_count stop raycasting when this many voxels intersected (0: disable)
Returns
number of intersected voxels
Definition at line 583 of file octree_search.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getIntersectedVoxelCentersRecursive (double min_x, double min_y, double min_z, double max_x, double max_y, double max_z, unsigned char a, const OctreeNode * node, const OctreeKey & key, AlignedPointTVector & voxel_center_list, int max_voxel_count) const protected
Recursively search the tree for all intersected leaf nodes and return a vector of voxel centers.
This algorithm is based off the paper An Efficient Parametric Algorithm for Octree Traversal: http://wscg.zcu.cz/wscg2000/Papers_2000/X31.pdf
Parameters
[in] min_x octree nodes X coordinate of lower bounding box corner
[in] min_y octree nodes Y coordinate of lower bounding box corner
[in] min_z octree nodes Z coordinate of lower bounding box corner
[in] max_x octree nodes X coordinate of upper bounding box corner
[in] max_y octree nodes Y coordinate of upper bounding box corner
[in] max_z octree nodes Z coordinate of upper bounding box corner
[in] a
[in] node current octree node to be explored
[in] key octree key addressing a leaf node.
[out] voxel_center_list results are written to this vector of PointT elements
[in] max_voxel_count stop raycasting when this many voxels intersected (0: disable)
Returns
number of voxels found
Definition at line 631 of file octree_search.hpp.
References pcl::octree::OctreeNode::getNodeType(), pcl::octree::LEAF_NODE, pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getIntersectedVoxelIndices (Eigen::Vector3f origin, Eigen::Vector3f direction, std::vector< int > & k_indices, int max_voxel_count = 0) const
Get indices of all voxels that are intersected by a ray (origin, direction).
Parameters
[in] origin ray origin
[in] direction ray direction vector
[out] k_indices resulting point indices from intersected voxels
[in] max_voxel_count stop raycasting when this many voxels intersected (0: disable)
Returns
number of intersected voxels
Definition at line 608 of file octree_search.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
Referenced by pcl::TextureMapping< PointInT >::showOcclusions().
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getIntersectedVoxelIndicesRecursive (double min_x, double min_y, double min_z, double max_x, double max_y, double max_z, unsigned char a, const OctreeNode * node, const OctreeKey & key, std::vector< int > & k_indices, int max_voxel_count) const protected
Recursively search the tree for all intersected leaf nodes and return a vector of indices.
This algorithm is based off the paper An Efficient Parametric Algorithm for Octree Traversal: http://wscg.zcu.cz/wscg2000/Papers_2000/X31.pdf
Parameters
[in] min_x octree nodes X coordinate of lower bounding box corner
[in] min_y octree nodes Y coordinate of lower bounding box corner
[in] min_z octree nodes Z coordinate of lower bounding box corner
[in] max_x octree nodes X coordinate of upper bounding box corner
[in] max_y octree nodes Y coordinate of upper bounding box corner
[in] max_z octree nodes Z coordinate of upper bounding box corner
[in] a
[in] node current octree node to be explored
[in] key octree key addressing a leaf node.
[out] k_indices resulting indices
[in] max_voxel_count stop raycasting when this many voxels intersected (0: disable)
Returns
number of voxels found
Definition at line 749 of file octree_search.hpp.
References pcl::octree::OctreeNode::getNodeType(), pcl::octree::LEAF_NODE, pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > double pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getKNearestNeighborRecursive (const PointT & point, unsigned int K, const BranchNode * node, const OctreeKey & key, unsigned int tree_depth, const double squared_search_radius, std::vector< prioPointQueueEntry > & point_candidates) const protected
Recursive search method that explores the octree and finds the K nearest neighbors.
Parameters
[in] point query point
[in] K amount of nearest neighbors to be found
[in] node current octree node to be explored
[in] key octree key addressing a leaf node.
[in] tree_depth current depth/level in the octree
[in] squared_search_radius squared search radius distance
[out] point_candidates priority queue of nearest neigbor point candidates
Returns
squared search radius based on current point candidate set found
Definition at line 208 of file octree_search.hpp.
References pcl::K, pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::prioPointQueueEntry::point_distance_, pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::prioPointQueueEntry::point_idx_, pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getNeighborsWithinRadiusRecursive (const PointT & point, const double radiusSquared, const BranchNode * node, const OctreeKey & key, unsigned int tree_depth, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances, unsigned int max_nn) const protected
Recursive search method that explores the octree and finds neighbors within a given radius.
Parameters
[in] point query point
[in] radiusSquared squared search radius
[in] node current octree node to be explored
[in] key octree key addressing a leaf node.
[in] tree_depth current depth/level in the octree
[out] k_indices vector of indices found to be neighbors of query point
[out] k_sqr_distances squared distances of neighbors to query point
[in] max_nn maximum of neighbors to be found
Definition at line 317 of file octree_search.hpp.
References pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::getNextIntersectedNode (double x, double y, double z, int a, int b, int c) const inline protected
Get the next visited node given the current node upper bounding box corner.
This function accepts three float values, and three int values. The function returns the ith integer where the ith float value is the minimum of the three float values.
Parameters
[in] x current nodes X coordinate of upper bounding box corner
[in] y current nodes Y coordinate of upper bounding box corner
[in] z current nodes Z coordinate of upper bounding box corner
[in] a next node if exit Plane YZ
[in] b next node if exit Plane XZ
[in] c next node if exit Plane XY
Returns
the next child node ray will enter or 8 if exiting
Definition at line 579 of file octree_search.h.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> void pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::initIntersectedVoxel (Eigen::Vector3f & origin, Eigen::Vector3f & direction, double & min_x, double & min_y, double & min_z, double & max_x, double & max_y, double & max_z, unsigned char & a) const inline protected
Initialize raytracing algorithm.
Parameters
origin
direction
[in] min_x octree nodes X coordinate of lower bounding box corner
[in] min_y octree nodes Y coordinate of lower bounding box corner
[in] min_z octree nodes Z coordinate of lower bounding box corner
[in] max_x octree nodes X coordinate of upper bounding box corner
[in] max_y octree nodes Y coordinate of upper bounding box corner
[in] max_z octree nodes Z coordinate of upper bounding box corner
a
Definition at line 466 of file octree_search.h.
References pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >::max_x_, pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >::max_y_, pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >::max_z_, pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >::min_x_, pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >::min_y_, and pcl::octree::OctreePointCloud< PointT, LeafContainerT, BranchContainerT >::min_z_.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::nearestKSearch (const PointCloud & cloud, int index, int k, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances) inline
Search for k-nearest neighbors at the query point.
Parameters
[in] cloud the point cloud data
[in] index the index in cloud representing the query point
[in] k the number of neighbors to search for
[out] k_indices the resultant indices of the neighboring points (must be resized to k a priori!)
[out] k_sqr_distances the resultant squared distances to the neighboring points (must be resized to k a priori!)
Returns
number of neighbors found
Definition at line 119 of file octree_search.h.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::nearestKSearch (const PointT & p_q, int k, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances)
Search for k-nearest neighbors at given query point.
Parameters
[in] p_q the given query point
[in] k the number of neighbors to search for
[out] k_indices the resultant indices of the neighboring points (must be resized to k a priori!)
[out] k_sqr_distances the resultant squared distances to the neighboring points (must be resized to k a priori!)
Returns
number of neighbors found
Definition at line 78 of file octree_search.hpp.
References pcl::isFinite(), pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::nearestKSearch (int index, int k, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances)
Search for k-nearest neighbors at query point.
Parameters
[in] index index representing the query point in the dataset given by setInputCloud. If indices were given in setInputCloud, index will be the position in the indices vector.
[in] k the number of neighbors to search for
[out] k_indices the resultant indices of the neighboring points (must be resized to k a priori!)
[out] k_sqr_distances the resultant squared distances to the neighboring points (must be resized to k a priori!)
Returns
number of neighbors found
Definition at line 121 of file octree_search.hpp.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > float pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::pointSquaredDist (const PointT & point_a, const PointT & point_b) const protected
Helper function to calculate the squared distance between two points.
Parameters
[in] point_a point A
[in] point_b point B
Returns
squared distance between point A and point B
Definition at line 498 of file octree_search.hpp.
template<typename PointT, typename LeafContainerT = OctreeContainerPointIndices, typename BranchContainerT = OctreeContainerEmpty> int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::radiusSearch (const PointCloud & cloud, int index, double radius, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances, unsigned int max_nn = 0) inline
Search for all neighbors of query point that are within a given radius.
Parameters
[in] cloud the point cloud data
[in] index the index in cloud representing the query point
[in] radius the radius of the sphere bounding all of p_q's neighbors
[out] k_indices the resultant indices of the neighboring points
[out] k_sqr_distances the resultant squared distances to the neighboring points
[in] max_nn if given, bounds the maximum returned neighbors to this value
Returns
number of neighbors found in radius
Definition at line 189 of file octree_search.h.
References pcl::PointCloud< T >::points.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::radiusSearch (const PointT & p_q, const double radius, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances, unsigned int max_nn = 0) const
Search for all neighbors of query point that are within a given radius.
Parameters
[in] p_q the given query point
[in] radius the radius of the sphere bounding all of p_q's neighbors
[out] k_indices the resultant indices of the neighboring points
[out] k_sqr_distances the resultant squared distances to the neighboring points
[in] max_nn if given, bounds the maximum returned neighbors to this value
Returns
number of neighbors found in radius
Definition at line 158 of file octree_search.hpp.
References pcl::isFinite(), pcl::octree::OctreeKey::x, pcl::octree::OctreeKey::y, and pcl::octree::OctreeKey::z.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > int pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::radiusSearch (int index, const double radius, std::vector< int > & k_indices, std::vector< float > & k_sqr_distances, unsigned int max_nn = 0) const
Search for all neighbors of query point that are within a given radius.
Parameters
[in] index index representing the query point in the dataset given by setInputCloud. If indices were given in setInputCloud, index will be the position in the indices vector
[in] radius radius of the sphere bounding all of p_q's neighbors
[out] k_indices the resultant indices of the neighboring points
[out] k_sqr_distances the resultant squared distances to the neighboring points
[in] max_nn if given, bounds the maximum returned neighbors to this value
Returns
number of neighbors found in radius
Definition at line 178 of file octree_search.hpp.
template<typename PointT , typename LeafContainerT , typename BranchContainerT > bool pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::voxelSearch (const PointT & point, std::vector< int > & point_idx_data)
Search for neighbors within a voxel at given point.
Parameters
[in] point point addressing a leaf node voxel
[out] point_idx_data the resultant indices of the neighboring voxel points
Returns
"true" if leaf node exist; "false" otherwise
Definition at line 46 of file octree_search.hpp.
References pcl::isFinite().
Referenced by pcl::GFPFHEstimation< PointInT, PointLT, PointOutT >::computeFeature().
template<typename PointT , typename LeafContainerT , typename BranchContainerT > bool pcl::octree::OctreePointCloudSearch< PointT, LeafContainerT, BranchContainerT >::voxelSearch (const int index, std::vector< int > & point_idx_data)
Search for neighbors within a voxel at given point referenced by a point index.
Parameters
[in] index the index in input cloud defining the query point
[out] point_idx_data the resultant indices of the neighboring voxel points
Returns
"true" if leaf node exist; "false" otherwise
Definition at line 69 of file octree_search.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/octree/include/pcl/octree/octree_search.h
/home/travis/build/PointCloudLibrary/pcl/octree/include/pcl/octree/impl/octree_search.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:13