Point Cloud Library (PCL): pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType > Class Template Reference
pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType > Class Template Reference
Utility class for evaluating a decision tree.
#include <pcl/ml/dt/decision_tree_evaluator.h>
Public Member Functions
DecisionTreeEvaluator ()
Constructor.
virtual ~DecisionTreeEvaluator ()
Destructor.
void evaluate (pcl::DecisionTree< NodeType > &tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< LabelType > &label_data)
Evaluates the specified examples using the supplied tree.
void evaluateAndAdd (pcl::DecisionTree< NodeType > &tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< LabelType > &label_data)
Evaluates the specified examples using the supplied tree and adds the results to the supplied results array.
void evaluate (pcl::DecisionTree< NodeType > &tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, ExampleIndex example, NodeType &leave)
Evaluates the specified examples using the supplied tree.
void getNodes (pcl::DecisionTree< NodeType > &tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > &feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > &stats_estimator, DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< NodeType * > &nodes)
Evaluates the specified examples using the supplied tree.
Detailed Description
template<class FeatureType, class DataSet, class LabelType, class ExampleIndex, class NodeType>
class pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >
Utility class for evaluating a decision tree.
Definition at line 59 of file decision_tree_evaluator.h.
Constructor & Destructor Documentation
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::DecisionTreeEvaluator ()
Constructor.
Definition at line 52 of file decision_tree_evaluator.hpp.
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::~DecisionTreeEvaluator () virtual
Destructor.
Definition at line 58 of file decision_tree_evaluator.hpp.
Member Function Documentation
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluate (pcl::DecisionTree< NodeType > & tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< LabelType > & label_data)
Evaluates the specified examples using the supplied tree.
Parameters
[in] tree The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] examples The examples that have to be evaluated.
[out] label_data The destination for the resulting label data.
Definition at line 65 of file decision_tree_evaluator.hpp.
References pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getLabelOfNode(), and pcl::DecisionTree< NodeType >::getRoot().
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluate (pcl::DecisionTree< NodeType > & tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, ExampleIndex example, NodeType & leave)
Evaluates the specified examples using the supplied tree.
Parameters
[in] tree The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] example The example that has to be evaluated.
[out] leave The leave reached by the examples.
Definition at line 129 of file decision_tree_evaluator.hpp.
References pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), and pcl::DecisionTree< NodeType >::getRoot().
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::evaluateAndAdd (pcl::DecisionTree< NodeType > & tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< LabelType > & label_data)
Evaluates the specified examples using the supplied tree and adds the results to the supplied results array.
Parameters
[in] tree The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] examples The examples that have to be evaluated.
[out] label_data The destination where the resulting label data is added to.
Definition at line 98 of file decision_tree_evaluator.hpp.
References pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getLabelOfNode(), and pcl::DecisionTree< NodeType >::getRoot().
template<class FeatureType , class DataSet , class LabelType , class ExampleIndex , class NodeType > void pcl::DecisionTreeEvaluator< FeatureType, DataSet, LabelType, ExampleIndex, NodeType >::getNodes (pcl::DecisionTree< NodeType > & tree, pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex > & feature_handler, pcl::StatsEstimator< LabelType, NodeType, DataSet, ExampleIndex > & stats_estimator, DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< NodeType * > & nodes)
Evaluates the specified examples using the supplied tree.
Parameters
[in] tree The decision tree.
[in] feature_handler The feature handler used to train the tree.
[in] stats_estimator The statistics estimation instance used while training the tree.
[in] data_set The data set used for evaluation.
[in] examples The examples that have to be evaluated.
[out] nodes The leaf-nodes reached while evaluation.
Definition at line 158 of file decision_tree_evaluator.hpp.
References pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex(), pcl::FeatureHandler< FeatureType, DataSet, ExampleIndex >::evaluateFeature(), and pcl::DecisionTree< NodeType >::getRoot().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/ml/include/pcl/ml/dt/decision_tree_evaluator.h
/home/travis/build/PointCloudLibrary/pcl/ml/include/pcl/ml/impl/dt/decision_tree_evaluator.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:33