Point Cloud Library (PCL): pcl::DefaultIterator< PointT > Class Template Reference
pcl::DefaultIterator< PointT > Class Template Reference
#include <pcl/impl/cloud_iterator.hpp>
Inherits pcl::CloudIterator< PointT >::Iterator.
Public Member Functions
DefaultIterator (PointCloud< PointT > &cloud)
~DefaultIterator ()
void operator++ ()
void operator++ (int)
PointT & operator* () const
PointT * operator-> ()
unsigned getCurrentPointIndex () const
unsigned getCurrentIndex () const
size_t size () const
void reset ()
bool isValid () const
Detailed Description
template<class PointT>
class pcl::DefaultIterator< PointT >
Author
Suat Gedikli
Definition at line 50 of file cloud_iterator.hpp.
Constructor & Destructor Documentation
template<class PointT > pcl::DefaultIterator< PointT >::DefaultIterator (PointCloud< PointT > & cloud) inline
Definition at line 53 of file cloud_iterator.hpp.
template<class PointT > pcl::DefaultIterator< PointT >::~DefaultIterator () inline
Definition at line 59 of file cloud_iterator.hpp.
Member Function Documentation
template<class PointT > unsigned pcl::DefaultIterator< PointT >::getCurrentIndex () const inline
Definition at line 88 of file cloud_iterator.hpp.
References pcl::PointCloud< T >::begin().
template<class PointT > unsigned pcl::DefaultIterator< PointT >::getCurrentPointIndex () const inline
Definition at line 83 of file cloud_iterator.hpp.
References pcl::PointCloud< T >::begin().
template<class PointT > bool pcl::DefaultIterator< PointT >::isValid () const inline
Definition at line 103 of file cloud_iterator.hpp.
References pcl::PointCloud< T >::end().
template<class PointT > PointT& pcl::DefaultIterator< PointT >::operator* () const inline
Definition at line 73 of file cloud_iterator.hpp.
template<class PointT > void pcl::DefaultIterator< PointT >::operator++ () inline
Definition at line 63 of file cloud_iterator.hpp.
template<class PointT > void pcl::DefaultIterator< PointT >::operator++ (int) inline
Definition at line 68 of file cloud_iterator.hpp.
template<class PointT > PointT* pcl::DefaultIterator< PointT >::operator-> () inline
Definition at line 78 of file cloud_iterator.hpp.
template<class PointT > void pcl::DefaultIterator< PointT >::reset () inline
Definition at line 98 of file cloud_iterator.hpp.
References pcl::PointCloud< T >::begin().
template<class PointT > size_t pcl::DefaultIterator< PointT >::size () const inline
Definition at line 93 of file cloud_iterator.hpp.
References pcl::PointCloud< T >::size().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/impl/cloud_iterator.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:56