Point Cloud Library (PCL): pcl::geometry::TriangleMesh< MeshTraitsT > Class Template Reference
pcl::geometry::TriangleMesh< MeshTraitsT > Class Template Reference
Module geometry
Half-edge mesh that can only store triangles.
#include <pcl/geometry/triangle_mesh.h>
Public Types
typedef
pcl::geometry::MeshBase
< TriangleMesh< MeshTraitsT >
, MeshTraitsT, TriangleMeshTag > Base
typedef TriangleMesh< MeshTraitsT > Self
typedef boost::shared_ptr< Self > Ptr
typedef boost::shared_ptr
< const Self > ConstPtr
typedef Base::VertexData VertexData
typedef Base::HalfEdgeData HalfEdgeData
typedef Base::EdgeData EdgeData
typedef Base::FaceData FaceData
typedef Base::IsManifold IsManifold
typedef Base::MeshTag MeshTag
typedef Base::HasVertexData HasVertexData
typedef Base::HasHalfEdgeData HasHalfEdgeData
typedef Base::HasEdgeData HasEdgeData
typedef Base::HasFaceData HasFaceData
typedef Base::VertexDataCloud VertexDataCloud
typedef Base::HalfEdgeDataCloud HalfEdgeDataCloud
typedef Base::EdgeDataCloud EdgeDataCloud
typedef Base::FaceDataCloud FaceDataCloud
typedef Base::VertexIndex VertexIndex
typedef Base::HalfEdgeIndex HalfEdgeIndex
typedef Base::EdgeIndex EdgeIndex
typedef Base::FaceIndex FaceIndex
typedef std::pair< FaceIndex,
FaceIndex > FaceIndexPair
typedef Base::VertexIndices VertexIndices
typedef Base::HalfEdgeIndices HalfEdgeIndices
typedef Base::EdgeIndices EdgeIndices
typedef Base::FaceIndices FaceIndices
typedef
Base::VertexAroundVertexCirculator VertexAroundVertexCirculator
typedef
Base::OutgoingHalfEdgeAroundVertexCirculator OutgoingHalfEdgeAroundVertexCirculator
typedef
Base::IncomingHalfEdgeAroundVertexCirculator IncomingHalfEdgeAroundVertexCirculator
typedef
Base::FaceAroundVertexCirculator FaceAroundVertexCirculator
typedef
Base::VertexAroundFaceCirculator VertexAroundFaceCirculator
typedef
Base::InnerHalfEdgeAroundFaceCirculator InnerHalfEdgeAroundFaceCirculator
typedef
Base::OuterHalfEdgeAroundFaceCirculator OuterHalfEdgeAroundFaceCirculator
typedef
Base::FaceAroundFaceCirculator FaceAroundFaceCirculator
Public Types inherited from pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, TriangleMeshTag >
typedef MeshBase< TriangleMesh
< MeshTraitsT >, MeshTraitsT,
TriangleMeshTag > Self
typedef boost::shared_ptr< Self > Ptr
typedef boost::shared_ptr
< const Self > ConstPtr
typedef TriangleMesh< MeshTraitsT > Derived
typedef MeshTraitsT::VertexData VertexData
typedef MeshTraitsT::HalfEdgeData HalfEdgeData
typedef MeshTraitsT::EdgeData EdgeData
typedef MeshTraitsT::FaceData FaceData
typedef MeshTraitsT::IsManifold IsManifold
typedef TriangleMeshTag MeshTag
typedef
boost::integral_constant< bool,!boost::is_same
< VertexData,
pcl::geometry::NoData >::value > HasVertexData
typedef
boost::integral_constant< bool,!boost::is_same
< HalfEdgeData,
pcl::geometry::NoData >::value > HasHalfEdgeData
typedef
boost::integral_constant< bool,!boost::is_same
< EdgeData,
pcl::geometry::NoData >::value > HasEdgeData
typedef
boost::integral_constant< bool,!boost::is_same
< FaceData,
pcl::geometry::NoData >::value > HasFaceData
typedef pcl::PointCloud
< VertexData > VertexDataCloud
typedef pcl::PointCloud
< HalfEdgeData > HalfEdgeDataCloud
typedef pcl::PointCloud< EdgeData > EdgeDataCloud
typedef pcl::PointCloud< FaceData > FaceDataCloud
typedef pcl::geometry::VertexIndex VertexIndex
typedef
pcl::geometry::HalfEdgeIndex HalfEdgeIndex
typedef pcl::geometry::EdgeIndex EdgeIndex
typedef pcl::geometry::FaceIndex FaceIndex
typedef std::vector< VertexIndex > VertexIndices
typedef std::vector
< HalfEdgeIndex > HalfEdgeIndices
typedef std::vector< EdgeIndex > EdgeIndices
typedef std::vector< FaceIndex > FaceIndices
typedef
pcl::geometry::VertexAroundVertexCirculator
< const Self > VertexAroundVertexCirculator
typedef
pcl::geometry::OutgoingHalfEdgeAroundVertexCirculator
< const Self > OutgoingHalfEdgeAroundVertexCirculator
typedef
pcl::geometry::IncomingHalfEdgeAroundVertexCirculator
< const Self > IncomingHalfEdgeAroundVertexCirculator
typedef
pcl::geometry::FaceAroundVertexCirculator
< const Self > FaceAroundVertexCirculator
typedef
pcl::geometry::VertexAroundFaceCirculator
< const Self > VertexAroundFaceCirculator
typedef
pcl::geometry::InnerHalfEdgeAroundFaceCirculator
< const Self > InnerHalfEdgeAroundFaceCirculator
typedef
pcl::geometry::OuterHalfEdgeAroundFaceCirculator
< const Self > OuterHalfEdgeAroundFaceCirculator
typedef
pcl::geometry::FaceAroundFaceCirculator
< const Self > FaceAroundFaceCirculator
Public Member Functions
TriangleMesh ()
Constructor.
FaceIndex addFace (const VertexIndex &idx_v_0, const VertexIndex &idx_v_1, const VertexIndex &idx_v_2, const FaceData &face_data=FaceData(), const EdgeData &edge_data=EdgeData(), const HalfEdgeData &half_edge_data=HalfEdgeData())
Add a triangle to the mesh.
FaceIndexPair addTrianglePair (const VertexIndices &vertices, const FaceData &face_data=FaceData(), const EdgeData &edge_data=EdgeData(), const HalfEdgeData &half_edge_data=HalfEdgeData())
Add two triangles for the four given input vertices.
FaceIndexPair addTrianglePair (const VertexIndex &idx_v_0, const VertexIndex &idx_v_1, const VertexIndex &idx_v_2, const VertexIndex &idx_v_3, const FaceData &face_data=FaceData(), const EdgeData &edge_data=EdgeData(), const HalfEdgeData &half_edge_data=HalfEdgeData())
Add two triangles for the four given input vertices.
Public Member Functions inherited from pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, TriangleMeshTag >
BOOST_CONCEPT_ASSERT ((boost::Convertible< IsManifold, bool >))
MeshBase ()
Constructor.
VertexIndex addVertex (const VertexData &vertex_data=VertexData())
Add a vertex to the mesh.
FaceIndex addFace (const VertexIndices &vertices, const FaceData &face_data=FaceData(), const EdgeData &edge_data=EdgeData(), const HalfEdgeData &half_edge_data=HalfEdgeData())
Add a face to the mesh.
void deleteVertex (const VertexIndex &idx_vertex)
Mark the given vertex and all connected half-edges and faces as deleted.
void deleteEdge (const HalfEdgeIndex &idx_he)
Mark the given half-edge, the opposite half-edge and the associated faces as deleted.
void deleteEdge (const EdgeIndex &idx_edge)
Mark the given edge (both half-edges) and the associated faces as deleted.
void deleteFace (const FaceIndex &idx_face)
Mark the given face as deleted.
void cleanUp ()
Removes all mesh elements and data that are marked as deleted.
HalfEdgeIndex getOutgoingHalfEdgeIndex (const VertexIndex &idx_vertex) const
Get the outgoing half-edge index to a given vertex.
HalfEdgeIndex getIncomingHalfEdgeIndex (const VertexIndex &idx_vertex) const
Get the incoming half-edge index to a given vertex.
VertexIndex getTerminatingVertexIndex (const HalfEdgeIndex &idx_half_edge) const
Get the terminating vertex index to a given half-edge.
VertexIndex getOriginatingVertexIndex (const HalfEdgeIndex &idx_half_edge) const
Get the originating vertex index to a given half-edge.
HalfEdgeIndex getOppositeHalfEdgeIndex (const HalfEdgeIndex &idx_half_edge) const
Get the opposite half-edge index to a given half-edge.
HalfEdgeIndex getNextHalfEdgeIndex (const HalfEdgeIndex &idx_half_edge) const
Get the next half-edge index to a given half-edge.
HalfEdgeIndex getPrevHalfEdgeIndex (const HalfEdgeIndex &idx_half_edge) const
Get the previous half-edge index to a given half-edge.
FaceIndex getFaceIndex (const HalfEdgeIndex &idx_half_edge) const
Get the face index to a given half-edge.
FaceIndex getFaceIndex (const FaceData &face_data) const
Get the index associated to the given face data.
FaceIndex getOppositeFaceIndex (const HalfEdgeIndex &idx_half_edge) const
Get the face index to a given half-edge.
HalfEdgeIndex getInnerHalfEdgeIndex (const FaceIndex &idx_face) const
Get the inner half-edge index to a given face.
HalfEdgeIndex getOuterHalfEdgeIndex (const FaceIndex &idx_face) const
Get the outer half-edge inex to a given face.
VertexAroundVertexCirculator getVertexAroundVertexCirculator (const VertexIndex &idx_vertex) const
VertexAroundVertexCirculator getVertexAroundVertexCirculator (const HalfEdgeIndex &idx_outgoing_half_edge) const
OutgoingHalfEdgeAroundVertexCirculator getOutgoingHalfEdgeAroundVertexCirculator (const VertexIndex &idx_vertex) const
OutgoingHalfEdgeAroundVertexCirculator getOutgoingHalfEdgeAroundVertexCirculator (const HalfEdgeIndex &idx_outgoing_half_edge) const
IncomingHalfEdgeAroundVertexCirculator getIncomingHalfEdgeAroundVertexCirculator (const VertexIndex &idx_vertex) const
IncomingHalfEdgeAroundVertexCirculator getIncomingHalfEdgeAroundVertexCirculator (const HalfEdgeIndex &idx_incoming_half_edge) const
FaceAroundVertexCirculator getFaceAroundVertexCirculator (const VertexIndex &idx_vertex) const
FaceAroundVertexCirculator getFaceAroundVertexCirculator (const HalfEdgeIndex &idx_outgoing_half_edge) const
VertexAroundFaceCirculator getVertexAroundFaceCirculator (const FaceIndex &idx_face) const
VertexAroundFaceCirculator getVertexAroundFaceCirculator (const HalfEdgeIndex &idx_inner_half_edge) const
InnerHalfEdgeAroundFaceCirculator getInnerHalfEdgeAroundFaceCirculator (const FaceIndex &idx_face) const
InnerHalfEdgeAroundFaceCirculator getInnerHalfEdgeAroundFaceCirculator (const HalfEdgeIndex &idx_inner_half_edge) const
OuterHalfEdgeAroundFaceCirculator getOuterHalfEdgeAroundFaceCirculator (const FaceIndex &idx_face) const
OuterHalfEdgeAroundFaceCirculator getOuterHalfEdgeAroundFaceCirculator (const HalfEdgeIndex &idx_inner_half_edge) const
FaceAroundFaceCirculator getFaceAroundFaceCirculator (const FaceIndex &idx_face) const
FaceAroundFaceCirculator getFaceAroundFaceCirculator (const HalfEdgeIndex &idx_inner_half_edge) const
bool isEqualTopology (const Self &other) const
Check if the other mesh has the same topology as this mesh.
bool isValid (const VertexIndex &idx_vertex) const
Check if the given vertex index is a valid index into the mesh.
bool isValid (const HalfEdgeIndex &idx_he) const
Check if the given half-edge index is a valid index into the mesh.
bool isValid (const EdgeIndex &idx_edge) const
Check if the given edge index is a valid index into the mesh.
bool isValid (const FaceIndex &idx_face) const
Check if the given face index is a valid index into the mesh.
bool isDeleted (const VertexIndex &idx_vertex) const
Check if the given vertex is marked as deleted.
bool isDeleted (const HalfEdgeIndex &idx_he) const
Check if the given half-edge is marked as deleted.
bool isDeleted (const EdgeIndex &idx_edge) const
Check if the given edge (any of the two half-edges) is marked as deleted.
bool isDeleted (const FaceIndex &idx_face) const
Check if the given face is marked as deleted.
bool isIsolated (const VertexIndex &idx_vertex) const
Check if the given vertex is isolated (not connected to other elements).
bool isBoundary (const VertexIndex &idx_vertex) const
Check if the given vertex lies on the boundary.
bool isBoundary (const HalfEdgeIndex &idx_he) const
Check if the given half-edge lies on the bounddary.
bool isBoundary (const EdgeIndex &idx_edge) const
Check if the given edge lies on the boundary (any of the two half-edges lies on the boundary.
bool isBoundary (const FaceIndex &idx_face) const
Check if the given face lies on the boundary.
bool isBoundary (const FaceIndex &idx_face) const
Check if the given face lies on the boundary.
bool isManifold (const VertexIndex &idx_vertex) const
Check if the given vertex is manifold.
bool isManifold () const
Check if the mesh is manifold.
size_t sizeVertices () const
Get the number of the vertices.
size_t sizeHalfEdges () const
Get the number of the half-edges.
size_t sizeEdges () const
Get the number of the edges.
size_t sizeFaces () const
Get the number of the faces.
bool empty () const
Check if the mesh is empty.
bool emptyVertices () const
Check if the vertices are empty.
bool emptyEdges () const
Check if the edges are empty.
bool emptyFaces () const
Check if the faces are empty.
void reserveVertices (const size_t n)
Reserve storage space n vertices.
void reserveEdges (const size_t n)
Reserve storage space for n edges (2*n storage space is reserved for the half-edges).
void reserveFaces (const size_t n)
Reserve storage space for n faces.
void resizeVertices (const size_t n, const VertexData &data=VertexData())
Resize the the vertices to n elements.
void resizeEdges (const size_t n, const EdgeData &edge_data=EdgeData(), const HalfEdgeData he_data=HalfEdgeData())
Resize the edges to n elements (half-edges will hold 2*n elements).
void resizeFaces (const size_t n, const FaceData &data=FaceData())
Resize the faces to n elements.
void clear ()
Clear all mesh elements and data.
VertexDataCloud & getVertexDataCloud ()
Get access to the stored vertex data.
VertexDataCloud getVertexDataCloud () const
Get the stored vertex data.
bool setVertexDataCloud (const VertexDataCloud &vertex_data_cloud)
Change the stored vertex data.
HalfEdgeDataCloud & getHalfEdgeDataCloud ()
Get access to the stored half-edge data.
HalfEdgeDataCloud getHalfEdgeDataCloud () const
Get the stored half-edge data.
bool setHalfEdgeDataCloud (const HalfEdgeDataCloud &half_edge_data_cloud)
Change the stored half-edge data.
EdgeDataCloud & getEdgeDataCloud ()
Get access to the stored edge data.
EdgeDataCloud getEdgeDataCloud () const
Get the stored edge data.
bool setEdgeDataCloud (const EdgeDataCloud &edge_data_cloud)
Change the stored edge data.
FaceDataCloud & getFaceDataCloud ()
Get access to the stored face data.
FaceDataCloud getFaceDataCloud () const
Get the stored face data.
bool setFaceDataCloud (const FaceDataCloud &face_data_cloud)
Change the stored face data.
VertexIndex getVertexIndex (const VertexData &vertex_data) const
Get the index associated to the given vertex data.
HalfEdgeIndex getHalfEdgeIndex (const HalfEdgeData &half_edge_data) const
Get the index associated to the given half-edge data.
EdgeIndex getEdgeIndex (const EdgeData &edge_data) const
Get the index associated to the given edge data.
Friends
class pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, pcl::geometry::TriangleMeshTag >
Additional Inherited Members
Protected Types inherited from pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, TriangleMeshTag >
typedef pcl::geometry::Vertex Vertex
typedef pcl::geometry::HalfEdge HalfEdge
typedef pcl::geometry::Face Face
typedef std::vector< Vertex > Vertices
typedef std::vector< HalfEdge > HalfEdges
typedef std::vector< Face > Faces
typedef Vertices::iterator VertexIterator
typedef HalfEdges::iterator HalfEdgeIterator
typedef Faces::iterator FaceIterator
typedef Vertices::const_iterator VertexConstIterator
typedef HalfEdges::const_iterator HalfEdgeConstIterator
typedef Faces::const_iterator FaceConstIterator
Protected Member Functions inherited from pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, TriangleMeshTag >
void deleteFace (const FaceIndex &idx_face, boost::true_type)
Manifold version of deleteFace.
void deleteFace (const FaceIndex &idx_face, boost::false_type)
Non-manifold version of deleteFace.
bool isBoundary (const FaceIndex &idx_face, boost::true_type) const
Check if any vertex of the face lies on the boundary.
bool isBoundary (const FaceIndex &idx_face, boost::false_type) const
Check if any edge of the face lies on the boundary.
bool isManifold (const VertexIndex &, boost::true_type) const
Always manifold.
bool isManifold (const VertexIndex &idx_vertex, boost::false_type) const
Check if the given vertex is manifold.
bool isManifold (boost::true_type) const
Always manifold.
bool isManifold (boost::false_type) const
Check if all vertices in the mesh are manifold.
FaceIndex addFaceImplBase (const VertexIndices &vertices, const FaceData &face_data, const EdgeData &edge_data, const HalfEdgeData &half_edge_data)
General implementation of addFace.
HalfEdgeIndex addEdge (const VertexIndex &idx_v_a, const VertexIndex &idx_v_b, const HalfEdgeData &he_data, const EdgeData &edge_data)
Add an edge between the two given vertices and connect them with the vertices.
bool checkTopology1 (const VertexIndex &idx_v_a, const VertexIndex &idx_v_b, HalfEdgeIndex &idx_he_ab, std::vector< bool >::reference is_new_ab, boost::true_type) const
Check if the edge between the two vertices can be added.
bool checkTopology1 (const VertexIndex &idx_v_a, const VertexIndex &idx_v_b, HalfEdgeIndex &idx_he_ab, std::vector< bool >::reference is_new_ab, boost::false_type) const
Non manifold version of checkTopology1.
bool checkTopology2 (const HalfEdgeIndex &, const HalfEdgeIndex &, const bool is_new_ab, const bool is_new_bc, const bool is_isolated_b, std::vector< bool >::reference, HalfEdgeIndex &, boost::true_type) const
Check if the face may be added (mesh does not become non-manifold).
bool checkTopology2 (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, const bool is_new_ab, const bool is_new_bc, const bool, std::vector< bool >::reference make_adjacent_ab_bc, HalfEdgeIndex &idx_free_half_edge, boost::false_type) const
Check if the half-edge bc is the next half-edge of ab.
void makeAdjacent (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, HalfEdgeIndex &idx_free_half_edge)
Make the half-edges bc the next half-edge of ab.
FaceIndex connectFace (const HalfEdgeIndices &inner_he, const FaceData &face_data)
Add a face to the mesh and connect it to the half-edges.
void connectPrevNext (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc)
Connect the next and prev indices of the two half-edges with each other.
void connectNewNew (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, const VertexIndex &idx_v_b, boost::true_type)
Both half-edges are new (manifold version).
void connectNewNew (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, const VertexIndex &idx_v_b, boost::false_type)
Both half-edges are new (non-manifold version).
void connectNewOld (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, const VertexIndex &idx_v_b)
The first half-edge is new.
void connectOldNew (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, const VertexIndex &idx_v_b)
The second half-edge is new.
void connectOldOld (const HalfEdgeIndex &, const HalfEdgeIndex &, const VertexIndex &, boost::true_type)
Both half-edges are old (manifold version).
void connectOldOld (const HalfEdgeIndex &, const HalfEdgeIndex &idx_he_bc, const VertexIndex &idx_v_b, boost::false_type)
Both half-edges are old (non-manifold version).
void addData (pcl::PointCloud< DataT > &cloud, const DataT &data, boost::true_type)
Add mesh data.
void addData (pcl::PointCloud< DataT > &, const DataT &, boost::false_type)
Does nothing.
void reconnect (const HalfEdgeIndex &idx_he_ab, const HalfEdgeIndex &idx_he_bc, const bool is_boundary_ba, const bool is_boundary_cb)
Deconnect the input half-edges from the mesh and adjust the indices of the connected half-edges.
void reconnectNBNB (const HalfEdgeIndex &idx_he_bc, const HalfEdgeIndex &idx_he_cb, const VertexIndex &idx_v_b, boost::true_type)
Both edges are not on the boundary.
void reconnectNBNB (const HalfEdgeIndex &idx_he_bc, const HalfEdgeIndex &, const VertexIndex &idx_v_b, boost::false_type)
Both edges are not on the boundary.
void markDeleted (const VertexIndex &idx_vertex)
Mark the given vertex as deleted.
void markDeleted (const HalfEdgeIndex &idx_he)
Mark the given half-edge as deleted.
void markDeleted (const EdgeIndex &idx_edge)
Mark the given edge (both half-edges) as deleted.
void markDeleted (const FaceIndex &idx_face)
Mark the given face as deleted.
IndexContainerT remove (ElementContainerT &elements, DataContainerT &data_cloud)
Removes mesh elements and data that are marked as deleted from the container.
void incrementIf (IteratorT &it, boost::true_type) const
Increment the iterator.
void incrementIf (IteratorT &, boost::false_type) const
Does nothing.
void assignIf (const ConstIteratorT source, IteratorT target, boost::true_type) const
Assign the source iterator to the target iterator.
void assignIf (const ConstIteratorT, IteratorT, boost::false_type) const
Does nothing.
void setOutgoingHalfEdgeIndex (const VertexIndex &idx_vertex, const HalfEdgeIndex &idx_outgoing_half_edge)
Set the outgoing half-edge index to a given vertex.
void setTerminatingVertexIndex (const HalfEdgeIndex &idx_half_edge, const VertexIndex &idx_terminating_vertex)
Set the terminating vertex index to a given half-edge.
void setNextHalfEdgeIndex (const HalfEdgeIndex &idx_half_edge, const HalfEdgeIndex &idx_next_half_edge)
Set the next half_edge index to a given half-edge.
void setPrevHalfEdgeIndex (const HalfEdgeIndex &idx_half_edge, const HalfEdgeIndex &idx_prev_half_edge)
Set the previous half-edge index to a given half-edge.
void setFaceIndex (const HalfEdgeIndex &idx_half_edge, const FaceIndex &idx_face)
Set the face index to a given half-edge.
void setInnerHalfEdgeIndex (const FaceIndex &idx_face, const HalfEdgeIndex &idx_inner_half_edge)
Set the inner half-edge index to a given face.
void reserveData (DataCloudT &cloud, const size_t n, boost::true_type) const
Reserve storage space for the mesh data.
void reserveData (DataCloudT &, const size_t, boost::false_type) const
Does nothing.
void resizeData (DataCloudT &, const size_t n, const typename DataCloudT::value_type &data, boost::true_type) const
Resize the mesh data.
void resizeData (DataCloudT &, const size_t, const typename DataCloudT::value_type &, boost::false_type) const
Does nothing.
void clearData (DataCloudT &cloud, boost::true_type) const
Clear the mesh data.
void clearData (DataCloudT &, boost::false_type) const
Does nothing.
Vertex & getVertex (const VertexIndex &idx_vertex)
Get the vertex for the given index.
Vertex getVertex (const VertexIndex &idx_vertex) const
Get the vertex for the given index.
void setVertex (const VertexIndex &idx_vertex, const Vertex &vertex)
Set the vertex at the given index.
HalfEdge & getHalfEdge (const HalfEdgeIndex &idx_he)
Get the half-edge for the given index.
HalfEdge getHalfEdge (const HalfEdgeIndex &idx_he) const
Get the half-edge for the given index.
void setHalfEdge (const HalfEdgeIndex &idx_he, const HalfEdge &half_edge)
Set the half-edge at the given index.
Face & getFace (const FaceIndex &idx_face)
Get the face for the given index.
Face getFace (const FaceIndex &idx_face) const
Get the face for the given index.
void setFace (const FaceIndex &idx_face, const Face &face)
Set the face at the given index.
Detailed Description
template<class MeshTraitsT>
class pcl::geometry::TriangleMesh< MeshTraitsT >
Half-edge mesh that can only store triangles.
Template Parameters
MeshTraitsT Please have a look at pcl::geometry::DefaultMeshTraits.
Author
Martin Saelzle
Definition at line 61 of file triangle_mesh.h.
Member Typedef Documentation
template<class MeshTraitsT > typedef pcl::geometry::MeshBase<TriangleMesh <MeshTraitsT>, MeshTraitsT, TriangleMeshTag> pcl::geometry::TriangleMesh< MeshTraitsT >::Base
Definition at line 65 of file triangle_mesh.h.
template<class MeshTraitsT > typedef boost::shared_ptr<const Self> pcl::geometry::TriangleMesh< MeshTraitsT >::ConstPtr
Definition at line 69 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::EdgeData pcl::geometry::TriangleMesh< MeshTraitsT >::EdgeData
Definition at line 73 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::EdgeDataCloud pcl::geometry::TriangleMesh< MeshTraitsT >::EdgeDataCloud
Definition at line 85 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::EdgeIndex pcl::geometry::TriangleMesh< MeshTraitsT >::EdgeIndex
Definition at line 91 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::EdgeIndices pcl::geometry::TriangleMesh< MeshTraitsT >::EdgeIndices
Definition at line 97 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::FaceAroundFaceCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::FaceAroundFaceCirculator
Definition at line 108 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::FaceAroundVertexCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::FaceAroundVertexCirculator
Definition at line 104 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::FaceData pcl::geometry::TriangleMesh< MeshTraitsT >::FaceData
Definition at line 74 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::FaceDataCloud pcl::geometry::TriangleMesh< MeshTraitsT >::FaceDataCloud
Definition at line 86 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::FaceIndex pcl::geometry::TriangleMesh< MeshTraitsT >::FaceIndex
Definition at line 92 of file triangle_mesh.h.
template<class MeshTraitsT > typedef std::pair<FaceIndex, FaceIndex> pcl::geometry::TriangleMesh< MeshTraitsT >::FaceIndexPair
Definition at line 93 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::FaceIndices pcl::geometry::TriangleMesh< MeshTraitsT >::FaceIndices
Definition at line 98 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HalfEdgeData pcl::geometry::TriangleMesh< MeshTraitsT >::HalfEdgeData
Definition at line 72 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HalfEdgeDataCloud pcl::geometry::TriangleMesh< MeshTraitsT >::HalfEdgeDataCloud
Definition at line 84 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HalfEdgeIndex pcl::geometry::TriangleMesh< MeshTraitsT >::HalfEdgeIndex
Definition at line 90 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HalfEdgeIndices pcl::geometry::TriangleMesh< MeshTraitsT >::HalfEdgeIndices
Definition at line 96 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HasEdgeData pcl::geometry::TriangleMesh< MeshTraitsT >::HasEdgeData
Definition at line 80 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HasFaceData pcl::geometry::TriangleMesh< MeshTraitsT >::HasFaceData
Definition at line 81 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HasHalfEdgeData pcl::geometry::TriangleMesh< MeshTraitsT >::HasHalfEdgeData
Definition at line 79 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::HasVertexData pcl::geometry::TriangleMesh< MeshTraitsT >::HasVertexData
Definition at line 78 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::IncomingHalfEdgeAroundVertexCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::IncomingHalfEdgeAroundVertexCirculator
Definition at line 103 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::InnerHalfEdgeAroundFaceCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::InnerHalfEdgeAroundFaceCirculator
Definition at line 106 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::IsManifold pcl::geometry::TriangleMesh< MeshTraitsT >::IsManifold
Definition at line 75 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::MeshTag pcl::geometry::TriangleMesh< MeshTraitsT >::MeshTag
Definition at line 76 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::OuterHalfEdgeAroundFaceCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::OuterHalfEdgeAroundFaceCirculator
Definition at line 107 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::OutgoingHalfEdgeAroundVertexCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::OutgoingHalfEdgeAroundVertexCirculator
Definition at line 102 of file triangle_mesh.h.
template<class MeshTraitsT > typedef boost::shared_ptr<Self> pcl::geometry::TriangleMesh< MeshTraitsT >::Ptr
Definition at line 68 of file triangle_mesh.h.
template<class MeshTraitsT > typedef TriangleMesh<MeshTraitsT> pcl::geometry::TriangleMesh< MeshTraitsT >::Self
Definition at line 67 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::VertexAroundFaceCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::VertexAroundFaceCirculator
Definition at line 105 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::VertexAroundVertexCirculator pcl::geometry::TriangleMesh< MeshTraitsT >::VertexAroundVertexCirculator
Definition at line 101 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::VertexData pcl::geometry::TriangleMesh< MeshTraitsT >::VertexData
Definition at line 71 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::VertexDataCloud pcl::geometry::TriangleMesh< MeshTraitsT >::VertexDataCloud
Definition at line 83 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::VertexIndex pcl::geometry::TriangleMesh< MeshTraitsT >::VertexIndex
Definition at line 89 of file triangle_mesh.h.
template<class MeshTraitsT > typedef Base::VertexIndices pcl::geometry::TriangleMesh< MeshTraitsT >::VertexIndices
Definition at line 95 of file triangle_mesh.h.
Constructor & Destructor Documentation
template<class MeshTraitsT > pcl::geometry::TriangleMesh< MeshTraitsT >::TriangleMesh () inline
Constructor.
Definition at line 111 of file triangle_mesh.h.
Member Function Documentation
template<class MeshTraitsT > FaceIndex pcl::geometry::TriangleMesh< MeshTraitsT >::addFace (const VertexIndex & idx_v_0, const VertexIndex & idx_v_1, const VertexIndex & idx_v_2, const FaceData & face_data = FaceData (), const EdgeData & edge_data = EdgeData (), const HalfEdgeData & half_edge_data = HalfEdgeData ()) inline
Add a triangle to the mesh.
Data is only added if it is associated with the elements. The last vertex is connected with the first one.
Parameters
[in] idx_v_0 Index to the first vertex.
[in] idx_v_1 Index to the second vertex.
[in] idx_v_2 Index to the third vertex.
[in] face_data Data that is set for the face.
[in] half_edge_data Data that is set for all added half-edges.
[in] edge_data Data that is set for all added edges.
Returns
Index to the new face. Failure is signaled by returning an invalid face index.
Warning
The vertices must be valid and unique (each vertex may be contained only once). Not complying with this requirement results in undefined behavior!
Definition at line 133 of file triangle_mesh.h.
References pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, TriangleMeshTag >::addFaceImplBase().
Referenced by pcl::geometry::TriangleMesh< MeshTraitsT >::addTrianglePair().
template<class MeshTraitsT > FaceIndexPair pcl::geometry::TriangleMesh< MeshTraitsT >::addTrianglePair (const VertexIndices & vertices, const FaceData & face_data = FaceData (), const EdgeData & edge_data = EdgeData (), const HalfEdgeData & half_edge_data = HalfEdgeData ()) inline
Add two triangles for the four given input vertices.
When using a manifold triangle mesh it is not possible to connect two bounded regions without going through a non-manifold intermediate step. This method first tries to add the triangles individually and if this fails connects the whole configuration at once (if possible).
Parameters
[in] vertices Indices to the vertices of the new face. (The size must be equal to four).
[in] face_data Data that is set for the face.
[in] half_edge_data Data that is set for all added half-edges.
[in] edge_data Data that is set for all added edges.
Returns
Pair of face indices. The first index is valid if one triangle was added. Both indices are valid if two triangles were added.
Warning
The vertices must be valid and unique (each vertex may be contained only once). Not complying with this requirement results in undefined behavior!
Definition at line 156 of file triangle_mesh.h.
template<class MeshTraitsT > FaceIndexPair pcl::geometry::TriangleMesh< MeshTraitsT >::addTrianglePair (const VertexIndex & idx_v_0, const VertexIndex & idx_v_1, const VertexIndex & idx_v_2, const VertexIndex & idx_v_3, const FaceData & face_data = FaceData (), const EdgeData & edge_data = EdgeData (), const HalfEdgeData & half_edge_data = HalfEdgeData ()) inline
Add two triangles for the four given input vertices.
When using a manifold triangle mesh it is not possible to connect two bounded regions without going through a non-manifold intermediate step. This method first tries to add the triangles individually and if this fails connects the whole configuration at once (if possible).
Parameters
[in] idx_v_0 Index to the first vertex.
[in] idx_v_1 Index to the second vertex.
[in] idx_v_2 Index to the third vertex.
[in] idx_v_3 Index to the fourth vertex.
[in] face_data Data that is set for the face.
[in] half_edge_data Data that is set for all added half-edges.
[in] edge_data Data that is set for all added edges.
Returns
Pair of face indices. The first index is valid if one triangle was added. Both indices are valid if two triangles were added.
Warning
The vertices must be valid and unique (each vertex may be contained only once). Not complying with this requirement results in undefined behavior!
Definition at line 183 of file triangle_mesh.h.
References pcl::geometry::TriangleMesh< MeshTraitsT >::addFace(), pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, TriangleMeshTag >::checkTopology1(), and pcl::geometry::FaceIndex::isValid().
Friends And Related Function Documentation
template<class MeshTraitsT > friend class pcl::geometry::MeshBase< TriangleMesh< MeshTraitsT >, MeshTraitsT, pcl::geometry::TriangleMeshTag > friend
Definition at line 257 of file triangle_mesh.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/geometry/include/pcl/geometry/triangle_mesh.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:00