Point Cloud Library (PCL): pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar > Class Template Reference
pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar > Class Template Reference
Module registration
CorrespondenceEstimationBackprojection computes correspondences as points in the target cloud which have minimum
#include <pcl/registration/correspondence_estimation_backprojection.h>
Public Types
typedef boost::shared_ptr
< CorrespondenceEstimationBackProjection
< PointSource, PointTarget,
NormalT, Scalar > > Ptr
typedef boost::shared_ptr
< const
CorrespondenceEstimationBackProjection
< PointSource, PointTarget,
NormalT, Scalar > > ConstPtr
typedef pcl::search::KdTree
< PointTarget > KdTree
typedef pcl::search::KdTree
< PointTarget >::Ptr KdTreePtr
typedef pcl::PointCloud
< PointSource > PointCloudSource
typedef PointCloudSource::Ptr PointCloudSourcePtr
typedef PointCloudSource::ConstPtr PointCloudSourceConstPtr
typedef pcl::PointCloud
< PointTarget > PointCloudTarget
typedef PointCloudTarget::Ptr PointCloudTargetPtr
typedef PointCloudTarget::ConstPtr PointCloudTargetConstPtr
typedef pcl::PointCloud< NormalT > PointCloudNormals
typedef PointCloudNormals::Ptr NormalsPtr
typedef PointCloudNormals::ConstPtr NormalsConstPtr
Public Types inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >
typedef boost::shared_ptr
< CorrespondenceEstimationBase
< PointSource, PointTarget,
Scalar > > Ptr
typedef boost::shared_ptr
< const
CorrespondenceEstimationBase
< PointSource, PointTarget,
Scalar > > ConstPtr
typedef pcl::search::KdTree
< PointTarget > KdTree
typedef KdTree::Ptr KdTreePtr
typedef pcl::search::KdTree
< PointSource > KdTreeReciprocal
typedef KdTree::Ptr KdTreeReciprocalPtr
typedef pcl::PointCloud
< PointSource > PointCloudSource
typedef PointCloudSource::Ptr PointCloudSourcePtr
typedef PointCloudSource::ConstPtr PointCloudSourceConstPtr
typedef pcl::PointCloud
< PointTarget > PointCloudTarget
typedef PointCloudTarget::Ptr PointCloudTargetPtr
typedef PointCloudTarget::ConstPtr PointCloudTargetConstPtr
typedef
KdTree::PointRepresentationConstPtr PointRepresentationConstPtr
Public Types inherited from pcl::PCLBase< PointSource >
typedef pcl::PointCloud
< PointSource > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Public Member Functions
CorrespondenceEstimationBackProjection ()
Empty constructor.
virtual ~CorrespondenceEstimationBackProjection ()
Empty destructor.
void setSourceNormals (const NormalsConstPtr &normals)
Set the normals computed on the source point cloud.
NormalsConstPtr getSourceNormals () const
Get the normals of the source point cloud.
void setTargetNormals (const NormalsConstPtr &normals)
Set the normals computed on the target point cloud.
NormalsConstPtr getTargetNormals () const
Get the normals of the target point cloud.
bool requiresSourceNormals () const
See if this rejector requires source normals.
void setSourceNormals (pcl::PCLPointCloud2::ConstPtr cloud2)
Blob method for setting the source normals.
bool requiresTargetNormals () const
See if this rejector requires target normals.
void setTargetNormals (pcl::PCLPointCloud2::ConstPtr cloud2)
Method for setting the target normals.
void determineCorrespondences (pcl::Correspondences &correspondences, double max_distance=std::numeric_limits< double >::max())
Determine the correspondences between input and target cloud.
virtual void determineReciprocalCorrespondences (pcl::Correspondences &correspondences, double max_distance=std::numeric_limits< double >::max())
Determine the reciprocal correspondences between input and target cloud.
void setKSearch (unsigned int k)
Set the number of nearest neighbours to be considered in the target point cloud.
unsigned int getKSearch () const
Get the number of nearest neighbours considered in the target point cloud for computing correspondences.
virtual boost::shared_ptr
< CorrespondenceEstimationBase
< PointSource, PointTarget,
Scalar > > clone () const
Clone and cast to CorrespondenceEstimationBase.
Public Member Functions inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >
CorrespondenceEstimationBase ()
Empty constructor.
virtual ~CorrespondenceEstimationBase ()
Empty destructor.
void setInputSource (const PointCloudSourceConstPtr &cloud)
Provide a pointer to the input source (e.g., the point cloud that we want to align to the target)
PointCloudSourceConstPtr const getInputSource ()
Get a pointer to the input point cloud dataset target.
void setInputTarget (const PointCloudTargetConstPtr &cloud)
Provide a pointer to the input target (e.g., the point cloud that we want to align the input source to)
PointCloudTargetConstPtr const getInputTarget ()
Get a pointer to the input point cloud dataset target.
void setIndicesSource (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represent the input source point cloud.
IndicesPtr const getIndicesSource ()
Get a pointer to the vector of indices used for the source dataset.
void setIndicesTarget (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represent the input target point cloud.
IndicesPtr const getIndicesTarget ()
Get a pointer to the vector of indices used for the target dataset.
void setSearchMethodTarget (const KdTreePtr &tree, bool force_no_recompute=false)
Provide a pointer to the search object used to find correspondences in the target cloud.
KdTreePtr getSearchMethodTarget () const
Get a pointer to the search method used to find correspondences in the target cloud.
void setSearchMethodSource (const KdTreeReciprocalPtr &tree, bool force_no_recompute=false)
Provide a pointer to the search object used to find correspondences in the source cloud (usually used by reciprocal correspondence finding).
KdTreeReciprocalPtr getSearchMethodSource () const
Get a pointer to the search method used to find correspondences in the source cloud.
void setPointRepresentation (const PointRepresentationConstPtr &point_representation)
Provide a boost shared pointer to the PointRepresentation to be used when searching for nearest neighbors.
Public Member Functions inherited from pcl::PCLBase< PointSource >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (size_t row_start, size_t col_start, size_t nb_rows, size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointSource & operator[] (size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
bool initCompute ()
Internal computation initialization.
Protected Member Functions inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >
const std::string & getClassName () const
Abstract class get name method.
bool initCompute ()
Internal computation initialization.
bool initComputeReciprocal ()
Internal computation initialization for reciprocal correspondences.
Protected Member Functions inherited from pcl::PCLBase< PointSource >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Additional Inherited Members
Protected Attributes inherited from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >
std::string corr_name_
The correspondence estimation method name.
KdTreePtr tree_
A pointer to the spatial search object used for the target dataset.
KdTreeReciprocalPtr tree_reciprocal_
A pointer to the spatial search object used for the source dataset.
PointCloudTargetConstPtr target_
The input point cloud dataset target.
IndicesPtr target_indices_
The target point cloud dataset indices.
PointRepresentationConstPtr point_representation_
The point representation used (internal).
PointCloudTargetPtr input_transformed_
The transformed input source point cloud dataset.
std::vector< pcl::PCLPointField > input_fields_
The types of input point fields available.
bool target_cloud_updated_
Variable that stores whether we have a new target cloud, meaning we need to pre-process it again.
bool source_cloud_updated_
Variable that stores whether we have a new source cloud, meaning we need to pre-process it again.
bool force_no_recompute_
A flag which, if set, means the tree operating on the target cloud will never be recomputed.
bool force_no_recompute_reciprocal_
A flag which, if set, means the tree operating on the source cloud will never be recomputed.
Protected Attributes inherited from pcl::PCLBase< PointSource >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointSource, typename PointTarget, typename NormalT, typename Scalar = float>
class pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >
CorrespondenceEstimationBackprojection computes correspondences as points in the target cloud which have minimum
Author
Suat Gedikli
Definition at line 56 of file correspondence_estimation_backprojection.h.
Member Typedef Documentation
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef boost::shared_ptr<const CorrespondenceEstimationBackProjection<PointSource, PointTarget, NormalT, Scalar> > pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::ConstPtr
Definition at line 60 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef pcl::search::KdTree<PointTarget> pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::KdTree
Definition at line 72 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef pcl::search::KdTree<PointTarget>::Ptr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::KdTreePtr
Definition at line 73 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef PointCloudNormals::ConstPtr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::NormalsConstPtr
Definition at line 85 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef PointCloudNormals::Ptr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::NormalsPtr
Definition at line 84 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef pcl::PointCloud<NormalT> pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudNormals
Definition at line 83 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef pcl::PointCloud<PointSource> pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudSource
Definition at line 75 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef PointCloudSource::ConstPtr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudSourceConstPtr
Definition at line 77 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef PointCloudSource::Ptr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudSourcePtr
Definition at line 76 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef pcl::PointCloud<PointTarget> pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudTarget
Definition at line 79 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef PointCloudTarget::ConstPtr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudTargetConstPtr
Definition at line 81 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef PointCloudTarget::Ptr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::PointCloudTargetPtr
Definition at line 80 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> typedef boost::shared_ptr<CorrespondenceEstimationBackProjection<PointSource, PointTarget, NormalT, Scalar> > pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::Ptr
Definition at line 59 of file correspondence_estimation_backprojection.h.
Constructor & Destructor Documentation
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::CorrespondenceEstimationBackProjection () inline
Empty constructor.
Note
Sets the number of neighbors to be considered in the target point cloud (k_) to 10.
Definition at line 92 of file correspondence_estimation_backprojection.h.
References pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >::corr_name_.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> virtual pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::~CorrespondenceEstimationBackProjection () inline virtual
Empty destructor.
Definition at line 102 of file correspondence_estimation_backprojection.h.
Member Function Documentation
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> virtual boost::shared_ptr< CorrespondenceEstimationBase<PointSource, PointTarget, Scalar> > pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::clone () const inline virtual
Clone and cast to CorrespondenceEstimationBase.
Implements pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 192 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar > void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineCorrespondences (pcl::Correspondences & correspondences, double max_distance = std::numeric_limits<double>::max ()) virtual
Determine the correspondences between input and target cloud.
Parameters
[out] correspondences the found correspondences (index of query point, index of target point, distance)
[in] max_distance maximum distance between the normal on the source point cloud and the corresponding point in the target point cloud
Implements pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 59 of file correspondence_estimation_backprojection.hpp.
References pcl::copyPoint(), pcl::Correspondence::distance, pcl::Correspondence::index_match, and pcl::Correspondence::index_query.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar > void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::determineReciprocalCorrespondences (pcl::Correspondences & correspondences, double max_distance = std::numeric_limits<double>::max ()) virtual
Determine the reciprocal correspondences between input and target cloud.
A correspondence is considered reciprocal if both Src_i has Tgt_i as a correspondence, and Tgt_i has Src_i as one.
Parameters
[out] correspondences the found correspondences (index of query and target point, distance)
[in] max_distance maximum allowed distance between correspondences
Implements pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 157 of file correspondence_estimation_backprojection.hpp.
References pcl::copyPoint(), pcl::Correspondence::distance, pcl::Correspondence::index_match, and pcl::Correspondence::index_query.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> unsigned int pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::getKSearch () const inline
Get the number of nearest neighbours considered in the target point cloud for computing correspondences.
By default we use k = 10 nearest neighbors.
Definition at line 188 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> NormalsConstPtr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::getSourceNormals () const inline
Get the normals of the source point cloud.
Definition at line 113 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> NormalsConstPtr pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::getTargetNormals () const inline
Get the normals of the target point cloud.
Definition at line 124 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar > bool pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::initCompute () protected
Internal computation initialization.
Definition at line 46 of file correspondence_estimation_backprojection.hpp.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> bool pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::requiresSourceNormals () const inline virtual
See if this rejector requires source normals.
Reimplemented from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 129 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> bool pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::requiresTargetNormals () const inline virtual
See if this rejector requires target normals.
Reimplemented from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 143 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setKSearch (unsigned int k) inline
Set the number of nearest neighbours to be considered in the target point cloud.
By default, we use k = 10 nearest neighbors.
Parameters
[in] k the number of nearest neighbours to be considered
Definition at line 181 of file correspondence_estimation_backprojection.h.
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals (const NormalsConstPtr & normals) inline
Set the normals computed on the source point cloud.
Parameters
[in] normals the normals computed for the source cloud
Definition at line 108 of file correspondence_estimation_backprojection.h.
Referenced by pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals().
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals (pcl::PCLPointCloud2::ConstPtr cloud2) inline virtual
Blob method for setting the source normals.
Reimplemented from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 134 of file correspondence_estimation_backprojection.h.
References pcl::fromPCLPointCloud2(), and pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setSourceNormals().
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setTargetNormals (const NormalsConstPtr & normals) inline
Set the normals computed on the target point cloud.
Parameters
[in] normals the normals computed for the target cloud
Definition at line 119 of file correspondence_estimation_backprojection.h.
Referenced by pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setTargetNormals().
template<typename PointSource , typename PointTarget , typename NormalT , typename Scalar = float> void pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setTargetNormals (pcl::PCLPointCloud2::ConstPtr cloud2) inline virtual
Method for setting the target normals.
Reimplemented from pcl::registration::CorrespondenceEstimationBase< PointSource, PointTarget, Scalar >.
Definition at line 148 of file correspondence_estimation_backprojection.h.
References pcl::fromPCLPointCloud2(), and pcl::registration::CorrespondenceEstimationBackProjection< PointSource, PointTarget, NormalT, Scalar >::setTargetNormals().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/registration/include/pcl/registration/correspondence_estimation_backprojection.h
/home/travis/build/PointCloudLibrary/pcl/registration/include/pcl/registration/impl/correspondence_estimation_backprojection.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:18