Point Cloud Library (PCL): pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex > Class Template Reference
pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex > Class Template Reference
Statistics estimator for regression trees which optimizes information gain and pose parameters error.
#include <pcl/recognition/face_detection/rf_face_utils.h>
Public Member Functions
PoseClassRegressionVarianceStatsEstimator (BranchEstimator *branch_estimator)
Constructor.
virtual ~PoseClassRegressionVarianceStatsEstimator ()
Destructor.
size_t getNumOfBranches () const
Returns the number of branches the corresponding tree has.
LabelDataType getLabelOfNode (NodeType &node) const
Returns the label of the specified node.
unsigned int computeMeanAndCovarianceOffset (DataSet &data_set, std::vector< ExampleIndex > &examples, Eigen::Matrix3d &covariance_matrix, Eigen::Vector3d &centroid) const
Computes the covariance matrix for translation offsets.
unsigned int computeMeanAndCovarianceAngles (DataSet &data_set, std::vector< ExampleIndex > &examples, Eigen::Matrix3d &covariance_matrix, Eigen::Vector3d &centroid) const
Computes the covariance matrix for rotation values.
float computeInformationGain (DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< LabelDataType > &label_data, std::vector< float > &results, std::vector< unsigned char > &flags, const float threshold) const
Computes the information gain obtained by the specified threshold.
void computeBranchIndices (std::vector< float > &results, std::vector< unsigned char > &flags, const float threshold, std::vector< unsigned char > &branch_indices) const
Computes the branch indices for all supplied results.
void computeBranchIndex (const float result, const unsigned char flag, const float threshold, unsigned char &branch_index) const
Computes the branch index for the specified result.
void computeAndSetNodeStats (DataSet &data_set, std::vector< ExampleIndex > &examples, std::vector< LabelDataType > &label_data, NodeType &node) const
Computes and sets the statistics for a node.
void generateCodeForBranchIndexComputation (NodeType &, std::ostream &stream) const
Generates code for branch index computation.
void generateCodeForOutput (NodeType &, std::ostream &stream) const
Generates code for label output.
Public Member Functions inherited from pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >
virtual ~StatsEstimator ()
Destructor.
Detailed Description
template<class LabelDataType, class NodeType, class DataSet, class ExampleIndex>
class pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >
Statistics estimator for regression trees which optimizes information gain and pose parameters error.
Definition at line 197 of file rf_face_utils.h.
Constructor & Destructor Documentation
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::PoseClassRegressionVarianceStatsEstimator (BranchEstimator * branch_estimator) inline
Constructor.
Definition at line 202 of file rf_face_utils.h.
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > virtual pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::~PoseClassRegressionVarianceStatsEstimator () inline virtual
Destructor.
Definition at line 208 of file rf_face_utils.h.
Member Function Documentation
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > void pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeAndSetNodeStats (DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< LabelDataType > & label_data, NodeType & node) const inline virtual
Computes and sets the statistics for a node.
Parameters
[in] data_set The data set which is evaluated.
[in] examples The examples which define which parts of the data set are used for evaluation.
[in] label_data The label_data corresponding to the examples.
[out] node The destination node for the statistics.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 476 of file rf_face_utils.h.
References pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeMeanAndCovarianceAngles(), and pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeMeanAndCovarianceOffset().
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > void pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex (const float result, const unsigned char flag, const float threshold, unsigned char & branch_index) const inline virtual
Computes the branch index for the specified result.
Parameters
[in] result The result the branch index will be computed for.
[in] flag The flag corresponding to the specified result.
[in] threshold The threshold used to compute the branch index.
[out] branch_index The destination for the computed branch index.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 465 of file rf_face_utils.h.
References pcl::BranchEstimator::computeBranchIndex().
Referenced by pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndices(), and pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeInformationGain().
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > void pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndices (std::vector< float > & results, std::vector< unsigned char > & flags, const float threshold, std::vector< unsigned char > & branch_indices) const inline virtual
Computes the branch indices for all supplied results.
Parameters
[in] results The results the branch indices will be computed for.
[in] flags The flags corresponding to the specified results.
[in] threshold The threshold used to compute the branch indices.
[out] branch_indices The destination for the computed branch indices.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 445 of file rf_face_utils.h.
References pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex().
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > float pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeInformationGain (DataSet & data_set, std::vector< ExampleIndex > & examples, std::vector< LabelDataType > & label_data, std::vector< float > & results, std::vector< unsigned char > & flags, const float threshold) const inline virtual
Computes the information gain obtained by the specified threshold.
Parameters
[in] data_set The data set corresponding to the supplied result data.
[in] examples The examples used for extracting the supplied result data.
[in] label_data The label data corresponding to the specified examples.
[in] results The results computed using the specified examples.
[in] flags The flags corresponding to the results.
[in] threshold The threshold for which the information gain is computed.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 322 of file rf_face_utils.h.
References pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeBranchIndex(), pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeMeanAndCovarianceAngles(), pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeMeanAndCovarianceOffset(), and pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getNumOfBranches().
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > unsigned int pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeMeanAndCovarianceAngles (DataSet & data_set, std::vector< ExampleIndex > & examples, Eigen::Matrix3d & covariance_matrix, Eigen::Vector3d & centroid) const inline
Computes the covariance matrix for rotation values.
Parameters
[in] data_set The corresponding data set.
[in] examples A set of examples from the dataset.
[out] covariance_matrix The covariance matrix.
[out] centroid The mean of the data.
Definition at line 276 of file rf_face_utils.h.
References pcl::face_detection::TrainingExample::rot_.
Referenced by pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeAndSetNodeStats(), and pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeInformationGain().
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > unsigned int pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeMeanAndCovarianceOffset (DataSet & data_set, std::vector< ExampleIndex > & examples, Eigen::Matrix3d & covariance_matrix, Eigen::Vector3d & centroid) const inline
Computes the covariance matrix for translation offsets.
Parameters
[in] data_set The corresponding data set.
[in] examples A set of examples from the dataset.
[out] covariance_matrix The covariance matrix.
[out] centroid The mean of the data.
Definition at line 232 of file rf_face_utils.h.
References pcl::face_detection::TrainingExample::trans_.
Referenced by pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeAndSetNodeStats(), and pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeInformationGain().
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > void pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::generateCodeForBranchIndexComputation (NodeType & , std::ostream & stream) const inline virtual
Generates code for branch index computation.
Parameters
[out] stream The destination for the generated code.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 519 of file rf_face_utils.h.
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > void pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::generateCodeForOutput (NodeType & , std::ostream & stream) const inline virtual
Generates code for label output.
Parameters
[out] stream The destination for the generated code.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 528 of file rf_face_utils.h.
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > LabelDataType pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getLabelOfNode (NodeType & node) const inline virtual
Returns the label of the specified node.
Parameters
[in] node The node which label is returned.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 221 of file rf_face_utils.h.
template<class LabelDataType , class NodeType , class DataSet , class ExampleIndex > size_t pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::getNumOfBranches () const inline virtual
Returns the number of branches the corresponding tree has.
Implements pcl::StatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >.
Definition at line 213 of file rf_face_utils.h.
References pcl::BranchEstimator::getNumOfBranches().
Referenced by pcl::face_detection::PoseClassRegressionVarianceStatsEstimator< LabelDataType, NodeType, DataSet, ExampleIndex >::computeInformationGain().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/recognition/include/pcl/recognition/face_detection/rf_face_utils.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:57