Point Cloud Library (PCL): INCVMemAllocator Class Reference
INCVMemAllocator Class Reference abstract
INCVMemAllocator (Interface)
#include </home/travis/build/PointCloudLibrary/pcl/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
virtual ~INCVMemAllocator ()=0
virtual NCVStatus alloc (NCVMemSegment &seg, size_t size)=0
virtual NCVStatus dealloc (NCVMemSegment &seg)=0
virtual NcvBool isInitialized (void) const =0
virtual NcvBool isCounting (void) const =0
virtual NCVMemoryType memType (void) const =0
virtual Ncv32u alignment (void) const =0
virtual size_t maxSize (void) const =0
Detailed Description
INCVMemAllocator (Interface)
Definition at line 418 of file NCV.hpp.
Constructor & Destructor Documentation
INCVMemAllocator::~INCVMemAllocator () inline pure virtual
Definition at line 434 of file NCV.hpp.
Member Function Documentation
virtual Ncv32u INCVMemAllocator::alignment (void) const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVVectorAlloc< HaarClassifierNode128 >::getAllocatorsAlignment(), NCVMatrixAlloc< T >::getAllocatorsAlignment(), and NCVMatrixAlloc< T >::NCVMatrixAlloc().
virtual NCVStatus INCVMemAllocator::alloc (NCVMemSegment & seg, size_t size) pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVVectorAlloc< HaarClassifierNode128 >::NCVVectorAlloc().
virtual NCVStatus INCVMemAllocator::dealloc (NCVMemSegment & seg) pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVMatrixAlloc< T >::~NCVMatrixAlloc(), and NCVVectorAlloc< HaarClassifierNode128 >::~NCVVectorAlloc().
virtual NcvBool INCVMemAllocator::isCounting (void) const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
Referenced by NCVVectorAlloc< HaarClassifierNode128 >::isMemAllocated(), and NCVMatrixAlloc< T >::isMemAllocated().
virtual NcvBool INCVMemAllocator::isInitialized (void) const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
virtual size_t INCVMemAllocator::maxSize (void) const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
virtual NCVMemoryType INCVMemAllocator::memType (void) const pure virtual
Implemented in NCVMemNativeAllocator, and NCVMemStackAllocator.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:30