Point Cloud Library (PCL): NCVMatrix< T > Class Template Reference
NCVMatrix< T > Class Template Reference
NCVMatrix (2D)
#include </home/travis/build/PointCloudLibrary/pcl/gpu/people/src/cuda/nvidia/NCV.hpp>
Public Member Functions
NCVMatrix ()
virtual ~NCVMatrix ()
void clear ()
Ncv32u stride () const
NCVStatus copySolid (NCVMatrix< T > &dst, cudaStream_t cuStream, size_t howMuch=0) const
NCVStatus copy2D (NCVMatrix< T > &dst, NcvSize32u roi, cudaStream_t cuStream) const
T & at (Ncv32u x, Ncv32u y) const
T * ptr () const
Ncv32u width () const
Ncv32u height () const
NcvSize32u size () const
Ncv32u pitch () const
NCVMemoryType memType () const
Protected Attributes
T * _ptr
Ncv32u _width
Ncv32u _height
Ncv32u _pitch
NCVMemoryType _memtype
Detailed Description
template<class T>
class NCVMatrix< T >
NCVMatrix (2D)
Definition at line 695 of file NCV.hpp.
Constructor & Destructor Documentation
template<class T> NCVMatrix< T >::NCVMatrix () inline
Definition at line 701 of file NCV.hpp.
References NCVMatrix< T >::clear().
template<class T> virtual NCVMatrix< T >::~NCVMatrix () inline virtual
Definition at line 706 of file NCV.hpp.
Member Function Documentation
template<class T> T& NCVMatrix< T >::at (Ncv32u x, Ncv32u y) const inline
Definition at line 769 of file NCV.hpp.
References NCVMatrix< T >::_height, NCVMatrix< T >::_pitch, NCVMatrix< T >::_ptr, and NCVMatrix< T >::_width.
Referenced by NCVMatrixReuse< T >::NCVMatrixReuse().
template<class T> void NCVMatrix< T >::clear () inline
Definition at line 708 of file NCV.hpp.
References NCVMatrix< T >::_height, NCVMatrix< T >::_memtype, NCVMatrix< T >::_pitch, NCVMatrix< T >::_ptr, and NCVMatrix< T >::_width.
Referenced by NCVMatrix< T >::NCVMatrix(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), NCVMatrixReuse< T >::NCVMatrixReuse(), and NCVMatrixAlloc< T >::~NCVMatrixAlloc().
template<class T> NCVStatus NCVMatrix< T >::copy2D (NCVMatrix< T > & dst, NcvSize32u roi, cudaStream_t cuStream) const inline
Definition at line 751 of file NCV.hpp.
References NCVMatrix< T >::_memtype, NCVMatrix< T >::_pitch, NCVMatrix< T >::_ptr, NcvSize32u::height, NCVMatrix< T >::height(), NcvSize32u::width, and NCVMatrix< T >::width().
template<class T> NCVStatus NCVMatrix< T >::copySolid (NCVMatrix< T > & dst, cudaStream_t cuStream, size_t howMuch = 0) const inline
Definition at line 723 of file NCV.hpp.
References NCVMatrix< T >::_height, NCVMatrix< T >::_memtype, NCVMatrix< T >::_pitch, and NCVMatrix< T >::_ptr.
template<class T> Ncv32u NCVMatrix< T >::height () const inline
Definition at line 782 of file NCV.hpp.
References NCVMatrix< T >::_height.
Referenced by NCVMatrix< T >::copy2D(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVMatrixReuse< T >::NCVMatrixReuse().
template<class T> NCVMemoryType NCVMatrix< T >::memType (void) const inline
Definition at line 785 of file NCV.hpp.
References NCVMatrix< T >::_memtype.
Referenced by NCVMatrixReuse< T >::NCVMatrixReuse().
template<class T> Ncv32u NCVMatrix< T >::pitch () const inline
Definition at line 784 of file NCV.hpp.
References NCVMatrix< T >::_pitch.
Referenced by NCVMatrixAlloc< T >::NCVMatrixAlloc(), and NCVMatrixReuse< T >::NCVMatrixReuse().
template<class T> T* NCVMatrix< T >::ptr () const inline
Definition at line 780 of file NCV.hpp.
References NCVMatrix< T >::_ptr.
template<class T> NcvSize32u NCVMatrix< T >::size () const inline
Definition at line 783 of file NCV.hpp.
References NCVMatrix< T >::_height, and NCVMatrix< T >::_width.
template<class T> Ncv32u NCVMatrix< T >::stride () const inline
Definition at line 717 of file NCV.hpp.
References NCVMatrix< T >::_pitch.
template<class T> Ncv32u NCVMatrix< T >::width () const inline
Definition at line 781 of file NCV.hpp.
References NCVMatrix< T >::_width.
Referenced by NCVMatrix< T >::copy2D(), and NCVMatrixReuse< T >::NCVMatrixReuse().
Member Data Documentation
template<class T> Ncv32u NCVMatrix< T >::_height protected
Definition at line 791 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrix< T >::copySolid(), NCVMatrix< T >::height(), NCVMatrixReuse< T >::NCVMatrixReuse(), and NCVMatrix< T >::size().
template<class T> NCVMemoryType NCVMatrix< T >::_memtype protected
Definition at line 793 of file NCV.hpp.
Referenced by NCVMatrix< T >::clear(), NCVMatrix< T >::copy2D(), NCVMatrix< T >::copySolid(), NCVMatrix< T >::memType(), and NCVMatrixReuse< T >::NCVMatrixReuse().
template<class T> Ncv32u NCVMatrix< T >::_pitch protected
Definition at line 792 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrix< T >::copy2D(), NCVMatrix< T >::copySolid(), NCVMatrixReuse< T >::NCVMatrixReuse(), NCVMatrix< T >::pitch(), and NCVMatrix< T >::stride().
template<class T> T* NCVMatrix< T >::_ptr protected
Definition at line 789 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrix< T >::copy2D(), NCVMatrix< T >::copySolid(), NCVMatrixAlloc< T >::NCVMatrixAlloc(), NCVMatrixReuse< T >::NCVMatrixReuse(), and NCVMatrix< T >::ptr().
template<class T> Ncv32u NCVMatrix< T >::_width protected
Definition at line 790 of file NCV.hpp.
Referenced by NCVMatrix< T >::at(), NCVMatrix< T >::clear(), NCVMatrixReuse< T >::NCVMatrixReuse(), NCVMatrix< T >::size(), and NCVMatrix< T >::width().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/gpu/people/src/cuda/nvidia/NCV.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:31