Point Cloud Library (PCL): pcl::geometry::FaceIndex Class Reference
pcl::geometry::FaceIndex Class Reference
Module geometry
Index used to access elements in the half-edge mesh.
#include <pcl/geometry/mesh_indices.h>
Public Types
typedef boost::totally_ordered
< pcl::geometry::FaceIndex,
boost::unit_steppable
< pcl::geometry::FaceIndex,
boost::additive
< pcl::geometry::FaceIndex > > > Base
typedef pcl::geometry::FaceIndex Self
Public Member Functions
FaceIndex ()
Constructor.
FaceIndex (const int index)
Constructor.
bool isValid () const
Returns true if the index is valid.
void invalidate ()
Invalidate the index.
int get () const
Get the index.
void set (const int index)
Set the index.
bool operator< (const Self &other) const
Comparison operators (with boost::operators): < > <= >=.
bool operator== (const Self &other) const
Comparison operators (with boost::operators): == !=.
Self & operator++ ()
Increment operators (with boost::operators): ++ (pre and post)
Self & operator-- ()
Decrement operators (with boost::operators): -- (pre and post)
Self & operator+= (const Self &other)
Addition operators (with boost::operators): + +=.
Self & operator-= (const Self &other)
Subtraction operators (with boost::operators): - -=.
Friends
std::istream & operator>> (std::istream &is, pcl::geometry::FaceIndex &index)
istream operator.
Detailed Description
Index used to access elements in the half-edge mesh.
It is basically just a wrapper around an integer with a few added methods.
Author
Martin Saelzle
Definition at line 479 of file mesh_indices.h.
Member Typedef Documentation
typedef boost::totally_ordered<pcl::geometry::FaceIndex, boost::unit_steppable <pcl::geometry::FaceIndex, boost::additive <pcl::geometry::FaceIndex> > > pcl::geometry::FaceIndex::Base
Definition at line 489 of file mesh_indices.h.
typedef pcl::geometry::FaceIndex pcl::geometry::FaceIndex::Self
Definition at line 490 of file mesh_indices.h.
Constructor & Destructor Documentation
pcl::geometry::FaceIndex::FaceIndex () inline
Constructor.
Initializes with an invalid index.
Definition at line 493 of file mesh_indices.h.
pcl::geometry::FaceIndex::FaceIndex (const int index) inline explicit
Constructor.
Parameters
[in] index The integer index.
Definition at line 501 of file mesh_indices.h.
Member Function Documentation
int pcl::geometry::FaceIndex::get () const inline
Get the index.
Definition at line 522 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::getFace(), operator+=(), operator-=(), operator<(), pcl::geometry::operator<<(), operator==(), and pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::setFace().
void pcl::geometry::FaceIndex::invalidate () inline
Invalidate the index.
Definition at line 515 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::deleteFace().
bool pcl::geometry::FaceIndex::isValid () const inline
Returns true if the index is valid.
Definition at line 508 of file mesh_indices.h.
Referenced by pcl::geometry::TriangleMesh< MeshTraitsT >::addTrianglePair(), and pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::deleteVertex().
Self& pcl::geometry::FaceIndex::operator++ () inline
Increment operators (with boost::operators): ++ (pre and post)
Definition at line 550 of file mesh_indices.h.
Self& pcl::geometry::FaceIndex::operator+= (const Self & other) inline
Addition operators (with boost::operators): + +=.
Definition at line 566 of file mesh_indices.h.
References get().
Self& pcl::geometry::FaceIndex::operator-- () inline
Decrement operators (with boost::operators): -- (pre and post)
Definition at line 558 of file mesh_indices.h.
Self& pcl::geometry::FaceIndex::operator-= (const Self & other) inline
Subtraction operators (with boost::operators): - -=.
Definition at line 574 of file mesh_indices.h.
References get().
bool pcl::geometry::FaceIndex::operator< (const Self & other) const inline
Comparison operators (with boost::operators): < > <= >=.
Definition at line 536 of file mesh_indices.h.
References get().
bool pcl::geometry::FaceIndex::operator== (const Self & other) const inline
Comparison operators (with boost::operators): == !=.
Definition at line 543 of file mesh_indices.h.
References get().
void pcl::geometry::FaceIndex::set (const int index) inline
Set the index.
Definition at line 529 of file mesh_indices.h.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & is, pcl::geometry::FaceIndex & index) friend
istream operator.
Definition at line 598 of file mesh_indices.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/geometry/include/pcl/geometry/mesh_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:59