Point Cloud Library (PCL): pcl::MaskMap Class Reference
pcl::MaskMap Class Reference
#include <pcl/recognition/mask_map.h>
Public Member Functions
MaskMap ()
MaskMap (size_t width, size_t height)
virtual ~MaskMap ()
void resize (size_t width, size_t height)
size_t getWidth () const
size_t getHeight () const
unsigned char * getData ()
const unsigned char * getData () const
void set (const size_t x, const size_t y)
void unset (const size_t x, const size_t y)
bool isSet (const size_t x, const size_t y) const
void reset ()
unsigned char & operator() (const size_t x, const size_t y)
const unsigned char & operator() (const size_t x, const size_t y) const
void erode (MaskMap &eroded_mask) const
Static Public Member Functions
static void getDifferenceMask (const MaskMap &mask0, const MaskMap &mask1, MaskMap &diff_mask)
Detailed Description
Definition at line 47 of file mask_map.h.
Constructor & Destructor Documentation
pcl::MaskMap::MaskMap ()
pcl::MaskMap::MaskMap (size_t width, size_t height)
virtual pcl::MaskMap::~MaskMap () virtual
Member Function Documentation
void pcl::MaskMap::erode (MaskMap & eroded_mask) const
unsigned char* pcl::MaskMap::getData () inline
Definition at line 64 of file mask_map.h.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), and pcl::SurfaceNormalModality< PointInT >::computeDistanceMap().
const unsigned char* pcl::MaskMap::getData () const inline
Definition at line 67 of file mask_map.h.
static void pcl::MaskMap::getDifferenceMask (const MaskMap & mask0, const MaskMap & mask1, MaskMap & diff_mask) static
Referenced by pcl::ColorGradientModality< PointInT >::extractFeatures().
size_t pcl::MaskMap::getHeight () const inline
Definition at line 61 of file mask_map.h.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), pcl::SurfaceNormalModality< PointInT >::computeDistanceMap(), pcl::ColorGradientModality< PointInT >::erode(), pcl::ColorGradientModality< PointInT >::extractAllFeatures(), pcl::SurfaceNormalModality< PointInT >::extractAllFeatures(), pcl::ColorModality< PointInT >::extractFeatures(), pcl::ColorGradientModality< PointInT >::extractFeatures(), and pcl::SurfaceNormalModality< PointInT >::extractFeatures().
size_t pcl::MaskMap::getWidth () const inline
Definition at line 58 of file mask_map.h.
Referenced by pcl::ColorModality< PointInT >::computeDistanceMap(), pcl::SurfaceNormalModality< PointInT >::computeDistanceMap(), pcl::ColorGradientModality< PointInT >::erode(), pcl::ColorGradientModality< PointInT >::extractAllFeatures(), pcl::SurfaceNormalModality< PointInT >::extractAllFeatures(), pcl::ColorModality< PointInT >::extractFeatures(), pcl::ColorGradientModality< PointInT >::extractFeatures(), and pcl::SurfaceNormalModality< PointInT >::extractFeatures().
bool pcl::MaskMap::isSet (const size_t x, const size_t y) const inline
Definition at line 87 of file mask_map.h.
unsigned char& pcl::MaskMap::operator() (const size_t x, const size_t y) inline
Definition at line 99 of file mask_map.h.
const unsigned char& pcl::MaskMap::operator() (const size_t x, const size_t y) const inline
Definition at line 105 of file mask_map.h.
void pcl::MaskMap::reset () inline
Definition at line 93 of file mask_map.h.
void pcl::MaskMap::resize (size_t width, size_t height)
Referenced by pcl::ColorGradientModality< PointInT >::erode().
void pcl::MaskMap::set (const size_t x, const size_t y) inline
Definition at line 75 of file mask_map.h.
void pcl::MaskMap::unset (const size_t x, const size_t y) inline
Definition at line 81 of file mask_map.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/recognition/include/pcl/recognition/mask_map.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:36