Point Cloud Library (PCL): pcl::ConstCloudIterator< PointT > Class Template Reference
pcl::ConstCloudIterator< PointT > Class Template Reference
Iterator class for point clouds with or without given indices.
#include <pcl/cloud_iterator.h>
Classes
class ConstIteratorIdx
class DefaultConstIterator
Public Member Functions
ConstCloudIterator (const PointCloud< PointT > &cloud)
ConstCloudIterator (const PointCloud< PointT > &cloud, const std::vector< int > &indices)
ConstCloudIterator (const PointCloud< PointT > &cloud, const PointIndices &indices)
ConstCloudIterator (const PointCloud< PointT > &cloud, const Correspondences &corrs, bool source)
~ConstCloudIterator ()
void operator++ ()
void operator++ (int)
const PointT & operator* () const
const PointT * operator-> () const
unsigned getCurrentPointIndex () const
unsigned getCurrentIndex () const
size_t size () const
Size of the range the iterator is going through.
void reset ()
bool isValid () const
operator bool () const
Detailed Description
template<typename PointT>
class pcl::ConstCloudIterator< PointT >
Iterator class for point clouds with or without given indices.
Author
Suat Gedikli
Definition at line 121 of file cloud_iterator.h.
Constructor & Destructor Documentation
template<class PointT > pcl::ConstCloudIterator< PointT >::ConstCloudIterator (const PointCloud< PointT > & cloud)
Definition at line 445 of file cloud_iterator.hpp.
template<class PointT > pcl::ConstCloudIterator< PointT >::ConstCloudIterator (const PointCloud< PointT > & cloud, const std::vector< int > & indices)
Definition at line 452 of file cloud_iterator.hpp.
template<class PointT > pcl::ConstCloudIterator< PointT >::ConstCloudIterator (const PointCloud< PointT > & cloud, const PointIndices & indices)
Definition at line 460 of file cloud_iterator.hpp.
template<class PointT > pcl::ConstCloudIterator< PointT >::ConstCloudIterator (const PointCloud< PointT > & cloud, const Correspondences & corrs, bool source)
Definition at line 468 of file cloud_iterator.hpp.
template<class PointT > pcl::ConstCloudIterator< PointT >::~ConstCloudIterator ()
Definition at line 488 of file cloud_iterator.hpp.
Member Function Documentation
template<class PointT > unsigned pcl::ConstCloudIterator< PointT >::getCurrentIndex () const
Definition at line 530 of file cloud_iterator.hpp.
template<class PointT > unsigned pcl::ConstCloudIterator< PointT >::getCurrentPointIndex () const
Definition at line 523 of file cloud_iterator.hpp.
Referenced by pcl::estimateProjectionMatrix().
template<class PointT > bool pcl::ConstCloudIterator< PointT >::isValid () const
Definition at line 551 of file cloud_iterator.hpp.
Referenced by pcl::compute3DCentroid(), pcl::demeanPointCloud(), pcl::registration::TransformationEstimationPointToPlaneLLS< PointSource, PointTarget, Scalar >::estimateRigidTransformation(), pcl::registration::TransformationEstimationPointToPlaneLLSWeighted< PointSource, PointTarget, Scalar >::estimateRigidTransformation(), and pcl::ConstCloudIterator< PointT >::operator bool().
template<typename PointT> pcl::ConstCloudIterator< PointT >::operator bool () const inline
Definition at line 153 of file cloud_iterator.h.
References pcl::ConstCloudIterator< PointT >::isValid().
template<class PointT > const PointT & pcl::ConstCloudIterator< PointT >::operator* () const
Definition at line 509 of file cloud_iterator.hpp.
template<class PointT > void pcl::ConstCloudIterator< PointT >::operator++ ()
Definition at line 495 of file cloud_iterator.hpp.
template<class PointT > void pcl::ConstCloudIterator< PointT >::operator++ (int)
Definition at line 502 of file cloud_iterator.hpp.
template<class PointT > const PointT * pcl::ConstCloudIterator< PointT >::operator-> () const
Definition at line 516 of file cloud_iterator.hpp.
template<class PointT > void pcl::ConstCloudIterator< PointT >::reset ()
Definition at line 544 of file cloud_iterator.hpp.
Referenced by pcl::demeanPointCloud(), pcl::registration::TransformationEstimation2D< PointSource, PointTarget, Scalar >::estimateRigidTransformation(), pcl::registration::TransformationEstimationSVD< PointSource, PointTarget, Scalar >::estimateRigidTransformation(), and pcl::registration::TransformationEstimation3Point< PointSource, PointTarget, Scalar >::estimateRigidTransformation().
template<class PointT > size_t pcl::ConstCloudIterator< PointT >::size () const
Size of the range the iterator is going through.
Depending on how the ConstCloudIterator was constructed this is the size of the cloud or indices/correspondences.
Definition at line 537 of file cloud_iterator.hpp.
Referenced by pcl::registration::TransformationEstimationDQ< PointSource, PointTarget, Scalar >::estimateRigidTransformation(), pcl::registration::TransformationEstimationDualQuaternion< PointSource, PointTarget, Scalar >::estimateRigidTransformation(), and pcl::registration::TransformationEstimationSVD< PointSource, PointTarget, Scalar >::estimateRigidTransformation().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/cloud_iterator.h
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/impl/cloud_iterator.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:53