Point Cloud Library (PCL): pcl::StopWatch Class Reference
pcl::StopWatch Class Reference
Module common
Simple stopwatch.
#include <pcl/common/time.h>
Public Member Functions
StopWatch ()
Constructor.
virtual ~StopWatch ()
Destructor.
double getTime ()
Retrieve the time in milliseconds spent since the last call to reset().
double getTimeSeconds ()
Retrieve the time in seconds spent since the last call to reset().
void reset ()
Reset the stopwatch to 0.
Protected Attributes
boost::posix_time::ptime start_time_
Detailed Description
Simple stopwatch.
Definition at line 65 of file time.h.
Constructor & Destructor Documentation
pcl::StopWatch::StopWatch () inline
Constructor.
Definition at line 69 of file time.h.
virtual pcl::StopWatch::~StopWatch () inline virtual
Destructor.
Definition at line 74 of file time.h.
Member Function Documentation
double pcl::StopWatch::getTime () inline
Retrieve the time in milliseconds spent since the last call to reset().
Definition at line 78 of file time.h.
References start_time_.
Referenced by getTimeSeconds(), and pcl::ScopeTime::~ScopeTime().
double pcl::StopWatch::getTimeSeconds () inline
Retrieve the time in seconds spent since the last call to reset().
Definition at line 86 of file time.h.
References getTime().
Referenced by pcl::registration::FPCSInitialAlignment< PointSource, PointTarget, NormalT, Scalar >::computeTransformation(), and pcl::EventFrequency::event().
void pcl::StopWatch::reset () inline
Reset the stopwatch to 0.
Definition at line 93 of file time.h.
References start_time_.
Referenced by pcl::EventFrequency::EventFrequency(), and pcl::EventFrequency::reset().
Member Data Documentation
boost::posix_time::ptime pcl::StopWatch::start_time_ protected
Definition at line 99 of file time.h.
Referenced by getTime(), reset(), and pcl::ScopeTime::ScopeTime().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/common/time.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:54