Point Cloud Library (PCL): pcl::poisson::PPolynomial< Degree > Class Template Reference
pcl::poisson::PPolynomial< Degree > Class Template Reference
#include <pcl/surface/3rdparty/poisson4/ppolynomial.h>
Public Member Functions
PPolynomial (void)
PPolynomial (const PPolynomial< Degree > &p)
~PPolynomial (void)
PPolynomial & operator= (const PPolynomial &p)
int size (void) const
void set (size_t size)
void set (StartingPolynomial< Degree > *sps, int count)
void reset (size_t newSize)
double operator() (double t) const
double integral (double tMin, double tMax) const
double Integral (void) const
template<int Degree2>
PPolynomial< Degree > & operator= (const PPolynomial< Degree2 > &p)
PPolynomial operator+ (const PPolynomial &p) const
PPolynomial operator- (const PPolynomial &p) const
template<int Degree2>
PPolynomial< Degree+Degree2 > operator* (const Polynomial< Degree2 > &p) const
template<int Degree2>
PPolynomial< Degree+Degree2 > operator* (const PPolynomial< Degree2 > &p) const
PPolynomial & operator+= (double s)
PPolynomial & operator-= (double s)
PPolynomial & operator*= (double s)
PPolynomial & operator/= (double s)
PPolynomial operator+ (double s) const
PPolynomial operator- (double s) const
PPolynomial operator* (double s) const
PPolynomial operator/ (double s) const
PPolynomial & addScaled (const PPolynomial &poly, double scale)
PPolynomial scale (double s) const
PPolynomial shift (double t) const
PPolynomial< Degree-1 > derivative (void) const
PPolynomial< Degree+1 > integral (void) const
void getSolutions (double c, std::vector< double > &roots, double EPS, double min=-DBL_MAX, double max=DBL_MAX) const
void printnl (void) const
PPolynomial< Degree+1 > MovingAverage (double radius)
void write (FILE *fp, int samples, double min, double max) const
template<>
PPolynomial< 0 > BSpline (double radius)
Static Public Member Functions
static PPolynomial BSpline (double radius=0.5)
Public Attributes
size_t polyCount
StartingPolynomial< Degree > * polys
Detailed Description
template<int Degree>
class pcl::poisson::PPolynomial< Degree >
Definition at line 58 of file ppolynomial.h.
Constructor & Destructor Documentation
template<int Degree> pcl::poisson::PPolynomial< Degree >::PPolynomial (void)
Definition at line 83 of file ppolynomial.hpp.
template<int Degree> pcl::poisson::PPolynomial< Degree >::PPolynomial (const PPolynomial< Degree > & p)
Definition at line 88 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, and pcl::poisson::PPolynomial< Degree >::polys.
template<int Degree> pcl::poisson::PPolynomial< Degree >::~PPolynomial (void)
Definition at line 96 of file ppolynomial.hpp.
Member Function Documentation
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::addScaled (const PPolynomial< Degree > & poly, double scale)
Definition at line 217 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::StartingPolynomial< Degree >::start.
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::BSpline (double radius = 0.5) static
Definition at line 387 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::MovingAverage().
Referenced by pcl::poisson::BSplineData< Degree, Real >::set().
template<> PPolynomial< 0 > pcl::poisson::PPolynomial< 0 >::BSpline (double radius)
Definition at line 374 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> PPolynomial< Degree-1 > pcl::poisson::PPolynomial< Degree >::derivative (void) const
Definition at line 283 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::set().
Referenced by pcl::poisson::BSplineData< Degree, Real >::setValueTables(), and pcl::poisson::FunctionData< Degree, Real >::setValueTables().
template<int Degree> void pcl::poisson::PPolynomial< Degree >::getSolutions (double c, std::vector< double > & roots, double EPS, double min = -DBL_MAX, double max = DBL_MAX) const
Definition at line 412 of file ppolynomial.hpp.
References pcl::poisson::Polynomial< Degree >::getSolutions(), and pcl::poisson::Polynomial< Degree >::setZero().
template<int Degree> double pcl::poisson::PPolynomial< Degree >::integral (double tMin, double tMax) const
Definition at line 162 of file ppolynomial.hpp.
template<int Degree> double pcl::poisson::PPolynomial< Degree >::Integral (void) const
Definition at line 181 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree+1 > pcl::poisson::PPolynomial< Degree >::integral (void) const
Definition at line 293 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> PPolynomial< Degree+1 > pcl::poisson::PPolynomial< Degree >::MovingAverage (double radius)
Definition at line 392 of file ppolynomial.hpp.
References pcl::poisson::Polynomial< Degree >::integral(), pcl::poisson::StartingPolynomial< Degree >::p, pcl::poisson::PPolynomial< Degree >::set(), pcl::poisson::Polynomial< Degree >::shift(), and pcl::poisson::StartingPolynomial< Degree >::start.
Referenced by pcl::poisson::PPolynomial< Degree >::BSpline(), pcl::poisson::BSplineData< Degree, Real >::setValueTables(), and pcl::poisson::FunctionData< Degree, Real >::setValueTables().
template<int Degree> double pcl::poisson::PPolynomial< Degree >::operator() (double t) const
Definition at line 154 of file ppolynomial.hpp.
template<int Degree> template<int Degree2> PPolynomial< Degree+Degree2 > pcl::poisson::PPolynomial< Degree >::operator* (const Polynomial< Degree2 > & p) const
Definition at line 257 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> template<int Degree2> PPolynomial< Degree+Degree2 > pcl::poisson::PPolynomial< Degree >::operator* (const PPolynomial< Degree2 > & p) const
Definition at line 240 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator* (double s) const
Definition at line 335 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator*= (double s)
Definition at line 309 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator+ (const PPolynomial< Degree > & p) const
Definition at line 183 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator+ (double s) const
Definition at line 321 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator+= (double s)
Definition at line 305 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator- (const PPolynomial< Degree > & p) const
Definition at line 200 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator- (double s) const
Definition at line 328 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator-= (double s)
Definition at line 307 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::operator/ (double s) const
Definition at line 342 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator/= (double s)
Definition at line 315 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator= (const PPolynomial< Degree > & p)
Definition at line 136 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, and pcl::poisson::PPolynomial< Degree >::polys.
template<int Degree> template<int Degree2> PPolynomial< Degree > & pcl::poisson::PPolynomial< Degree >::operator= (const PPolynomial< Degree2 > & p)
Definition at line 144 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polyCount, and pcl::poisson::PPolynomial< Degree >::polys.
template<int Degree> void pcl::poisson::PPolynomial< Degree >::printnl (void) const
Definition at line 350 of file ppolynomial.hpp.
References pcl::poisson::Polynomial< Degree >::printnl().
template<int Degree> void pcl::poisson::PPolynomial< Degree >::reset (size_t newSize)
Definition at line 129 of file ppolynomial.hpp.
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::scale (double s) const
Definition at line 267 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> void pcl::poisson::PPolynomial< Degree >::set (size_t size)
Definition at line 117 of file ppolynomial.hpp.
Referenced by pcl::poisson::PPolynomial< Degree >::BSpline(), pcl::poisson::PPolynomial< Degree >::derivative(), pcl::poisson::PPolynomial< Degree >::integral(), pcl::poisson::PPolynomial< Degree >::MovingAverage(), pcl::poisson::PPolynomial< Degree >::operator*(), pcl::poisson::PPolynomial< Degree >::operator+(), pcl::poisson::PPolynomial< Degree >::operator-(), pcl::poisson::PPolynomial< Degree >::scale(), and pcl::poisson::PPolynomial< Degree >::shift().
template<int Degree> void pcl::poisson::PPolynomial< Degree >::set (StartingPolynomial< Degree > * sps, int count)
Definition at line 102 of file ppolynomial.hpp.
References pcl::poisson::StartingPolynomial< Degree >::p.
template<int Degree> PPolynomial< Degree > pcl::poisson::PPolynomial< Degree >::shift (double t) const
Definition at line 275 of file ppolynomial.hpp.
References pcl::poisson::PPolynomial< Degree >::polys, and pcl::poisson::PPolynomial< Degree >::set().
template<int Degree> int pcl::poisson::PPolynomial< Degree >::size (void) const
Definition at line 114 of file ppolynomial.hpp.
template<int Degree> void pcl::poisson::PPolynomial< Degree >::write (FILE * fp, int samples, double min, double max) const
Definition at line 431 of file ppolynomial.hpp.
Member Data Documentation
template<int Degree> size_t pcl::poisson::PPolynomial< Degree >::polyCount
Definition at line 61 of file ppolynomial.h.
Referenced by pcl::poisson::PPolynomial< Degree >::addScaled(), pcl::poisson::PPolynomial< Degree >::operator*(), pcl::poisson::PPolynomial< Degree >::operator+(), pcl::poisson::PPolynomial< Degree >::operator-(), pcl::poisson::PPolynomial< Degree >::operator=(), and pcl::poisson::PPolynomial< Degree >::PPolynomial().
template<int Degree> StartingPolynomial<Degree>* pcl::poisson::PPolynomial< Degree >::polys
Definition at line 62 of file ppolynomial.h.
Referenced by pcl::poisson::PPolynomial< Degree >::addScaled(), pcl::poisson::PPolynomial< Degree >::BSpline(), pcl::poisson::PPolynomial< Degree >::integral(), pcl::poisson::PPolynomial< Degree >::operator*(), pcl::poisson::PPolynomial< Degree >::operator+(), pcl::poisson::PPolynomial< Degree >::operator-(), pcl::poisson::PPolynomial< Degree >::operator=(), pcl::poisson::PPolynomial< Degree >::PPolynomial(), pcl::poisson::PPolynomial< Degree >::scale(), and pcl::poisson::PPolynomial< Degree >::shift().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.h
/home/travis/build/PointCloudLibrary/pcl/surface/include/pcl/surface/3rdparty/poisson4/ppolynomial.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:16