Point Cloud Library (PCL): pcl::FilterIndices< PointT > Class Template Reference
pcl::FilterIndices< PointT > Class Template Reference abstract
Module filters
FilterIndices represents the base class for filters that are about binary point removal.
#include <pcl/filters/filter_indices.h>
Public Types
typedef pcl::PointCloud< PointT > PointCloud
typedef boost::shared_ptr
< FilterIndices< PointT > > Ptr
typedef boost::shared_ptr
< const FilterIndices< PointT > > ConstPtr
Public Types inherited from pcl::Filter< PointT >
typedef boost::shared_ptr
< Filter< PointT > > Ptr
typedef boost::shared_ptr
< const Filter< PointT > > ConstPtr
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
Public Types inherited from pcl::PCLBase< PointT >
typedef pcl::PointCloud< PointT > PointCloud
typedef PointCloud::Ptr PointCloudPtr
typedef PointCloud::ConstPtr PointCloudConstPtr
typedef boost::shared_ptr
< PointIndices > PointIndicesPtr
typedef boost::shared_ptr
< PointIndices const > PointIndicesConstPtr
Public Member Functions
FilterIndices (bool extract_removed_indices=false)
Constructor.
virtual ~FilterIndices ()
Empty virtual destructor.
void filter (PointCloud &output)
void filter (std::vector< int > &indices)
Calls the filtering method and returns the filtered point cloud indices.
void setNegative (bool negative)
Set whether the regular conditions for points filtering should apply, or the inverted conditions.
bool getNegative () const
Get whether the regular conditions for points filtering should apply, or the inverted conditions.
void setKeepOrganized (bool keep_organized)
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
bool getKeepOrganized () const
Get whether the filtered points should be kept and set to the value given through setUserFilterValue (default = NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
void setUserFilterValue (float value)
Provide a value that the filtered points should be set to instead of removing them.
Public Member Functions inherited from pcl::Filter< PointT >
Filter (bool extract_removed_indices=false)
Empty constructor.
virtual ~Filter ()
Empty destructor.
IndicesConstPtr const getRemovedIndices () const
Get the point indices being removed.
void getRemovedIndices (PointIndices &pi)
Get the point indices being removed.
void filter (PointCloud &output)
Calls the filtering method and returns the filtered dataset in output.
Public Member Functions inherited from pcl::PCLBase< PointT >
PCLBase ()
Empty constructor.
PCLBase (const PCLBase &base)
Copy constructor.
virtual ~PCLBase ()
Destructor.
virtual void setInputCloud (const PointCloudConstPtr &cloud)
Provide a pointer to the input dataset.
PointCloudConstPtr const getInputCloud () const
Get a pointer to the input point cloud dataset.
virtual void setIndices (const IndicesPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const IndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (const PointIndicesConstPtr &indices)
Provide a pointer to the vector of indices that represents the input data.
virtual void setIndices (size_t row_start, size_t col_start, size_t nb_rows, size_t nb_cols)
Set the indices for the points laying within an interest region of the point cloud.
IndicesPtr const getIndices ()
Get a pointer to the vector of indices used.
IndicesConstPtr const getIndices () const
Get a pointer to the vector of indices used.
const PointT & operator[] (size_t pos) const
Override PointCloud operator[] to shorten code.
Protected Member Functions
virtual void applyFilter (std::vector< int > &indices)=0
Abstract filter method for point cloud indices.
virtual void applyFilter (PointCloud &output)=0
Abstract filter method for point cloud.
Protected Member Functions inherited from pcl::Filter< PointT >
const std::string & getClassName () const
Get a string representation of the name of this class.
Protected Member Functions inherited from pcl::PCLBase< PointT >
bool initCompute ()
This method should get called before starting the actual computation.
bool deinitCompute ()
This method should get called after finishing the actual computation.
Protected Attributes
bool negative_
False = normal filter behavior (default), true = inverted behavior.
bool keep_organized_
False = remove points (default), true = redefine points, keep structure.
float user_filter_value_
The user given value that the filtered point dimensions should be set to (default = NaN).
Protected Attributes inherited from pcl::Filter< PointT >
IndicesPtr removed_indices_
Indices of the points that are removed.
std::string filter_name_
The filter name.
bool extract_removed_indices_
Set to true if we want to return the indices of the removed points.
Protected Attributes inherited from pcl::PCLBase< PointT >
PointCloudConstPtr input_
The input point cloud dataset.
IndicesPtr indices_
A pointer to the vector of point indices to use.
bool use_indices_
Set to true if point indices are used.
bool fake_indices_
If no set of indices are given, we construct a set of fake indices that mimic the input PointCloud.
Detailed Description
template<typename PointT>
class pcl::FilterIndices< PointT >
FilterIndices represents the base class for filters that are about binary point removal.
All derived classes have to implement the filter (PointCloud &output) and the filter (std::vector<int> &indices) methods. Ideally they also make use of the negative_, keep_organized_ and extract_removed_indices_ systems. The distinguishment between the negative_ and extract_removed_indices_ systems only makes sense if the class automatically filters non-finite entries in the filtering methods (recommended).
Author
Justin Rosen
Definition at line 75 of file filter_indices.h.
Member Typedef Documentation
template<typename PointT> typedef boost::shared_ptr< const FilterIndices<PointT> > pcl::FilterIndices< PointT >::ConstPtr
Definition at line 82 of file filter_indices.h.
template<typename PointT> typedef pcl::PointCloud<PointT> pcl::FilterIndices< PointT >::PointCloud
Definition at line 79 of file filter_indices.h.
template<typename PointT> typedef boost::shared_ptr< FilterIndices<PointT> > pcl::FilterIndices< PointT >::Ptr
Definition at line 81 of file filter_indices.h.
Constructor & Destructor Documentation
template<typename PointT> pcl::FilterIndices< PointT >::FilterIndices (bool extract_removed_indices = false) inline
Constructor.
Parameters
[in] extract_removed_indices Set to true if you want to be able to extract the indices of points being removed (default = false).
Definition at line 88 of file filter_indices.h.
template<typename PointT> virtual pcl::FilterIndices< PointT >::~FilterIndices () inline virtual
Empty virtual destructor.
Definition at line 98 of file filter_indices.h.
Member Function Documentation
template<typename PointT> virtual void pcl::FilterIndices< PointT >::applyFilter (std::vector< int > & indices) protected pure virtual
Abstract filter method for point cloud indices.
Implemented in pcl::FrustumCulling< PointT >, pcl::ModelOutlierRemoval< PointT >, pcl::PassThrough< PointT >, pcl::PassThrough< PointInT >, pcl::CropBox< PointT >, pcl::NormalSpaceSampling< PointT, NormalT >, pcl::StatisticalOutlierRemoval< PointT >, pcl::RadiusOutlierRemoval< PointT >, pcl::CovarianceSampling< PointT, PointNT >, pcl::CropHull< PointT >, pcl::RandomSample< PointT >, pcl::RandomSample< pcl::pcl::PCLPointCloud2 >, pcl::ExtractIndices< PointT >, pcl::ShadowPoints< PointT, NormalT >, pcl::GridMinimum< PointT >, and pcl::LocalMaximum< PointT >.
Referenced by pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::filter().
template<typename PointT> virtual void pcl::FilterIndices< PointT >::applyFilter (PointCloud & output) protected pure virtual
Abstract filter method for point cloud.
Implements pcl::Filter< PointT >.
Implemented in pcl::FrustumCulling< PointT >, pcl::ModelOutlierRemoval< PointT >, pcl::PassThrough< PointT >, pcl::PassThrough< PointInT >, pcl::CropBox< PointT >, pcl::NormalSpaceSampling< PointT, NormalT >, pcl::StatisticalOutlierRemoval< PointT >, pcl::RadiusOutlierRemoval< PointT >, pcl::CovarianceSampling< PointT, PointNT >, pcl::CropHull< PointT >, pcl::RandomSample< PointT >, pcl::RandomSample< pcl::pcl::PCLPointCloud2 >, pcl::ExtractIndices< PointT >, pcl::ShadowPoints< PointT, NormalT >, pcl::GridMinimum< PointT >, and pcl::LocalMaximum< PointT >.
template<typename PointT> void pcl::FilterIndices< PointT >::filter (PointCloud & output) inline
Definition at line 103 of file filter_indices.h.
Referenced by pcl::people::GroundBasedPeopleDetectionApp< PointT >::compute(), and pcl::ism::ImplicitShapeModelEstimation< FeatureSize, PointT, NormalT >::simplifyCloud().
template<typename PointT> void pcl::FilterIndices< PointT >::filter (std::vector< int > & indices) inline
Calls the filtering method and returns the filtered point cloud indices.
Parameters
[out] indices the resultant filtered point cloud indices
Definition at line 112 of file filter_indices.h.
template<typename PointT> bool pcl::FilterIndices< PointT >::getKeepOrganized () const inline
Get whether the filtered points should be kept and set to the value given through setUserFilterValue (default = NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
Returns
The value of the internal keep_organized_ parameter; false = remove points (default), true = redefine points, keep structure.
Definition at line 156 of file filter_indices.h.
template<typename PointT> bool pcl::FilterIndices< PointT >::getNegative () const inline
Get whether the regular conditions for points filtering should apply, or the inverted conditions.
Returns
The value of the internal negative_ parameter; false = normal filter behavior (default), true = inverted behavior.
Definition at line 136 of file filter_indices.h.
template<typename PointT> void pcl::FilterIndices< PointT >::setKeepOrganized (bool keep_organized) inline
Set whether the filtered points should be kept and set to the value given through setUserFilterValue (default: NaN), or removed from the PointCloud, thus potentially breaking its organized structure.
Parameters
[in] keep_organized false = remove points (default), true = redefine points, keep structure.
Definition at line 146 of file filter_indices.h.
Referenced by pcl::tracking::ParticleFilterTracker< PointInT, StateT >::ParticleFilterTracker().
template<typename PointT> void pcl::FilterIndices< PointT >::setNegative (bool negative) inline
Set whether the regular conditions for points filtering should apply, or the inverted conditions.
Parameters
[in] negative false = normal filter behavior (default), true = inverted behavior.
Definition at line 127 of file filter_indices.h.
Referenced by pcl::people::GroundBasedPeopleDetectionApp< PointT >::compute().
template<typename PointT> void pcl::FilterIndices< PointT >::setUserFilterValue (float value) inline
Provide a value that the filtered points should be set to instead of removing them.
Used in conjunction with setKeepOrganized ().
Parameters
[in] value the user given value that the filtered point dimensions should be set to (default = NaN).
Definition at line 166 of file filter_indices.h.
Member Data Documentation
template<typename PointT> bool pcl::FilterIndices< PointT >::keep_organized_ protected
False = remove points (default), true = redefine points, keep structure.
Definition at line 180 of file filter_indices.h.
Referenced by pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::getKeepOrganized(), and pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::setKeepOrganized().
template<typename PointT> bool pcl::FilterIndices< PointT >::negative_ protected
False = normal filter behavior (default), true = inverted behavior.
Definition at line 177 of file filter_indices.h.
Referenced by pcl::PassThrough< PointInT >::getFilterLimitsNegative(), pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::getNegative(), pcl::PassThrough< PointInT >::setFilterLimitsNegative(), and pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::setNegative().
template<typename PointT> float pcl::FilterIndices< PointT >::user_filter_value_ protected
The user given value that the filtered point dimensions should be set to (default = NaN).
Definition at line 183 of file filter_indices.h.
Referenced by pcl::FilterIndices< pcl::pcl::PCLPointCloud2 >::setUserFilterValue().
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/filters/include/pcl/filters/filter_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:19