Point Cloud Library (PCL): pcl::poisson::Vector< T > Class Template Reference
pcl::poisson::Vector< T > Class Template Reference
#include <pcl/surface/3rdparty/poisson4/vector.h>
Public Member Functions
Vector ()
Vector (const Vector< T > &V)
Vector (size_t N)
Vector (size_t N, T *pV)
~Vector ()
const T & operator() (size_t i) const
T & operator() (size_t i)
const T & operator[] (size_t i) const
T & operator[] (size_t i)
void SetZero ()
size_t Dimensions () const
void Resize (size_t N)
Vector operator* (const T &A) const
Vector operator/ (const T &A) const
Vector operator- (const Vector &V) const
Vector operator+ (const Vector &V) const
Vector & operator*= (const T &A)
Vector & operator/= (const T &A)
Vector & operator+= (const Vector &V)
Vector & operator-= (const Vector &V)
Vector & AddScaled (const Vector &V, const T &scale)
Vector & SubtractScaled (const Vector &V, const T &scale)
Vector operator- () const
Vector & operator= (const Vector &V)
T Dot (const Vector &V) const
T Length () const
T Norm (size_t Ln) const
void Normalize ()
bool write (FILE *fp) const
bool write (const char *fileName) const
bool read (FILE *fp)
bool read (const char *fileName)
Static Public Member Functions
static void Add (const Vector &V1, const T &scale1, const Vector &V2, const T &scale2, Vector &Out)
static void Add (const Vector &V1, const T &scale1, const Vector &V2, Vector &Out)
Public Attributes
T * m_pV
Protected Attributes
size_t m_N
Detailed Description
template<class T>
class pcl::poisson::Vector< T >
Definition at line 41 of file vector.h.
Constructor & Destructor Documentation
template<class T > pcl::poisson::Vector< T >::Vector ()
Definition at line 42 of file vector.hpp.
template<class T > pcl::poisson::Vector< T >::Vector (const Vector< T > & V)
Definition at line 48 of file vector.hpp.
References pcl::poisson::Vector< T >::m_N, and pcl::poisson::Vector< T >::m_pV.
template<class T > pcl::poisson::Vector< T >::Vector (size_t N)
Definition at line 56 of file vector.hpp.
template<class T > pcl::poisson::Vector< T >::Vector (size_t N, T * pV)
Definition at line 74 of file vector.hpp.
template<class T > pcl::poisson::Vector< T >::~Vector ()
Definition at line 80 of file vector.hpp.
Member Function Documentation
template<class T > void pcl::poisson::Vector< T >::Add (const Vector< T > & V1, const T & scale1, const Vector< T > & V2, const T & scale2, Vector< T > & Out) static
Definition at line 169 of file vector.hpp.
References pcl::poisson::Vector< T >::m_N, and pcl::poisson::Vector< T >::m_pV.
template<class T > void pcl::poisson::Vector< T >::Add (const Vector< T > & V1, const T & scale1, const Vector< T > & V2, Vector< T > & Out) static
Definition at line 174 of file vector.hpp.
References pcl::poisson::Vector< T >::m_N, and pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > & pcl::poisson::Vector< T >::AddScaled (const Vector< T > & V, const T & scale)
Definition at line 153 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > size_t pcl::poisson::Vector< T >::Dimensions () const
Definition at line 89 of file vector.hpp.
Referenced by pcl::poisson::SparseSymmetricMatrix< T >::Multiply(), pcl::poisson::SparseSymmetricMatrix< T >::Solve(), and pcl::poisson::SparseMatrix< T >::SolveSymmetric().
template<class T > T pcl::poisson::Vector< T >::Dot (const Vector< T > & V) const
Definition at line 237 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
Referenced by pcl::poisson::SparseMatrix< T >::Solve().
template<class T > T pcl::poisson::Vector< T >::Length (void) const
Definition at line 229 of file vector.hpp.
template<class T > T pcl::poisson::Vector< T >::Norm (size_t Ln) const
Definition at line 214 of file vector.hpp.
template<class T > void pcl::poisson::Vector< T >::Normalize ()
Definition at line 222 of file vector.hpp.
template<class T > const T & pcl::poisson::Vector< T >::operator() (size_t i) const
Definition at line 93 of file vector.hpp.
template<class T > T & pcl::poisson::Vector< T >::operator() (size_t i)
Definition at line 99 of file vector.hpp.
template<class T > Vector< T > pcl::poisson::Vector< T >::operator* (const T & A) const
Definition at line 114 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > & pcl::poisson::Vector< T >::operator*= (const T & A)
Definition at line 122 of file vector.hpp.
template<class T > Vector< T > pcl::poisson::Vector< T >::operator+ (const Vector< T > & V) const
Definition at line 144 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > & pcl::poisson::Vector< T >::operator+= (const Vector< T > & V)
Definition at line 179 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > pcl::poisson::Vector< T >::operator- (const Vector< T > & V) const
Definition at line 187 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > pcl::poisson::Vector< T >::operator- (void) const
Definition at line 196 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > & pcl::poisson::Vector< T >::operator-= (const Vector< T > & V)
Definition at line 206 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > pcl::poisson::Vector< T >::operator/ (const T & A) const
Definition at line 129 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > Vector< T > & pcl::poisson::Vector< T >::operator/= (const T & A)
Definition at line 137 of file vector.hpp.
template<class T > Vector< T > & pcl::poisson::Vector< T >::operator= (const Vector< T > & V)
Definition at line 82 of file vector.hpp.
References pcl::poisson::Vector< T >::m_N, and pcl::poisson::Vector< T >::m_pV.
template<class T > const T & pcl::poisson::Vector< T >::operator[] (size_t i) const
Definition at line 104 of file vector.hpp.
template<class T > T & pcl::poisson::Vector< T >::operator[] (size_t i)
Definition at line 109 of file vector.hpp.
template<class T > bool pcl::poisson::Vector< T >::read (FILE * fp)
Definition at line 265 of file vector.hpp.
template<class T > bool pcl::poisson::Vector< T >::read (const char * fileName)
Definition at line 247 of file vector.hpp.
References pcl::read().
template<class T > void pcl::poisson::Vector< T >::Resize (size_t N)
Definition at line 63 of file vector.hpp.
Referenced by pcl::poisson::SparseSymmetricMatrix< T >::getDiagonal(), pcl::poisson::SparseMatrix< T >::Solve(), pcl::poisson::SparseSymmetricMatrix< T >::Solve(), and pcl::poisson::SparseMatrix< T >::SolveSymmetric().
template<class T > void pcl::poisson::Vector< T >::SetZero (void)
Definition at line 91 of file vector.hpp.
Referenced by pcl::poisson::SparseSymmetricMatrix< T >::Multiply(), pcl::poisson::SparseMatrix< T >::Solve(), pcl::poisson::SparseSymmetricMatrix< T >::Solve(), and pcl::poisson::SparseMatrix< T >::SolveSymmetric().
template<class T > Vector< T > & pcl::poisson::Vector< T >::SubtractScaled (const Vector< T > & V, const T & scale)
Definition at line 161 of file vector.hpp.
References pcl::poisson::Vector< T >::m_pV.
template<class T > bool pcl::poisson::Vector< T >::write (FILE * fp) const
Definition at line 274 of file vector.hpp.
template<class T > bool pcl::poisson::Vector< T >::write (const char * fileName) const
Definition at line 256 of file vector.hpp.
References pcl::write().
Member Data Documentation
template<class T> size_t pcl::poisson::Vector< T >::m_N protected
Definition at line 93 of file vector.h.
Referenced by pcl::poisson::Vector< T >::Add(), pcl::poisson::Vector< T >::operator=(), and pcl::poisson::Vector< T >::Vector().
template<class T> T* pcl::poisson::Vector< T >::m_pV
Definition at line 91 of file vector.h.
Referenced by pcl::poisson::Vector< T >::Add(), pcl::poisson::Vector< T >::AddScaled(), pcl::poisson::Vector< T >::Dot(), pcl::poisson::SparseMatrix< T >::Multiply(), pcl::poisson::SparseSymmetricMatrix< T >::Multiply(), pcl::poisson::Vector< T >::operator*(), pcl::poisson::Vector< T >::operator+(), pcl::poisson::Vector< T >::operator+=(), pcl::poisson::Vector< T >::operator-(), pcl::poisson::Vector< T >::operator-=(), pcl::poisson::Vector< T >::operator/(), pcl::poisson::Vector< T >::operator=(), pcl::poisson::SparseMatrix< T >::SolveSymmetric(), pcl::poisson::Vector< T >::SubtractScaled(), and pcl::poisson::Vector< T >::Vector().
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/surface/include/pcl/surface/3rdparty/poisson4/vector.h
/home/travis/build/PointCloudLibrary/pcl/surface/include/pcl/surface/3rdparty/poisson4/vector.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:16