Point Cloud Library (PCL): pcl::geometry::VertexIndex Class Reference
pcl::geometry::VertexIndex Class Reference
Module geometry
Index used to access elements in the half-edge mesh.
#include <pcl/geometry/mesh_indices.h>
Public Types
typedef boost::totally_ordered
< pcl::geometry::VertexIndex,
boost::unit_steppable
< pcl::geometry::VertexIndex,
boost::additive
< pcl::geometry::VertexIndex > > > Base
typedef pcl::geometry::VertexIndex Self
Public Member Functions
VertexIndex ()
Constructor.
VertexIndex (const int index)
Constructor.
bool isValid () const
Returns true if the index is valid.
void invalidate ()
Invalidate the index.
int get () const
Get the index.
void set (const int index)
Set the index.
bool operator< (const Self &other) const
Comparison operators (with boost::operators): < > <= >=.
bool operator== (const Self &other) const
Comparison operators (with boost::operators): == !=.
Self & operator++ ()
Increment operators (with boost::operators): ++ (pre and post)
Self & operator-- ()
Decrement operators (with boost::operators): -- (pre and post)
Self & operator+= (const Self &other)
Addition operators (with boost::operators): + +=.
Self & operator-= (const Self &other)
Subtraction operators (with boost::operators): - -=.
Friends
std::istream & operator>> (std::istream &is, pcl::geometry::VertexIndex &index)
istream operator.
Detailed Description
Index used to access elements in the half-edge mesh.
It is basically just a wrapper around an integer with a few added methods.
Author
Martin Saelzle
Definition at line 62 of file mesh_indices.h.
Member Typedef Documentation
typedef boost::totally_ordered<pcl::geometry::VertexIndex, boost::unit_steppable <pcl::geometry::VertexIndex, boost::additive <pcl::geometry::VertexIndex> > > pcl::geometry::VertexIndex::Base
Definition at line 72 of file mesh_indices.h.
typedef pcl::geometry::VertexIndex pcl::geometry::VertexIndex::Self
Definition at line 73 of file mesh_indices.h.
Constructor & Destructor Documentation
pcl::geometry::VertexIndex::VertexIndex () inline
Constructor.
Initializes with an invalid index.
Definition at line 76 of file mesh_indices.h.
pcl::geometry::VertexIndex::VertexIndex (const int index) inline explicit
Constructor.
Parameters
[in] index The integer index.
Definition at line 84 of file mesh_indices.h.
Member Function Documentation
int pcl::geometry::VertexIndex::get () const inline
Get the index.
Definition at line 105 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::getVertex(), operator+=(), operator-=(), operator<(), pcl::geometry::operator<<(), operator==(), and pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::setVertex().
void pcl::geometry::VertexIndex::invalidate () inline
Invalidate the index.
Definition at line 98 of file mesh_indices.h.
Referenced by pcl::geometry::MeshBase< QuadMesh< MeshTraitsT >, MeshTraitsT, QuadMeshTag >::markDeleted().
bool pcl::geometry::VertexIndex::isValid () const inline
Returns true if the index is valid.
Definition at line 91 of file mesh_indices.h.
Self& pcl::geometry::VertexIndex::operator++ () inline
Increment operators (with boost::operators): ++ (pre and post)
Definition at line 133 of file mesh_indices.h.
Self& pcl::geometry::VertexIndex::operator+= (const Self & other) inline
Addition operators (with boost::operators): + +=.
Definition at line 149 of file mesh_indices.h.
References get().
Self& pcl::geometry::VertexIndex::operator-- () inline
Decrement operators (with boost::operators): -- (pre and post)
Definition at line 141 of file mesh_indices.h.
Self& pcl::geometry::VertexIndex::operator-= (const Self & other) inline
Subtraction operators (with boost::operators): - -=.
Definition at line 157 of file mesh_indices.h.
References get().
bool pcl::geometry::VertexIndex::operator< (const Self & other) const inline
Comparison operators (with boost::operators): < > <= >=.
Definition at line 119 of file mesh_indices.h.
References get().
bool pcl::geometry::VertexIndex::operator== (const Self & other) const inline
Comparison operators (with boost::operators): == !=.
Definition at line 126 of file mesh_indices.h.
References get().
void pcl::geometry::VertexIndex::set (const int index) inline
Set the index.
Definition at line 112 of file mesh_indices.h.
Friends And Related Function Documentation
std::istream& operator>> (std::istream & is, pcl::geometry::VertexIndex & index) friend
istream operator.
Definition at line 181 of file mesh_indices.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/geometry/include/pcl/geometry/mesh_indices.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:59