Point Cloud Library (PCL): ON_FixedSizePool Class Reference
ON_FixedSizePool Class Reference
#include <pcl/surface/3rdparty/opennurbs/opennurbs_fsp.h>
Public Member Functions
ON_FixedSizePool ()
~ON_FixedSizePool ()
bool Create (size_t sizeof_element, size_t element_count_estimate, size_t block_element_capacity)
size_t SizeofElement () const
void * AllocateElement ()
void ReturnElement (void *p)
void ReturnAll ()
void Destroy ()
size_t ActiveElementCount () const
size_t TotalElementCount () const
void * FirstElement ()
void * FirstElement (size_t element_index)
void * NextElement ()
void * FirstBlock (size_t *block_element_count)
void * NextBlock (size_t *block_element_count)
void * Element (size_t element_index) const
void SetHeap (ON_MEMORY_POOL *heap)
ON_MEMORY_POOL * Heap ()
void EmergencyDestroy ()
Friends
class ON_FixedSizePoolIterator
Detailed Description
Definition at line 19 of file opennurbs_fsp.h.
Constructor & Destructor Documentation
ON_FixedSizePool::ON_FixedSizePool ()
ON_FixedSizePool::~ON_FixedSizePool ()
Member Function Documentation
size_t ON_FixedSizePool::ActiveElementCount () const
Referenced by ON_SimpleFixedSizePool< T >::ActiveElementCount().
void* ON_FixedSizePool::AllocateElement ()
Referenced by ON_SimpleFixedSizePool< T >::AllocateElement().
bool ON_FixedSizePool::Create (size_t sizeof_element, size_t element_count_estimate, size_t block_element_capacity)
Referenced by ON_SimpleFixedSizePool< T >::Create().
void ON_FixedSizePool::Destroy ()
Referenced by ON_SimpleFixedSizePool< T >::Destroy(), and ON_SimpleFixedSizePool< T >::~ON_SimpleFixedSizePool().
void* ON_FixedSizePool::Element (size_t element_index) const
Referenced by ON_SimpleFixedSizePool< T >::Element().
void ON_FixedSizePool::EmergencyDestroy ()
Referenced by ON_SimpleFixedSizePool< T >::EmergencyDestroy().
void* ON_FixedSizePool::FirstBlock (size_t * block_element_count)
Referenced by ON_SimpleFixedSizePool< T >::FirstBlock().
void* ON_FixedSizePool::FirstElement ()
Referenced by ON_SimpleFixedSizePool< T >::FirstElement().
void* ON_FixedSizePool::FirstElement (size_t element_index)
ON_MEMORY_POOL* ON_FixedSizePool::Heap ()
Referenced by ON_SimpleFixedSizePool< T >::Heap().
void* ON_FixedSizePool::NextBlock (size_t * block_element_count)
Referenced by ON_SimpleFixedSizePool< T >::NextBlock().
void* ON_FixedSizePool::NextElement ()
Referenced by ON_SimpleFixedSizePool< T >::NextElement().
void ON_FixedSizePool::ReturnAll ()
Referenced by ON_SimpleFixedSizePool< T >::ReturnAll().
void ON_FixedSizePool::ReturnElement (void * p)
Referenced by ON_SimpleFixedSizePool< T >::ReturnElement().
void ON_FixedSizePool::SetHeap (ON_MEMORY_POOL * heap)
Referenced by ON_SimpleFixedSizePool< T >::SetHeap().
size_t ON_FixedSizePool::SizeofElement () const
Referenced by ON_SimpleFixedSizePool< T >::SizeofElement().
size_t ON_FixedSizePool::TotalElementCount () const
Referenced by ON_SimpleFixedSizePool< T >::TotalElementCount().
Friends And Related Function Documentation
friend class ON_FixedSizePoolIterator friend
Definition at line 329 of file opennurbs_fsp.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/surface/include/pcl/surface/3rdparty/opennurbs/opennurbs_fsp.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:40