Point Cloud Library (PCL): pcl::gpu::DeviceArray2D< T > Class Template Reference
pcl::gpu::DeviceArray2D< T > Class Template Reference
DeviceArray2D class
#include </home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/device_array.h>
Public Types
enum { elem_size = sizeof(T) }
Element size.
typedef T type
Element type.
Public Member Functions
DeviceArray2D ()
Empty constructor.
DeviceArray2D (int rows, int cols)
Allocates internal buffer in GPU memory.
DeviceArray2D (int rows, int cols, void *data, size_t stepBytes)
Initializes with user allocated buffer.
DeviceArray2D (const DeviceArray2D &other)
Copy constructor.
DeviceArray2D & operator= (const DeviceArray2D &other)
Assignment operator.
void create (int rows, int cols)
Allocates internal buffer in GPU memory.
void release ()
Decrements reference counter and releases internal buffer if needed.
void copyTo (DeviceArray2D &other) const
Performs data copying.
void upload (const void *host_ptr, size_t host_step, int rows, int cols)
Uploads data to internal buffer in GPU memory.
void download (void *host_ptr, size_t host_step) const
Downloads data from internal buffer to CPU memory.
void swap (DeviceArray2D &other_arg)
Performs swap of data pointed with another device array.
template<class A >
void upload (const std::vector< T, A > &data, int cols)
Uploads data to internal buffer in GPU memory.
template<class A >
void download (std::vector< T, A > &data, int &cols) const
Downloads data from internal buffer to CPU memory.
T * ptr (int y=0)
Returns pointer to given row in internal buffer.
const T * ptr (int y=0) const
Returns const pointer to given row in internal buffer.
operator T * ()
Returns pointer for internal buffer in GPU memory.
operator const T * () const
Returns const pointer for internal buffer in GPU memory.
int cols () const
Returns number of elements in each row.
int rows () const
Returns number of rows.
size_t elem_step () const
Returns step in elements.
Public Member Functions inherited from pcl::gpu::DeviceMemory2D
DeviceMemory2D ()
Empty constructor.
~DeviceMemory2D ()
Destructor.
DeviceMemory2D (int rows_arg, int colsBytes_arg)
Allocates internal buffer in GPU memory.
DeviceMemory2D (int rows_arg, int colsBytes_arg, void *data_arg, size_t step_arg)
Initializes with user allocated buffer.
DeviceMemory2D (const DeviceMemory2D &other_arg)
Copy constructor.
DeviceMemory2D & operator= (const DeviceMemory2D &other_arg)
Assignment operator.
void create (int rows_arg, int colsBytes_arg)
Allocates internal buffer in GPU memory.
void release ()
Decrements reference counter and releases internal buffer if needed.
void copyTo (DeviceMemory2D &other) const
Performs data copying.
void upload (const void *host_ptr_arg, size_t host_step_arg, int rows_arg, int colsBytes_arg)
Uploads data to internal buffer in GPU memory.
void download (void *host_ptr_arg, size_t host_step_arg) const
Downloads data from internal buffer to CPU memory.
void swap (DeviceMemory2D &other_arg)
Performs swap of data pointed with another device memory.
template<class T >
T * ptr (int y_arg=0)
Returns pointer to given row in internal buffer.
template<class T >
const T * ptr (int y_arg=0) const
Returns constant pointer to given row in internal buffer.
template<class U >
operator PtrStep< U > () const
Conversion to PtrStep for passing to kernel functions.
template<class U >
operator PtrStepSz< U > () const
Conversion to PtrStepSz for passing to kernel functions.
bool empty () const
Returns true if unallocated otherwise false.
int colsBytes () const
Returns number of bytes in each row.
int rows () const
Returns number of rows.
size_t step () const
Returns stride between two consecutive rows in bytes for internal buffer.
Detailed Description
template<class T>
class pcl::gpu::DeviceArray2D< T >
DeviceArray2D class
Note
Typed container for pitched GPU memory with reference counting.
Author
Anatoly Baksheev
Definition at line 154 of file device_array.h.
Member Typedef Documentation
template<class T> typedef T pcl::gpu::DeviceArray2D< T >::type
Element type.
Definition at line 158 of file device_array.h.
Member Enumeration Documentation
template<class T> anonymous enum
Element size.
Enumerator
elem_size
Definition at line 161 of file device_array.h.
Constructor & Destructor Documentation
template<class T > pcl::gpu::DeviceArray2D< T >::DeviceArray2D () inline
Empty constructor.
Definition at line 76 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray2D< T >::DeviceArray2D (int rows, int cols) inline
Allocates internal buffer in GPU memory.
Parameters
rows number of rows to allocate
cols number of elements in each row
Definition at line 77 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray2D< T >::DeviceArray2D (int rows, int cols, void * data, size_t stepBytes) inline
Initializes with user allocated buffer.
Reference counting is disabled in this case.
Parameters
rows number of rows
cols number of elements in each row
data pointer to buffer
stepBytes stride between two consecutive rows in bytes
Definition at line 78 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray2D< T >::DeviceArray2D (const DeviceArray2D< T > & other) inline
Copy constructor.
Just increments reference counter.
Definition at line 79 of file device_array.hpp.
Member Function Documentation
template<class T > int pcl::gpu::DeviceArray2D< T >::cols () const inline
Returns number of elements in each row.
Definition at line 109 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::colsBytes().
Referenced by pcl::gpu::AsyncCopy< T >::download(), pcl::gpu::TextureBinder::TextureBinder(), and pcl::gpu::AsyncCopy< T >::upload().
template<class T > void pcl::gpu::DeviceArray2D< T >::copyTo (DeviceArray2D< T > & other) const inline
Performs data copying.
If destination size differs it will be reallocated.
Parameters
other destination container
Definition at line 88 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::copyTo().
template<class T > void pcl::gpu::DeviceArray2D< T >::create (int rows, int cols) inline
Allocates internal buffer in GPU memory.
If internal buffer was created before the function recreates it with new size. If new and old sizes are equal it does nothing.
Parameters
rows number of rows to allocate
cols number of elements in each row
Definition at line 83 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::create().
template<class T > void pcl::gpu::DeviceArray2D< T >::download (void * host_ptr, size_t host_step) const inline
Downloads data from internal buffer to CPU memory.
User is responsible for correct host buffer size.
Parameters
host_ptr pointer to host buffer to download
host_step stride between two consecutive rows in bytes for host buffer
Definition at line 92 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::download().
template<class T> template<class A > void pcl::gpu::DeviceArray2D< T >::download (std::vector< T, A > & data, int & cols) const inline
Downloads data from internal buffer to CPU memory.
Parameters
data host vector to download to
cols Output stride in elements between two consecutive rows for host vector.
Definition at line 98 of file device_array.hpp.
template<class T > size_t pcl::gpu::DeviceArray2D< T >::elem_step () const inline
Returns step in elements.
Definition at line 112 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::step().
template<class T > pcl::gpu::DeviceArray2D< T >::operator const T * () const inline
Returns const pointer for internal buffer in GPU memory.
Definition at line 107 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray2D< T >::operator T * () inline
Returns pointer for internal buffer in GPU memory.
Definition at line 106 of file device_array.hpp.
template<class T > pcl::gpu::DeviceArray2D< T > & pcl::gpu::DeviceArray2D< T >::operator= (const DeviceArray2D< T > & other) inline
Assignment operator.
Just increments reference counter.
Definition at line 80 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::operator=().
template<class T > T * pcl::gpu::DeviceArray2D< T >::ptr (int y = 0) inline
Returns pointer to given row in internal buffer.
Parameters
y row index
Definition at line 103 of file device_array.hpp.
Referenced by pcl::gpu::AsyncCopy< T >::download(), pcl::gpu::TextureBinder::TextureBinder(), and pcl::gpu::AsyncCopy< T >::upload().
template<class T > const T * pcl::gpu::DeviceArray2D< T >::ptr (int y = 0) const inline
Returns const pointer to given row in internal buffer.
Parameters
y row index
Definition at line 104 of file device_array.hpp.
template<class T > void pcl::gpu::DeviceArray2D< T >::release () inline
Decrements reference counter and releases internal buffer if needed.
Definition at line 85 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::release().
template<class T > int pcl::gpu::DeviceArray2D< T >::rows () const inline
Returns number of rows.
Definition at line 110 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::rows().
Referenced by pcl::gpu::AsyncCopy< T >::download(), pcl::gpu::TextureBinder::TextureBinder(), and pcl::gpu::AsyncCopy< T >::upload().
template<class T > void pcl::gpu::DeviceArray2D< T >::swap (DeviceArray2D< T > & other_arg)
Performs swap of data pointed with another device array.
Parameters
other_arg device array to swap with
Definition at line 101 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::swap().
template<class T > void pcl::gpu::DeviceArray2D< T >::upload (const void * host_ptr, size_t host_step, int rows, int cols) inline
Uploads data to internal buffer in GPU memory.
It calls create() inside to ensure that intenal buffer size is enough.
Parameters
host_ptr pointer to host buffer to upload
host_step stride between two consecutive rows in bytes for host buffer
rows number of rows to upload
cols number of elements in each row
Definition at line 90 of file device_array.hpp.
References pcl::gpu::DeviceMemory2D::upload().
template<class T> template<class A > void pcl::gpu::DeviceArray2D< T >::upload (const std::vector< T, A > & data, int cols) inline
Uploads data to internal buffer in GPU memory.
It calls create() inside to ensure that intenal buffer size is enough.
Parameters
data host vector to upload from
cols stride in elements between two consecutive rows for host buffer
Definition at line 95 of file device_array.hpp.
The documentation for this class was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/device_array.h
/home/travis/build/PointCloudLibrary/pcl/gpu/containers/include/pcl/gpu/containers/impl/device_array.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:00