Point Cloud Library (PCL): pcl::recognition::ORROctree::Node Class Reference
pcl::recognition::ORROctree::Node Class Reference
#include <pcl/recognition/ransac_based/orr_octree.h>
Classes
class Data
Public Member Functions
Node ()
virtual ~Node ()
void setCenter (const float *c)
void setBounds (const float *b)
void setParent (Node *parent)
void setData (Node::Data *data)
void computeRadius ()
Computes the "radius" of the node which is half the diagonal length.
const float * getCenter () const
const float * getBounds () const
void getBounds (float b[6]) const
Node * getChild (int id)
Node * getChildren ()
Node::Data * getData ()
const Node::Data * getData () const
void setUserData (void *user_data)
Node * getParent ()
bool hasData ()
bool hasChildren ()
float getRadius ()
Computes the "radius" of the node which is half the diagonal length.
bool createChildren ()
void deleteChildren ()
void deleteData ()
void makeNeighbors (Node *node)
Make this and 'node' neighbors by inserting each node in the others node neighbor set.
Protected Attributes
Node::Data * data_
float center_ [3]
float bounds_ [6]
float radius_
Node * parent_
Node * children_
Detailed Description
Definition at line 78 of file orr_octree.h.
Constructor & Destructor Documentation
pcl::recognition::ORROctree::Node::Node () inline
Definition at line 168 of file orr_octree.h.
virtual pcl::recognition::ORROctree::Node::~Node () inline
Definition at line 174 of file orr_octree.h.
Member Function Documentation
void pcl::recognition::ORROctree::Node::computeRadius () inline
Computes the "radius" of the node which is half the diagonal length.
Definition at line 194 of file orr_octree.h.
References pcl::recognition::aux::length3().
bool pcl::recognition::ORROctree::Node::createChildren ()
Referenced by pcl::recognition::ORROctree::createLeaf().
void pcl::recognition::ORROctree::Node::deleteChildren () inline
Definition at line 244 of file orr_octree.h.
void pcl::recognition::ORROctree::Node::deleteData () inline
Definition at line 254 of file orr_octree.h.
const float* pcl::recognition::ORROctree::Node::getBounds () const inline
Definition at line 204 of file orr_octree.h.
void pcl::recognition::ORROctree::Node::getBounds (float b[6]) const inline
Definition at line 207 of file orr_octree.h.
const float* pcl::recognition::ORROctree::Node::getCenter () const inline
Definition at line 201 of file orr_octree.h.
Referenced by pcl::recognition::ORROctree::createLeaf(), pcl::recognition::ORROctree::getLeaf(), and pcl::recognition::ORROctree::insertNeighbors().
Node* pcl::recognition::ORROctree::Node::getChild (int id) inline
Definition at line 213 of file orr_octree.h.
Referenced by pcl::recognition::ORROctree::createLeaf(), and pcl::recognition::ORROctree::getLeaf().
Node* pcl::recognition::ORROctree::Node::getChildren () inline
Definition at line 216 of file orr_octree.h.
Node::Data* pcl::recognition::ORROctree::Node::getData () inline
Definition at line 219 of file orr_octree.h.
Referenced by pcl::recognition::ORROctreeZProjection::Set::compare_nodes_z(), pcl::recognition::ORROctree::createLeaf(), and makeNeighbors().
const Node::Data* pcl::recognition::ORROctree::Node::getData () const inline
Definition at line 222 of file orr_octree.h.
Node* pcl::recognition::ORROctree::Node::getParent () inline
Definition at line 228 of file orr_octree.h.
float pcl::recognition::ORROctree::Node::getRadius () inline
Computes the "radius" of the node which is half the diagonal length.
Definition at line 238 of file orr_octree.h.
bool pcl::recognition::ORROctree::Node::hasChildren () inline
Definition at line 234 of file orr_octree.h.
Referenced by pcl::recognition::ORROctree::getLeaf().
bool pcl::recognition::ORROctree::Node::hasData () inline
Definition at line 231 of file orr_octree.h.
void pcl::recognition::ORROctree::Node::makeNeighbors (Node * node) inline
Make this and 'node' neighbors by inserting each node in the others node neighbor set.
Nothing happens of either of the nodes has no data.
Definition at line 266 of file orr_octree.h.
References getData(), and pcl::recognition::ORROctree::Node::Data::insertNeighbor().
Referenced by pcl::recognition::ORROctree::insertNeighbors().
void pcl::recognition::ORROctree::Node::setBounds (const float * b) inline
Definition at line 184 of file orr_octree.h.
void pcl::recognition::ORROctree::Node::setCenter (const float * c) inline
Definition at line 181 of file orr_octree.h.
void pcl::recognition::ORROctree::Node::setData (Node::Data * data) inline
Definition at line 190 of file orr_octree.h.
Referenced by pcl::recognition::ORROctree::createLeaf().
void pcl::recognition::ORROctree::Node::setParent (Node * parent) inline
Definition at line 187 of file orr_octree.h.
void pcl::recognition::ORROctree::Node::setUserData (void * user_data) inline
Definition at line 225 of file orr_octree.h.
Member Data Documentation
float pcl::recognition::ORROctree::Node::bounds_[6] protected
Definition at line 277 of file orr_octree.h.
float pcl::recognition::ORROctree::Node::center_[3] protected
Definition at line 277 of file orr_octree.h.
Node * pcl::recognition::ORROctree::Node::children_ protected
Definition at line 278 of file orr_octree.h.
Node::Data* pcl::recognition::ORROctree::Node::data_ protected
Definition at line 276 of file orr_octree.h.
Node* pcl::recognition::ORROctree::Node::parent_ protected
Definition at line 278 of file orr_octree.h.
float pcl::recognition::ORROctree::Node::radius_ protected
Definition at line 277 of file orr_octree.h.
The documentation for this class was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/recognition/include/pcl/recognition/ransac_based/orr_octree.h
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:17