Point Cloud Library (PCL): pcl::gpu::people::trees Namespace Reference
pcl::gpu::people::trees Namespace Reference
Classes
struct AttribLocation
struct Node
class Histogram
struct HistogramPair
struct SplitPoint
struct LabeledAttrib
struct LabeledFeature
Typedefs
typedef int16_t Attrib
typedef uint8_t Label
typedef uint32_t Label32
typedef uint16_t Depth
Enumerations
enum { NUM_ATTRIBS = 2000 }
enum { NUM_LABELS = 32 }
Functions
std::ostream & operator<< (std::ostream &os, const AttribLocation &aloc)
std::istream & operator>> (std::istream &is, AttribLocation &aloc)
std::istream & operator>> (std::istream &is, Node &n)
void writeAttribLocs (const std::string &filename, const std::vector< AttribLocation > &alocs)
void readAttribLocs (const std::string &filename, std::vector< AttribLocation > &alocs)
void readThreshs (const std::string &filename, std::vector< Attrib > &threshs)
void writeThreshs (const std::string &filename, const std::vector< Attrib > &threshs)
int loadTree (std::istream &is, std::vector< Node > &tree, std::vector< Label > &leaves)
The stream points to ascii data that goes: TreeHeight du1 dv1 du2 dv2 thresh du1 dv1 du2 dv2 thresh ............
int loadTree (const std::string &filename, std::vector< Node > &tree, std::vector< Label > &leaves)
void runThroughTree (int maxDepth, const std::vector< Node > &tree, const std::vector< Label > &leaves, int W, int H, const uint16_t *dmap, Label *lmap)
static uint64_t numElements (const Histogram &h)
static double entropy (const Histogram &h)
This is cool.
static double entropy_merged (const HistogramPair &hp)
This is a little weird.
static double informationGain (const HistogramPair &hp)
This will compute the gain in information resulting from the split.
static std::ostream & operator<< (std::ostream &os, const Histogram &h)
static std::istream & operator>> (std::istream &is, Histogram &h)
static std::ostream & operator<< (std::ostream &os, const HistogramPair &hp)
static std::istream & operator>> (std::istream &is, HistogramPair &hp)
static void writeLabeledFeatureVec (std::ostream &os, const std::vector< LabeledFeature > &lfs)
std::ostream & operator<< (std::ostream &os, const SplitPoint &sp)
std::istream & operator>> (std::istream &is, SplitPoint &sp)
void writeInfoFile (const std::string &filename, int attribId, Attrib threshold, double gain, const HistogramPair &HP)
void readInfoFile (const std::string &filename, int &attribId, Attrib &threshold, double &gain, HistogramPair &HP)
Variables
static const double focal = 1000.
Typedef Documentation
typedef int16_t pcl::gpu::people::trees::Attrib
Definition at line 73 of file tree.h.
typedef uint16_t pcl::gpu::people::trees::Depth
Definition at line 76 of file tree.h.
typedef uint8_t pcl::gpu::people::trees::Label
Definition at line 74 of file tree.h.
typedef uint32_t pcl::gpu::people::trees::Label32
Definition at line 75 of file tree.h.
Enumeration Type Documentation
anonymous enum
Enumerator
NUM_ATTRIBS
Definition at line 61 of file tree.h.
anonymous enum
Enumerator
NUM_LABELS
Definition at line 62 of file tree.h.
Function Documentation
static double pcl::gpu::people::trees::entropy (const Histogram & h) inline static
This is cool.
Definition at line 94 of file tree_train.h.
References numElements().
Referenced by entropy_merged(), and informationGain().
static double pcl::gpu::people::trees::entropy_merged (const HistogramPair & hp) inline static
This is a little weird.
. it will just compute the entropy of the merged histograms
Definition at line 109 of file tree_train.h.
References entropy(), pcl::gpu::people::trees::HistogramPair::h_false(), pcl::gpu::people::trees::HistogramPair::h_true(), and numElements().
Referenced by informationGain().
static double pcl::gpu::people::trees::informationGain (const HistogramPair & hp) inline static
This will compute the gain in information resulting from the split.
Definition at line 128 of file tree_train.h.
References entropy(), entropy_merged(), pcl::gpu::people::trees::HistogramPair::h_false(), pcl::gpu::people::trees::HistogramPair::h_true(), and numElements().
int pcl::gpu::people::trees::loadTree (std::istream & is, std::vector< Node > & tree, std::vector< Label > & leaves)
The stream points to ascii data that goes:
TreeHeight du1 dv1 du2 dv2 thresh du1 dv1 du2 dv2 thresh ............
label label
there are 2^threeheight -1 nodes ([du1 dv1 du2 dv2 thresh] lines) there are 2^threeheight leaves ([label] lines)
int pcl::gpu::people::trees::loadTree (const std::string & filename, std::vector< Node > & tree, std::vector< Label > & leaves)
static uint64_t pcl::gpu::people::trees::numElements (const Histogram & h) inline static
Definition at line 85 of file tree_train.h.
Referenced by entropy(), entropy_merged(), and informationGain().
std::ostream& pcl::gpu::people::trees::operator<< (std::ostream & os, const AttribLocation & aloc) inline
Definition at line 107 of file tree.h.
References pcl::gpu::people::trees::AttribLocation::du1, pcl::gpu::people::trees::AttribLocation::du2, pcl::gpu::people::trees::AttribLocation::dv1, and pcl::gpu::people::trees::AttribLocation::dv2.
static std::ostream& pcl::gpu::people::trees::operator<< (std::ostream & os, const Histogram & h) inline static
Definition at line 145 of file tree_train.h.
static std::ostream& pcl::gpu::people::trees::operator<< (std::ostream & os, const HistogramPair & hp) inline static
Definition at line 159 of file tree_train.h.
References pcl::gpu::people::trees::HistogramPair::h_false(), and pcl::gpu::people::trees::HistogramPair::h_true().
std::ostream& pcl::gpu::people::trees::operator<< (std::ostream & os, const SplitPoint & sp) inline
Definition at line 187 of file tree_train.h.
References pcl::gpu::people::trees::SplitPoint::attribId, and pcl::gpu::people::trees::SplitPoint::threshold.
std::istream& pcl::gpu::people::trees::operator>> (std::istream & is, AttribLocation & aloc) inline
Definition at line 108 of file tree.h.
References pcl::gpu::people::trees::AttribLocation::du1, pcl::gpu::people::trees::AttribLocation::du2, pcl::gpu::people::trees::AttribLocation::dv1, and pcl::gpu::people::trees::AttribLocation::dv2.
std::istream& pcl::gpu::people::trees::operator>> (std::istream & is, Node & n) inline
Definition at line 109 of file tree.h.
References pcl::gpu::people::trees::Node::loc, and pcl::gpu::people::trees::Node::thresh.
static std::istream& pcl::gpu::people::trees::operator>> (std::istream & is, Histogram & h) inline static
Definition at line 151 of file tree_train.h.
static std::istream& pcl::gpu::people::trees::operator>> (std::istream & is, HistogramPair & hp) inline static
Definition at line 165 of file tree_train.h.
References pcl::gpu::people::trees::HistogramPair::h_false(), and pcl::gpu::people::trees::HistogramPair::h_true().
std::istream& pcl::gpu::people::trees::operator>> (std::istream & is, SplitPoint & sp) inline
Definition at line 192 of file tree_train.h.
References pcl::gpu::people::trees::SplitPoint::attribId, and pcl::gpu::people::trees::SplitPoint::threshold.
void pcl::gpu::people::trees::readAttribLocs (const std::string & filename, std::vector< AttribLocation > & alocs)
void pcl::gpu::people::trees::readInfoFile (const std::string & filename, int & attribId, Attrib & threshold, double & gain, HistogramPair & HP) inline
Definition at line 213 of file tree_train.h.
void pcl::gpu::people::trees::readThreshs (const std::string & filename, std::vector< Attrib > & threshs)
void pcl::gpu::people::trees::runThroughTree (int maxDepth, const std::vector< Node > & tree, const std::vector< Label > & leaves, int W, int H, const uint16_t * dmap, Label * lmap)
void pcl::gpu::people::trees::writeAttribLocs (const std::string & filename, const std::vector< AttribLocation > & alocs)
void pcl::gpu::people::trees::writeInfoFile (const std::string & filename, int attribId, Attrib threshold, double gain, const HistogramPair & HP) inline
Definition at line 200 of file tree_train.h.
static void pcl::gpu::people::trees::writeLabeledFeatureVec (std::ostream & os, const std::vector< LabeledFeature > & lfs) static
Definition at line 174 of file tree_train.h.
void pcl::gpu::people::trees::writeThreshs (const std::string & filename, const std::vector< Attrib > & threshs)
Variable Documentation
const double pcl::gpu::people::trees::focal = 1000. static
Definition at line 57 of file tree.h.
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:03