Point Cloud Library (PCL): pcl::device::kinfuLS::Eigen33 Struct Reference
pcl::device::kinfuLS::Eigen33 Struct Reference
#include </home/travis/build/PointCloudLibrary/pcl/gpu/kinfu_large_scale/src/cuda/utils.hpp>
Classes
struct MiniMat
Public Types
typedef MiniMat< 3 > Mat33
typedef MiniMat< 4 > Mat43
Public Member Functions
__device__ __forceinline__ Eigen33 (volatile float *mat_pkg_arg)
__device__ __forceinline__ void compute (Mat33 &tmp, Mat33 &vec_tmp, Mat33 &evecs, float3 &evals)
Static Public Member Functions
static __forceinline__
__device__ float3 unitOrthogonal (const float3 &src)
Detailed Description
Definition at line 193 of file utils.hpp.
Member Typedef Documentation
typedef MiniMat<3> pcl::device::kinfuLS::Eigen33::Mat33
Definition at line 203 of file utils.hpp.
typedef MiniMat<4> pcl::device::kinfuLS::Eigen33::Mat43
Definition at line 204 of file utils.hpp.
Constructor & Destructor Documentation
__device__ __forceinline__ pcl::device::kinfuLS::Eigen33::Eigen33 (volatile float * mat_pkg_arg) inline
Definition at line 241 of file utils.hpp.
Member Function Documentation
__device__ __forceinline__ void pcl::device::kinfuLS::Eigen33::compute (Mat33 & tmp, Mat33 & vec_tmp, Mat33 & evecs, float3 & evals) inline
Definition at line 243 of file utils.hpp.
References pcl::device::kinfuLS::computeRoots3(), pcl::device::kinfuLS::cross(), pcl::device::kinfuLS::dot(), pcl::device::kinfuLS::normalized(), and unitOrthogonal().
static __forceinline__ __device__ float3 pcl::device::kinfuLS::Eigen33::unitOrthogonal (const float3 & src) inline static
Definition at line 208 of file utils.hpp.
Referenced by compute().
The documentation for this struct was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/gpu/kinfu_large_scale/src/cuda/utils.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:56