Point Cloud Library (PCL): pcl::device::kinfuLS::Block Struct Reference
pcl::device::kinfuLS::Block Struct Reference
#include </home/travis/build/PointCloudLibrary/pcl/gpu/kinfu_large_scale/src/cuda/utils.hpp>
Static Public Member Functions
static __device__
__forceinline__ unsigned int stride ()
static __device__
__forceinline__ int flattenedThreadId ()
template<int CTA_SIZE, typename T , class BinOp >
static __device__
__forceinline__ void reduce (volatile T *buffer, BinOp op)
template<int CTA_SIZE, typename T , class BinOp >
static __device__ __forceinline__ T reduce (volatile T *buffer, T init, BinOp op)
Detailed Description
Definition at line 481 of file utils.hpp.
Member Function Documentation
static __device__ __forceinline__ int pcl::device::kinfuLS::Block::flattenedThreadId () inline static
Definition at line 489 of file utils.hpp.
Referenced by pcl::device::kinfuLS::Emulation::All(), pcl::device::kinfuLS::Emulation::Ballot(), and reduce().
template<int CTA_SIZE, typename T , class BinOp > static __device__ __forceinline__ void pcl::device::kinfuLS::Block::reduce (volatile T * buffer, BinOp op) inline static
Definition at line 495 of file utils.hpp.
References flattenedThreadId().
template<int CTA_SIZE, typename T , class BinOp > static __device__ __forceinline__ T pcl::device::kinfuLS::Block::reduce (volatile T * buffer, T init, BinOp op) inline static
Definition at line 517 of file utils.hpp.
References flattenedThreadId().
static __device__ __forceinline__ unsigned int pcl::device::kinfuLS::Block::stride () inline static
Definition at line 483 of file utils.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/gpu/kinfu_large_scale/src/cuda/utils.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:41:56