Point Cloud Library (PCL): pcl::gpu::DataSource Struct Reference
pcl::gpu::DataSource Struct Reference
#include </home/travis/build/PointCloudLibrary/pcl/gpu/features/test/data_source.hpp>
Classes
struct Normal2PointXYZ
Public Member Functions
DataSource (const std::string &file="d:/office_chair_model.pcd")
void generateColor ()
void estimateNormals ()
void runCloudViewer () const
void findKNNeghbors ()
void findRadiusNeghbors (float radius=-1)
void getNeghborsArray (std::vector< int > &data)
void generateSurface ()
void generateIndices (size_t step=100)
Public Attributes
PointCloud< PointXYZ >::Ptr cloud
PointCloud< PointXYZ >::Ptr surface
IndicesPtr indices
PointCloud< Normal >::Ptr normals
PointCloud< Normal >::Ptr normals_surface
float radius
std::vector< std::vector< int > > neighbors_all
std::vector< int > sizes
int max_nn_size
Static Public Attributes
static const int k = 32
static const int max_elements = 500
Detailed Description
Definition at line 65 of file data_source.hpp.
Constructor & Destructor Documentation
pcl::gpu::DataSource::DataSource (const std::string & file = "d:/office_chair_model.pcd") inline
Definition at line 82 of file data_source.hpp.
References cloud, pcl::getMinMax3D(), radius, and pcl::PCDReader::read().
Member Function Documentation
void pcl::gpu::DataSource::estimateNormals () inline
Definition at line 110 of file data_source.hpp.
References cloud, pcl::Feature< PointInT, PointOutT >::compute(), k, normals, pcl::NormalEstimation< PointInT, PointOutT >::setInputCloud(), pcl::Feature< PointInT, PointOutT >::setKSearch(), and pcl::Feature< PointInT, PointOutT >::setSearchMethod().
void pcl::gpu::DataSource::findKNNeghbors () inline
Definition at line 128 of file data_source.hpp.
References cloud, k, max_nn_size, pcl::KdTreeFLANN< PointT, Dist >::nearestKSearch(), neighbors_all, pcl::PointCloud< T >::points, pcl::KdTreeFLANN< PointT, Dist >::setInputCloud(), and sizes.
void pcl::gpu::DataSource::findRadiusNeghbors (float radius = -1) inline
Definition at line 145 of file data_source.hpp.
References cloud, max_nn_size, neighbors_all, pcl::PointCloud< T >::points, radius, pcl::KdTreeFLANN< PointT, Dist >::radiusSearch(), pcl::KdTreeFLANN< PointT, Dist >::setInputCloud(), and sizes.
void pcl::gpu::DataSource::generateColor () inline
Definition at line 95 of file data_source.hpp.
References cloud, and pcl::PointCloud< T >::points.
void pcl::gpu::DataSource::generateIndices (size_t step = 100) inline
Definition at line 191 of file data_source.hpp.
References cloud, indices, and pcl::PointCloud< T >::points.
void pcl::gpu::DataSource::generateSurface () inline
Definition at line 172 of file data_source.hpp.
References cloud, pcl::PointCloud< T >::height, normals, normals_surface, pcl::PointCloud< T >::points, surface, and pcl::PointCloud< T >::width.
void pcl::gpu::DataSource::getNeghborsArray (std::vector< int > & data) inline
Definition at line 164 of file data_source.hpp.
References max_nn_size, neighbors_all, and pcl::gpu::PtrStep< T >::ptr().
void pcl::gpu::DataSource::runCloudViewer () const inline
Definition at line 121 of file data_source.hpp.
References cloud, pcl::visualization::CloudViewer::showCloud(), and pcl::visualization::CloudViewer::wasStopped().
Member Data Documentation
PointCloud<PointXYZ>::Ptr pcl::gpu::DataSource::cloud
Definition at line 70 of file data_source.hpp.
Referenced by DataSource(), estimateNormals(), findKNNeghbors(), findRadiusNeghbors(), generateColor(), generateIndices(), generateSurface(), and runCloudViewer().
IndicesPtr pcl::gpu::DataSource::indices
Definition at line 72 of file data_source.hpp.
Referenced by generateIndices().
const int pcl::gpu::DataSource::k = 32 static
Definition at line 67 of file data_source.hpp.
Referenced by estimateNormals(), and findKNNeghbors().
const int pcl::gpu::DataSource::max_elements = 500 static
Definition at line 68 of file data_source.hpp.
int pcl::gpu::DataSource::max_nn_size
Definition at line 80 of file data_source.hpp.
Referenced by findKNNeghbors(), findRadiusNeghbors(), and getNeghborsArray().
std::vector< std::vector<int> > pcl::gpu::DataSource::neighbors_all
Definition at line 78 of file data_source.hpp.
Referenced by findKNNeghbors(), findRadiusNeghbors(), and getNeghborsArray().
PointCloud<Normal>::Ptr pcl::gpu::DataSource::normals
Definition at line 74 of file data_source.hpp.
Referenced by estimateNormals(), and generateSurface().
PointCloud<Normal>::Ptr pcl::gpu::DataSource::normals_surface
Definition at line 75 of file data_source.hpp.
Referenced by generateSurface().
float pcl::gpu::DataSource::radius
Definition at line 76 of file data_source.hpp.
Referenced by DataSource(), and findRadiusNeghbors().
std::vector<int> pcl::gpu::DataSource::sizes
Definition at line 79 of file data_source.hpp.
Referenced by findKNNeghbors(), and findRadiusNeghbors().
PointCloud<PointXYZ>::Ptr pcl::gpu::DataSource::surface
Definition at line 71 of file data_source.hpp.
Referenced by generateSurface().
The documentation for this struct was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/gpu/features/test/data_source.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:03