Point Cloud Library (PCL): pcl::tracking::ParticleXYZRPY Struct Reference
pcl::tracking::ParticleXYZRPY Struct Reference
#include <pcl/tracking/impl/tracking.hpp>
Public Member Functions
ParticleXYZRPY ()
ParticleXYZRPY (float _x, float _y, float _z)
ParticleXYZRPY (float _x, float _y, float _z, float _roll, float _pitch, float _yaw)
void sample (const std::vector< double > &mean, const std::vector< double > &cov)
void zero ()
Eigen::Affine3f toEigenMatrix () const
float operator[] (unsigned int i)
Static Public Member Functions
static int stateDimension ()
static
pcl::tracking::ParticleXYZRPY toState (const Eigen::Affine3f &trans)
Additional Inherited Members
Public Attributes inherited from pcl::tracking::_ParticleXYZRPY
PCL_ADD_POINT4D
union {
struct {
float roll
float pitch
float yaw
float weight
}
float data_c [4]
};
Detailed Description
Definition at line 30 of file tracking.hpp.
Constructor & Destructor Documentation
pcl::tracking::ParticleXYZRPY::ParticleXYZRPY () inline
Definition at line 32 of file tracking.hpp.
pcl::tracking::ParticleXYZRPY::ParticleXYZRPY (float _x, float _y, float _z) inline
Definition at line 38 of file tracking.hpp.
pcl::tracking::ParticleXYZRPY::ParticleXYZRPY (float _x, float _y, float _z, float _roll, float _pitch, float _yaw) inline
Definition at line 45 of file tracking.hpp.
Member Function Documentation
float pcl::tracking::ParticleXYZRPY::operator[] (unsigned int i) inline
Definition at line 127 of file tracking.hpp.
void pcl::tracking::ParticleXYZRPY::sample (const std::vector< double > & mean, const std::vector< double > & cov) inline
Definition at line 56 of file tracking.hpp.
References pcl::getEulerAngles(), pcl::getTransformation(), and pcl::tracking::sampleNormal().
static int pcl::tracking::ParticleXYZRPY::stateDimension () inline static
Definition at line 53 of file tracking.hpp.
Eigen::Affine3f pcl::tracking::ParticleXYZRPY::toEigenMatrix () const inline
Definition at line 111 of file tracking.hpp.
References pcl::getTransformation().
static pcl::tracking::ParticleXYZRPY pcl::tracking::ParticleXYZRPY::toState (const Eigen::Affine3f & trans) inline static
Definition at line 117 of file tracking.hpp.
References pcl::getTranslationAndEulerAngles().
void pcl::tracking::ParticleXYZRPY::zero () inline
Definition at line 100 of file tracking.hpp.
The documentation for this struct was generated from the following file:
/home/travis/build/PointCloudLibrary/pcl/tracking/include/pcl/tracking/impl/tracking.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:42:28