Point Cloud Library (PCL): pcl::PolynomialCalculationsT< real >::Parameters Struct Reference
pcl::PolynomialCalculationsT< real >::Parameters Struct Reference
Parameters used in this class.
#include <pcl/common/polynomial_calculations.h>
Public Member Functions
Parameters ()
void setZeroValue (real new_zero_value)
Set zero_value.
Public Attributes
real zero_value
Every value below this is considered to be zero.
real sqr_zero_value
sqr of the above
Detailed Description
template<typename real>
struct pcl::PolynomialCalculationsT< real >::Parameters
Parameters used in this class.
Definition at line 59 of file polynomial_calculations.h.
Constructor & Destructor Documentation
template<typename real > pcl::PolynomialCalculationsT< real >::Parameters::Parameters () inline
Definition at line 61 of file polynomial_calculations.h.
References pcl::PolynomialCalculationsT< real >::Parameters::setZeroValue().
Member Function Documentation
template<typename real > void pcl::PolynomialCalculationsT< real >::Parameters::setZeroValue (real new_zero_value) inline
Set zero_value.
Definition at line 59 of file polynomial_calculations.hpp.
References pcl::PolynomialCalculationsT< real >::Parameters::sqr_zero_value, and pcl::PolynomialCalculationsT< real >::Parameters::zero_value.
Referenced by pcl::PolynomialCalculationsT< real >::Parameters::Parameters(), and pcl::PolynomialCalculationsT< real >::setZeroValue().
Member Data Documentation
template<typename real > real pcl::PolynomialCalculationsT< real >::Parameters::sqr_zero_value
sqr of the above
Definition at line 67 of file polynomial_calculations.h.
Referenced by pcl::PolynomialCalculationsT< real >::Parameters::setZeroValue(), and pcl::PolynomialCalculationsT< real >::sqrtIsNearlyZero().
template<typename real > real pcl::PolynomialCalculationsT< real >::Parameters::zero_value
Every value below this is considered to be zero.
Definition at line 66 of file polynomial_calculations.h.
Referenced by pcl::PolynomialCalculationsT< real >::isNearlyZero(), and pcl::PolynomialCalculationsT< real >::Parameters::setZeroValue().
The documentation for this struct was generated from the following files:
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/common/polynomial_calculations.h
/home/travis/build/PointCloudLibrary/pcl/common/include/pcl/common/impl/polynomial_calculations.hpp
Except where otherwise noted, the PointClouds.org web pages are licensed under Creative Commons Attribution 3.0.
Pages generated on Thu Oct 11 2018 18:40:54